begin;
select plan(75);
select is((select count(*)::int from pg_class where relnamespace='public'::regnamespace and relname in
  ('wave1_authority_audit_events','wave1_legal_document_versions','wave1_legal_acceptances','wave1_push_installation_ownership','wave1_creator_eligibility')),5,'all Wave 1 authority tables exist');
select is((select count(*)::int from pg_proc where pronamespace='public'::regnamespace and proname in
  ('wave1_session_authority_readback','wave1_legal_requirements_readback','wave1_accept_legal_documents','wave1_entitlement_authority_readback','wave1_push_ownership_readback','wave1_register_push_token','wave1_revoke_push_ownership','wave1_creator_eligibility_readback')),8,'canonical Wave 1 RPC contract exists');
select is((select count(*)::int from pg_class where relnamespace='public'::regnamespace and relname like 'wave1_%' and relkind='r' and relrowsecurity and relforcerowsecurity),5,'authority tables force RLS');
select ok(not has_table_privilege('authenticated','public.wave1_legal_acceptances','INSERT,UPDATE,DELETE'),'clients cannot manufacture legal acceptance');
select ok(not has_table_privilege('authenticated','public.wave1_creator_eligibility','INSERT,UPDATE,DELETE'),'clients cannot manufacture creator eligibility');
select ok(not has_table_privilege('authenticated','public.wave1_push_installation_ownership','INSERT,UPDATE,DELETE'),'clients cannot manufacture push ownership');
select ok(has_function_privilege('authenticated','public.wave1_session_authority_readback()','EXECUTE'),'authenticated sessions may read authority');
select ok(not has_function_privilege('authenticated','public.wave1_revoke_push_ownership(uuid,uuid,text,text,text,text,text,text)','EXECUTE'),'auth-loss revocation stays service-only');
select ok(has_function_privilege('service_role','public.wave1_revoke_push_ownership(uuid,uuid,text,text,text,text,text,text)','EXECUTE'),'edge service may perform destructive-only revocation');
with cases(expected,input,previous) as (values
 ('INELIGIBLE','{"accountStatus":"ACTIVE","moderationState":"CLEAR","market":"OTHER"}'::jsonb,'INELIGIBLE'),
 ('PENDING_VERIFICATION','{"accountStatus":"ACTIVE","moderationState":"CLEAR","market":"UNITED_STATES"}'::jsonb,'INELIGIBLE'),
 ('VERIFIED','{"accountStatus":"ACTIVE","moderationState":"CLEAR","market":"UNITED_STATES","age18Plus":true,"legalAccepted":true,"creatorRole":true,"rolloutEligible":true,"platformCapability":true,"providerEligible":true,"kycComplete":true,"taxComplete":true,"sanctionsClear":true,"payoutEligible":true}'::jsonb,'INELIGIBLE'),
 ('SUSPENDED','{"accountStatus":"ACTIVE","moderationState":"SUSPENDED"}'::jsonb,'VERIFIED'),
 ('REVOKED','{"accountStatus":"ACTIVE","moderationState":"REVOKED"}'::jsonb,'VERIFIED'))
select is((select count(*)::int from cases where public.wave1_compute_creator_eligibility(input,previous)->>'state'=expected),5,'creator evaluator preserves all five states');
select is(public.wave1_compute_creator_eligibility('{"accountStatus":"ACTIVE","moderationState":"CLEAR","market":"UNITED_STATES"}', 'INELIGIBLE')->>'state','PENDING_VERIFICATION','missing evidence remains pending');
with keys(k) as (select unnest(array['age18Plus','legalAccepted','creatorRole','rolloutEligible','platformCapability','providerEligible','kycComplete','taxComplete','sanctionsClear','payoutEligible'])), base(v) as (values ('{"accountStatus":"ACTIVE","moderationState":"CLEAR","market":"UNITED_STATES","age18Plus":true,"legalAccepted":true,"creatorRole":true,"rolloutEligible":true,"platformCapability":true,"providerEligible":true,"kycComplete":true,"taxComplete":true,"sanctionsClear":true,"payoutEligible":true}'::jsonb))
select is((select count(*)::int from keys,base where public.wave1_compute_creator_eligibility(jsonb_set(v,array[k],'false'), 'INELIGIBLE')->>'state'='INELIGIBLE'),10,'each independent creator gate fails closed');
select ok((public.wave1_compute_creator_eligibility('{"accountStatus":"ACTIVE","moderationState":"CLEAR","market":"UNITED_STATES","age18Plus":true,"legalAccepted":true,"creatorRole":true,"rolloutEligible":true,"platformCapability":true,"providerEligible":true,"kycComplete":true,"taxComplete":true,"sanctionsClear":true,"payoutEligible":true}', 'INELIGIBLE')->>'canCreateMoneyExposure')::boolean,'only complete server evidence permits new exposure');
select ok(not (public.wave1_compute_creator_eligibility('{"moderationState":"SUSPENDED"}', 'VERIFIED')->>'canCreateMoneyExposure')::boolean,'suspension blocks new exposure');
select ok((public.wave1_compute_creator_eligibility('{"moderationState":"REVOKED"}', 'VERIFIED')->>'canProcessHistoricalObligations')::boolean,'revocation preserves historical obligations');
create temporary table rollout_fixture as select id from (select md5(n::text)::uuid id from generate_series(1,1000)n)q where mod(hashtextextended('chillywood-wave1-us-rollout-v1:'||id::text,20260814),100)=0 limit 1;
insert into auth.users(id,is_sso_user,is_anonymous) select id,false,false from rollout_fixture;
select is((select public.wave1_evaluate_creator_eligibility(id,'{"accountStatus":"ACTIVE","moderationState":"CLEAR","market":"UNITED_STATES","age18Plus":true,"legalAccepted":true,"creatorRole":true,"rolloutEligible":false,"platformCapability":true,"providerEligible":true,"kycComplete":true,"taxComplete":true,"sanctionsClear":true,"payoutEligible":true,"inputVersions":{"evaluationSequence":1}}','rollout-boundary','local_pgtap')->>'state' from rollout_fixture),'VERIFIED','the server overrides caller rollout input only for its one-percent bucket');
select is((select public.wave1_evaluate_creator_eligibility(id,'{"accountStatus":"ACTIVE","moderationState":"CLEAR","market":"OTHER","inputVersions":{"evaluationSequence":2}}','newer-denial','local_pgtap')->>'state' from rollout_fixture),'INELIGIBLE','a newer creator denial supersedes verified input');
select is((select public.wave1_evaluate_creator_eligibility(id,'{"accountStatus":"ACTIVE","moderationState":"CLEAR","market":"UNITED_STATES","age18Plus":true,"legalAccepted":true,"creatorRole":true,"platformCapability":true,"providerEligible":true,"kycComplete":true,"taxComplete":true,"sanctionsClear":true,"payoutEligible":true,"inputVersions":{"evaluationSequence":1}}','rollout-boundary','local_pgtap')->>'state' from rollout_fixture),'INELIGIBLE','replayed operation cannot overwrite newer creator authority');
select ok((select (public.wave1_evaluate_creator_eligibility(id,'{"accountStatus":"ACTIVE","moderationState":"CLEAR","market":"UNITED_STATES","inputVersions":{"evaluationSequence":1}}','stale-new-key','local_pgtap')->>'staleInput')::boolean from rollout_fixture),'a new key with a stale input sequence is rejected');
select throws_ok((select format('select public.wave1_evaluate_creator_eligibility(%L,%L,%L,%L)',id,'{"accountStatus":"ACTIVE"}', 'missing-version','local_pgtap') from rollout_fixture),'P0001','creator_input_version_invalid','missing creator provenance cannot verify');
select is((select public.wave1_evaluate_creator_eligibility(id,'{"accountStatus":"ACTIVE","moderationState":"CLEAR","market":"UNITED_STATES","age18Plus":true,"legalAccepted":true,"creatorRole":true,"platformCapability":true,"providerEligible":true,"kycComplete":true,"taxComplete":true,"sanctionsClear":true,"payoutEligible":true,"inputVersions":{"evaluationSequence":3}}','verified-v3','local_pgtap')->>'state' from rollout_fixture),'VERIFIED','a newer complete evaluation can verify again');
insert into auth.sessions(id,user_id) select '11111111-1111-4111-8111-111111111111',id from rollout_fixture;
select set_config('request.jwt.claims',(select jsonb_build_object('sub',id,'session_id','11111111-1111-4111-8111-111111111111')::text from rollout_fixture),true);
select is(public.wave1_legal_requirements_readback('account')->>'sessionGeneration','11111111-1111-4111-8111-111111111111','legal requirements readback binds the live session generation');
select ok((select (public.wave1_accept_legal_documents((select jsonb_object_agg(document_key,version) from public.wave1_legal_document_versions where active and market='UNITED_STATES' and capability='account'),'UNITED_STATES',id,id,'11111111-1111-4111-8111-111111111111','account')->>'allAccepted')::boolean from rollout_fixture),'exact-version legal acceptance returns authoritative current readback');
update public.wave1_legal_acceptances set invalidated_at=now() where user_id in (select id from rollout_fixture) and document_key='terms' and capability='account';
select public.wave1_accept_legal_documents((select jsonb_object_agg(document_key,version) from public.wave1_legal_document_versions where active and market='UNITED_STATES' and capability='account'),'UNITED_STATES',id,id,'11111111-1111-4111-8111-111111111111','account') from rollout_fixture;
select ok((public.wave1_legal_requirements_readback('account')->>'allAccepted')::boolean and (select count(*)=2 and count(*) filter(where invalidated_at is null)=1 from public.wave1_legal_acceptances where user_id in (select id from rollout_fixture) and document_key='terms' and capability='account') and exists(select 1 from public.wave1_authority_audit_events where domain='LEGAL_ACCEPTANCE' and reason='acceptance_invalidated' and subject_hash=(select public.wave1_sha256(id::text) from rollout_fixture)) and (select count(*)=2 from public.wave1_authority_audit_events where domain='LEGAL_ACCEPTANCE' and reason='exact_versions_accepted' and subject_hash=(select public.wave1_sha256(id::text) from rollout_fixture)),'invalidated evidence and a new acceptance receipt are retained while the same current version can be reaccepted');
insert into auth.sessions(id,user_id) select '22222222-2222-4222-8222-222222222222',id from rollout_fixture;
select set_config('request.jwt.claims',(select jsonb_build_object('sub',id,'session_id','22222222-2222-4222-8222-222222222222')::text from rollout_fixture),true);
select is(public.wave1_legal_requirements_readback('account')->>'sessionGeneration','22222222-2222-4222-8222-222222222222','legal readback follows the replacement live session generation');
select ok(not (public.wave1_legal_requirements_readback('account')->>'allAccepted')::boolean,'prior-session legal evidence cannot authorize a replacement session');
select ok((select (public.wave1_accept_legal_documents((select jsonb_object_agg(document_key,version) from public.wave1_legal_document_versions where active and market='UNITED_STATES' and capability='account'),'UNITED_STATES',id,id,'22222222-2222-4222-8222-222222222222','account')->>'allAccepted')::boolean from rollout_fixture),'replacement session must accept exact current legal versions itself');
select is((select count(distinct session_generation)::int from public.wave1_legal_acceptances where user_id in (select id from rollout_fixture) and invalidated_at is null and capability='account'),2,'active legal receipts preserve both exact session generations without laundering either');
delete from auth.sessions where id='22222222-2222-4222-8222-222222222222';
select set_config('request.jwt.claims',(select jsonb_build_object('sub',id,'session_id','11111111-1111-4111-8111-111111111111')::text from rollout_fixture),true);
select is(public.wave1_entitlement_authority_readback('premium')->>'state','INACTIVE','no entitlement row is authoritative inactive');
select is(public.wave1_entitlement_authority_readback('premium')->>'sessionGeneration','11111111-1111-4111-8111-111111111111','entitlement readback binds exact session generation');
insert into public.provider_events (
  id,provider_event_id,provider,product_id,product_key,user_id,app_user_id,
  environment,event_type,status,occurred_at,idempotency_key,raw_payload_hash,metadata
)
select
  '55555555-5555-4555-8555-555555555555','wave1-premium-fixture','revenuecat_app_store',
  mapping.product_id,product.product_key,fixture.id,fixture.id::text,
  'sandbox','INITIAL_PURCHASE','processed',now()-interval '1 hour',
  'INITIAL_PURCHASE:wave1-premium-fixture',repeat('a',64),jsonb_build_object(
    'provider_product_id',mapping.provider_product_id,
    'provider_base_plan_id',mapping.provider_base_plan_id,
    'store_mapping_id',mapping.id,'entitlement_key','premium',
    'original_transaction_id','wave1-premium-original','provider_payload_stored',false
  )
from rollout_fixture fixture
cross join lateral (
  select * from public.monetization_product_store_mappings
  where provider='revenuecat_app_store' and provider_product_id='com.chillywood.premium.monthly'
    and environment='sandbox' limit 1
) mapping
join public.monetization_products product on product.id=mapping.product_id;
insert into public.revenuecat_premium_transaction_authority (
  provider,original_transaction_id,user_id,environment,current_product_id,
  current_provider_product_id,current_provider_base_plan_id,first_event_id,first_event_hash,
  latest_event_id,latest_event_hash,latest_event_type,latest_occurred_at,latest_event_rank,authority_state
)
select
  event.provider,'wave1-premium-original',event.user_id,event.environment,event.product_id,
  event.metadata->>'provider_product_id',event.metadata->>'provider_base_plan_id',
  event.provider_event_id,event.raw_payload_hash,event.provider_event_id,event.raw_payload_hash,
  event.event_type,event.occurred_at,2,'active'
from public.provider_events event where event.provider_event_id='wave1-premium-fixture';
insert into public.user_entitlements(user_id,entitlement_key,status,source,starts_at,expires_at,metadata)
select id::text,'premium','active','revenuecat',now()-interval '1 day',now()+interval '1 day',jsonb_build_object(
  'environment','sandbox','revenuecat_event_id','wave1-premium-fixture','revenuecat_event_hash',repeat('a',64)
) from rollout_fixture;
insert into public.access_grants (
  user_id,grant_type,source_type,product_id,provider,provider_event_id,environment,
  status,starts_at,expires_at,metadata
)
select
  event.user_id,'premium','provider_event',event.product_id,event.provider,event.id,'sandbox',
  'sandbox_only',now()-interval '1 day',now()+interval '1 day',jsonb_build_object(
    'authority_granted',false,'provider_payload_stored',false
  )
from public.provider_events event where event.provider_event_id='wave1-premium-fixture';
select is(public.wave1_entitlement_authority_readback('premium')->>'state','ACTIVE','active entitlement grants');
update public.user_entitlements set status='trialing' where entitlement_key='premium'; select is(public.wave1_entitlement_authority_readback('premium')->>'state','ACTIVE','trialing entitlement grants');
update public.user_entitlements set status='grace_period' where entitlement_key='premium'; select is(public.wave1_entitlement_authority_readback('premium')->>'state','GRACE','grace entitlement grants');
update public.user_entitlements set status='pending' where entitlement_key='premium'; select is(public.wave1_entitlement_authority_readback('premium')->>'state','UNKNOWN','pending entitlement stays unknown');
update public.user_entitlements set status='active',starts_at=now()-interval '2 days',expires_at=now()-interval '1 day' where entitlement_key='premium'; select is(public.wave1_entitlement_authority_readback('premium')->>'state','EXPIRED','expiry overrides active status');
update public.user_entitlements set expires_at=now()+interval '1 day',revoked_at=now() where entitlement_key='premium'; select is(public.wave1_entitlement_authority_readback('premium')->>'state','REVOKED','revocation overrides active status');
update public.user_entitlements set metadata='{"revenuecat_event_type":"REFUND"}' where entitlement_key='premium'; select is(public.wave1_entitlement_authority_readback('premium')->>'state','REFUNDED','refund overrides revocation');
update auth.users set banned_until=now()+interval '1 hour' where id in (select id from rollout_fixture); select throws_ok($$select public.wave1_entitlement_authority_readback('premium')$$,'P0001','account_access_restricted','restricted account cannot read entitlement authority');
select is((select state from public.wave1_creator_eligibility where creator_user_id in (select id from rollout_fixture)),'SUSPENDED','account restriction durably suspends creator authority');
select is((select public.wave1_evaluate_creator_eligibility(id,'{"accountStatus":"ACTIVE","moderationState":"CLEAR","market":"UNITED_STATES","age18Plus":true,"legalAccepted":true,"creatorRole":true,"platformCapability":true,"providerEligible":true,"kycComplete":true,"taxComplete":true,"sanctionsClear":true,"payoutEligible":true,"inputVersions":{"evaluationSequence":4}}','restricted-v4','local_pgtap')->>'state' from rollout_fixture),'SUSPENDED','newer evaluation cannot overwrite a live account restriction');
insert into public.account_deletion_requests(user_id,status,delete_after,restore_deadline) select id,'scheduled',now()+interval '30 days',now()+interval '30 days' from rollout_fixture; update auth.users set banned_until=null where id in (select id from rollout_fixture); select is((select state from public.wave1_creator_eligibility where creator_user_id in (select id from rollout_fixture)),'SUSPENDED','lifting one overlapping restriction cannot restore creator authority');
update public.account_deletion_requests set status='restored',restored_at=now() where user_id in (select id from rollout_fixture) and status='scheduled'; select is((select state from public.wave1_creator_eligibility where creator_user_id in (select id from rollout_fixture)),'PENDING_VERIFICATION','lifting the final restriction requires creator reevaluation'); select is((select public.wave1_evaluate_creator_eligibility(id,'{"accountStatus":"ACTIVE","moderationState":"CLEAR","market":"UNITED_STATES","age18Plus":true,"legalAccepted":true,"creatorRole":true,"platformCapability":true,"providerEligible":true,"kycComplete":true,"taxComplete":true,"sanctionsClear":true,"payoutEligible":true,"inputVersions":{"evaluationSequence":5}}','post-restriction-v5','local_pgtap')->>'state' from rollout_fixture),'VERIFIED','only a newer post-lift evaluation restores creator authority');
select ok((select (public.wave1_accept_legal_documents((select jsonb_object_agg(document_key,version) from public.wave1_legal_document_versions where active and market='UNITED_STATES'),'UNITED_STATES',id,id,'11111111-1111-4111-8111-111111111111','creator_money')->>'allAccepted')::boolean from rollout_fixture),'creator-money acceptance covers the complete active legal set');
insert into public.money_purchase_intents(user_id,product_id,product_key,product_type,provider,provider_product_id,source_type,idempotency_key,expires_at,session_generation) select id,(select id from public.monetization_products limit 1),'pgtap','paid_content_access','revenuecat','pgtap','paid_content','wave1-pgtap-null-creator',now()+interval '1 hour','11111111-1111-4111-8111-111111111111' from rollout_fixture;
update public.wave1_legal_document_versions set active=false where document_key='money_terms' and market='UNITED_STATES' and capability='creator_money';
select throws_ok($$update public.money_purchase_intents set creator_id=(select id from rollout_fixture) where idempotency_key='wave1-pgtap-null-creator'$$,'42501','creator_eligibility_required','a missing required active legal document and mutable creator id both fail closed');
update public.wave1_legal_document_versions set active=true where document_key='money_terms' and market='UNITED_STATES' and capability='creator_money';
update public.money_purchase_intents set creator_id=(select id from rollout_fixture) where idempotency_key='wave1-pgtap-null-creator';
select is((select creator_id from public.money_purchase_intents where idempotency_key='wave1-pgtap-null-creator'),(select id from rollout_fixture),'creator id mutation is allowed only after current creator and legal authority pass');
update public.money_purchase_intents set status='failed' where idempotency_key='wave1-pgtap-null-creator'; select is((select status from public.money_purchase_intents where idempotency_key='wave1-pgtap-null-creator'),'failed','historical status-only intent updates remain allowed');
select ok((select count(*)>=2 from public.wave1_authority_audit_events where domain='CREATOR_ELIGIBILITY' and subject_hash=(select public.wave1_sha256(id::text) from rollout_fixture)),'restriction and lift creator transitions retain audit receipts'); update public.wave1_creator_eligibility set state='SUSPENDED',account_status='ACTIVE',moderation_state='SUSPENDED',reason_codes=array['authority_suspended'] where creator_user_id in (select id from rollout_fixture); update auth.users set banned_until=now()+interval '1 hour' where id in (select id from rollout_fixture); update auth.users set banned_until=null where id in (select id from rollout_fixture); select ok((select state='SUSPENDED' and reason_codes @> array['authority_suspended'] and not reason_codes @> array['account_restricted'] from public.wave1_creator_eligibility where creator_user_id in (select id from rollout_fixture)) and exists(select 1 from public.wave1_authority_audit_events where domain='CREATOR_ELIGIBILITY' and reason='account_restriction_lifted_other_suspension_remains' and to_state='SUSPENDED' and subject_hash=(select public.wave1_sha256(id::text) from rollout_fixture)),'lifting an account ban preserves an independent moderation suspension'); update public.wave1_creator_eligibility set state='VERIFIED',account_status='ACTIVE',moderation_state='CLEAR',reason_codes=array['all_authoritative_inputs_verified'] where creator_user_id in (select id from rollout_fixture);
insert into public.wave1_push_installation_ownership(platform,install_id,user_id,account_id,session_generation,ownership_state,revocation_credential_hash,last_operation_key,last_reason) select 'android','pgtap-delete',id,id,'11111111-1111-4111-8111-111111111111','ACCOUNT_BOUND',repeat('e',64),'register:delete','authenticated_registration' from rollout_fixture;
insert into public.user_push_tokens(user_id,platform,provider,token,token_hash,token_fingerprint,install_id,session_generation,ownership_state) select id,'android','fcm','pgtap-delete-token',repeat('e',64),repeat('e',12),'pgtap-delete','11111111-1111-4111-8111-111111111111','ACCOUNT_BOUND' from rollout_fixture;
insert into public.account_deletion_requests(user_id,status,delete_after,restore_deadline) select id,'scheduled',now()+interval '30 days',now()+interval '30 days' from rollout_fixture; select throws_ok($$select public.wave1_entitlement_authority_readback('premium')$$,'P0001','account_access_restricted','restore-only account cannot read protected entitlement authority');
select is((select ownership_state from public.wave1_push_installation_ownership where install_id='pgtap-delete'),'REVOKED','deletion scheduling revokes ownership without relying on signout');
select ok(not (select enabled from public.user_push_tokens where install_id='pgtap-delete'),'deletion scheduling disables token delivery');
update public.account_deletion_requests set status='completed' where user_id in (select id from rollout_fixture) and status='scheduled'; select ok((select state='SUSPENDED' from public.wave1_creator_eligibility where creator_user_id in (select id from rollout_fixture)) and exists(select 1 from public.wave1_authority_audit_events where domain='CREATOR_ELIGIBILITY' and authority_source='account_deletion_requests' and subject_hash=(select public.wave1_sha256(id::text) from rollout_fixture)) and not exists(select 1 from public.wave1_authority_audit_events where operation_key='account-deletion:'||(select id::text from public.account_deletion_requests where user_id in (select id from rollout_fixture) and status='completed')||':creator-restore'),'completed deletion remains restricted without a false creator-restore receipt');
delete from public.account_deletion_requests where user_id in (select id from rollout_fixture);
insert into public.wave1_push_installation_ownership(platform,install_id,user_id,account_id,session_generation,ownership_state,revocation_credential_hash,last_operation_key,last_reason) select 'android','pgtap-revoke',id,id,'11111111-1111-4111-8111-111111111111','ACCOUNT_BOUND',repeat('a',64),'register:revoke','authenticated_registration' from rollout_fixture;
insert into public.user_push_tokens(user_id,platform,provider,token,token_hash,token_fingerprint,install_id,session_generation,ownership_state) select id,'android','fcm','pgtap-revoke-token',repeat('f',64),repeat('f',12),'pgtap-revoke','11111111-1111-4111-8111-111111111111','ACCOUNT_BOUND' from rollout_fixture;
select ok(not (select (public.wave1_revoke_push_ownership(id,id,'11111111-1111-4111-8111-111111111111','android','pgtap-revoke',repeat('b',64),'revoke:wrong','sign_out')->>'requestAccepted')::boolean from rollout_fixture),'wrong revocation credential is never accepted');
select is((select ownership_state from public.wave1_push_installation_ownership where install_id='pgtap-revoke'),'ACCOUNT_BOUND','wrong credential leaves live ownership unchanged');
select ok((select enabled from public.user_push_tokens where install_id='pgtap-revoke'),'wrong credential leaves retry target enabled');
select is((select public.wave1_revoke_push_ownership(id,id,'11111111-1111-4111-8111-111111111111','android','pgtap-revoke',repeat('a',64),'revoke:correct','sign_out')->>'disposition' from rollout_fixture),'revoked','exact credential produces a confirmed revoke');
select is((select public.wave1_revoke_push_ownership(id,id,'11111111-1111-4111-8111-111111111111','android','pgtap-revoke',repeat('a',64),'revoke:correct','sign_out')->>'disposition' from rollout_fixture),'already_revoked','revoke replay is idempotent');
insert into public.wave1_push_installation_ownership(platform,install_id,user_id,account_id,session_generation,ownership_state,revocation_credential_hash,last_operation_key,last_reason) select 'android','pgtap-old',id,id,'11111111-1111-4111-8111-111111111111','ACCOUNT_BOUND',repeat('c',64),'register:old','authenticated_registration' from rollout_fixture;
insert into public.user_push_tokens(user_id,platform,provider,token,token_hash,token_fingerprint,install_id,session_generation,ownership_state) select id,'android','fcm','pgtap-move-token',public.wave1_sha256('fcm:pgtap-move-token'),left(public.wave1_sha256('fcm:pgtap-move-token'),12),'pgtap-old','11111111-1111-4111-8111-111111111111','ACCOUNT_BOUND' from rollout_fixture;
insert into public.user_push_tokens(user_id,platform,provider,token,token_hash,token_fingerprint,install_id,session_generation,ownership_state) select id,'android','expo','pgtap-old-sibling',public.wave1_sha256('expo:pgtap-old-sibling'),left(public.wave1_sha256('expo:pgtap-old-sibling'),12),'pgtap-old','11111111-1111-4111-8111-111111111111','ACCOUNT_BOUND' from rollout_fixture;
update public.user_push_tokens set enabled=false,ownership_state='REVOKED' where provider='fcm' and token_hash=public.wave1_sha256('fcm:pgtap-move-token');
insert into auth.users(id,is_sso_user,is_anonymous) values ('33333333-3333-4333-8333-333333333333',false,false); insert into public.wave1_push_installation_ownership(platform,install_id,user_id,account_id,session_generation,ownership_state,revocation_credential_hash,last_operation_key,last_reason) values ('android','pgtap-victim','33333333-3333-4333-8333-333333333333','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444','ACCOUNT_BOUND',repeat('a',64),'register:victim','authenticated_registration');
select throws_ok($$select public.wave1_register_push_token(id,id,'11111111-1111-4111-8111-111111111111','android','fcm','pgtap-victim','pgtap-takeover-token',repeat('d',64),'register:takeover','granted',null,null,'{}') from rollout_fixture$$,'P0001','push_registration_credential_mismatch','a different account cannot replace an installation without its capability');
select throws_ok($$select public.wave1_register_push_token(id,id,'11111111-1111-4111-8111-111111111111','android','fcm','pgtap-new','pgtap-move-token',repeat('d',64),'register:new','granted',null,null,'{}') from rollout_fixture$$,'P0001','push_registration_credential_mismatch','provider-token movement requires the prior installation capability');
select ok((select ownership_state='ACCOUNT_BOUND' from public.wave1_push_installation_ownership where install_id='pgtap-old') and (select enabled from public.user_push_tokens where provider='expo' and install_id='pgtap-old'),'a disabled moved token cannot bypass the live owner capability or disable its sibling');
select is((select public.wave1_register_push_token(id,id,'11111111-1111-4111-8111-111111111111','android','fcm','pgtap-new','pgtap-move-token',repeat('c',64),'register:new','granted',null,null,'{}')->>'status' from rollout_fixture),'registered','provider token can bind its new exact installation with prior authority');
select is((select ownership_state from public.wave1_push_installation_ownership where install_id='pgtap-old'),'REVOKED','provider token movement terminates old installation authority');
select is((select install_id from public.user_push_tokens where provider='fcm' and token_hash=public.wave1_sha256('fcm:pgtap-move-token')),'pgtap-new','one token row remains bound to the new installation');
select is((select count(*)::int from public.user_push_tokens where install_id='pgtap-old' and enabled),0,'provider token movement disables every sibling token on the old installation');
select public.wave1_register_push_token(id,id,'11111111-1111-4111-8111-111111111111','android','fcm','pgtap-audit','pgtap-audit-token',repeat('e',64),'register:new','granted',null,null,'{}') from rollout_fixture; select public.wave1_revoke_push_ownership(id,id,'11111111-1111-4111-8111-111111111111','android','pgtap-audit',repeat('e',64),'revoke:correct','sign_out') from rollout_fixture; select public.wave1_register_push_token(id,id,'11111111-1111-4111-8111-111111111111','android','fcm','pgtap-audit','pgtap-audit-token',repeat('e',64),'register:new','granted',null,null,'{}') from rollout_fixture; select public.wave1_register_push_token(id,id,'11111111-1111-4111-8111-111111111111','android','fcm','pgtap-audit','pgtap-audit-token',repeat('e',64),'register:new','granted',null,null,'{}') from rollout_fixture; select ok((select count(*)=3 from public.wave1_authority_audit_events where domain='PUSH_INSTALLATION_OWNERSHIP' and reason='authenticated_registration' and subject_hash=(select public.wave1_sha256(id::text) from rollout_fixture) and object_hash in (public.wave1_sha256('android:pgtap-new'),public.wave1_sha256('android:pgtap-audit'))) and (select count(*)=2 from public.wave1_authority_audit_events where domain='PUSH_INSTALLATION_OWNERSHIP' and reason='sign_out' and subject_hash=(select public.wave1_sha256(id::text) from rollout_fixture) and object_hash in (public.wave1_sha256('android:pgtap-revoke'),public.wave1_sha256('android:pgtap-audit'))),'caller-key reuse across targets and ownership epochs retains one receipt per mutation while a true replay stays idempotent');
insert into public.wave1_push_installation_ownership(platform,install_id,user_id,account_id,session_generation,ownership_state,revocation_credential_hash,last_operation_key,last_reason) select 'android','pgtap-install',id,id,'11111111-1111-4111-8111-111111111111','ACCOUNT_BOUND',repeat('a',64),'register:pgtap','authenticated_registration' from rollout_fixture;
insert into public.user_push_tokens(user_id,platform,provider,token,token_hash,token_fingerprint,install_id,session_generation,ownership_state) select id,'android','fcm','pgtap-token',repeat('b',64),repeat('b',12),'pgtap-install','11111111-1111-4111-8111-111111111111','ACCOUNT_BOUND' from rollout_fixture;
delete from auth.sessions where id='11111111-1111-4111-8111-111111111111';
select is((select ownership_state from public.wave1_push_installation_ownership where install_id='pgtap-install'),'REVOKED','auth session deletion revokes exact installation ownership');
select ok(not (select enabled from public.user_push_tokens where install_id='pgtap-install'),'auth session deletion disables exact-generation token delivery');
select is((select count(*)::int from public.wave1_legal_document_versions where document_key in ('terms','privacy','community_guidelines','creator_terms','money_terms') and market='UNITED_STATES'),5,'five legal documents are independently versioned for the US');
select is((select count(*)::int from pg_trigger where not tgisinternal and tgname in ('wave1_creator_config_eligibility','wave1_purchase_intent_creator_eligibility','wave1_revoke_push_on_session_delete','wave1_revoke_push_on_account_deletion','wave1_recheck_creator_on_auth_restriction')),5,'server triggers enforce creator eligibility and auth-loss push cleanup');
select ok(
  pg_get_functiondef('public.wave1_enforce_creator_money_exposure()'::regprocedure) like '%wave1_creator_money_subject_authorized_internal%'
  and pg_get_functiondef('public.wave1_creator_money_subject_authorized_internal(uuid)'::regprocedure) like '%is_account_access_restricted%'
  and pg_get_functiondef('public.wave1_creator_money_subject_authorized_internal(uuid)'::regprocedure) like '%wave1_user_has_active_legal_requirements_internal%',
  'final creator exposure rechecks current account and exact-session legal authority'
);
select ok((select column_default like '%7 years%' from information_schema.columns where table_schema='public' and table_name='wave1_authority_audit_events' and column_name='retention_expires_at'),'audit retention is bounded');
select ok(pg_get_functiondef('public.wave1_register_push_token(uuid,uuid,text,text,text,text,text,text,text,text,text,text,jsonb)'::regprocedure) like '%revocation_credential_hash%','push registration binds a revocation credential');
select ok(pg_get_functiondef('public.wave1_revoke_push_ownership(uuid,uuid,text,text,text,text,text,text)'::regprocedure) like '%session_generation%','push revocation binds the captured session generation');
select is((select count(*)::int from pg_proc where pronamespace in ('public'::regnamespace,'auth'::regnamespace) and proname in ('wave1_register_push_token','wave1_revoke_push_ownership','wave1_revoke_push_on_session_delete','wave1_revoke_push_on_account_deletion') and pg_get_functiondef(oid) like '%wave1-push-authority%'),4,'all push mutations share one authority lock');
select * from finish();
rollback;
