import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { handleScopedOperatorRequest } from "../_shared/scoped-operator.ts";
import { runIosRecoverySourceProbe } from "../_shared/ios-source-operator-probes.ts";

Deno.serve(handleScopedOperatorRequest({
  systemId: "platform_recovery_operator",
  tokenHeader: "x-platform-recovery-operator-token",
  tokenHashEnv: "PLATFORM_RECOVERY_OPERATOR_TOKEN_SHA256",
  tokenError: "platform_recovery_operator_token_required",
  eventTable: "platform_recovery_operator_events",
  snapshotTable: "backup_health_snapshots",
  reviewTable: "recovery_required_review_flags",
  defaultHealthState: "review",
  allowedActions: [
    "health_snapshot",
    "database_backup_freshness",
    "restore_drill_freshness",
    "critical_table_backup_coverage",
    "migration_drift_detection",
    "supabase_function_deployment_drift",
    "scheduled_timer_health",
    "operator_token_presence_by_name",
    "provider_secret_presence_by_name",
    "r2_backup_export_health",
    "audit_log_integrity",
    "emergency_state_readback",
    "cross_system_recovery_readiness",
    "watch_once",
    "status",
    "report",
  ],
  approvalActions: [
    "production_restore",
    "destructive_db_mutation",
    "secret_rotation",
    "backup_delete",
    "provider_config_change",
    "r2_media_behavior_change",
  ],
  actionTables: {
    database_backup_freshness: "backup_health_snapshots",
    restore_drill_freshness: "restore_drill_findings",
    migration_drift_detection: "migration_drift_findings",
    supabase_function_deployment_drift: "function_deployment_drift_findings",
    scheduled_timer_health: "scheduled_timer_health_findings",
    critical_table_backup_coverage: "recovery_required_review_flags",
    operator_token_presence_by_name: "recovery_required_review_flags",
    provider_secret_presence_by_name: "recovery_required_review_flags",
    r2_backup_export_health: "recovery_required_review_flags",
    audit_log_integrity: "recovery_required_review_flags",
    emergency_state_readback: "recovery_required_review_flags",
    cross_system_recovery_readiness: "recovery_required_review_flags",
  },
  watchOnceHandler: runIosRecoverySourceProbe,
}));
