import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { test } from "node:test";
import ts from "typescript";
const require = createRequire(import.meta.url);
const read = (path) => readFileSync(path, "utf8");
const load = (path) => { const module = { exports: {} }; const js = ts.transpileModule(read(path), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, strict: true } }).outputText; new Function("exports", "module", "require", js)(module.exports, module, require); return module.exports; };
let inert; inert = new Proxy(() => undefined, { get: (_target, key) => key === "then" ? undefined : inert, apply: () => undefined });
const loadStubbed = (path, mocks) => { const module = { exports: {} }; const js = ts.transpileModule(read(path), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, strict: true } }).outputText; new Function("exports", "module", "require", "__DEV__", js)(module.exports, module, (id) => Object.hasOwn(mocks, id) ? mocks[id] : inert, false); return module.exports; };
const links = load("_lib/appLinks.ts");
const ent = load("_lib/entitlementAuthority.ts");
const creator = load("_lib/creatorEligibility.ts");
const sameBinding = (left, right) => !!left && !!right && ["userId", "accountId", "sessionGeneration", "restoreOnly"].every((key) => left[key] === right[key]);
let monetizationAuthority = null;
const monetization = loadStubbed("_lib/monetization.ts", { "./entitlementAuthority": ent, "./accountSessionAuthority": { getCurrentAccountSessionAuthoritySnapshot: () => monetizationAuthority, sameAccountSessionAuthority: sameBinding, subscribeToAccountSessionAuthority: () => () => {} } });
let premiumAuthorityReads = 0; let premiumRpcCalls = 0;
const premiumRuntime = loadStubbed("_lib/premiumEntitlements.ts", { "./entitlementAuthority": ent, "./accountSessionAuthority": { readCurrentAccountSessionAuthority: async () => { premiumAuthorityReads += 1; return binding; }, sameAccountSessionAuthority: sameBinding }, "./supabase": { supabase: { rpc: () => { premiumRpcCalls += 1; return Promise.resolve({ data: null, error: null }); } } } });
const authorityRuntime = loadStubbed("_lib/accountSessionAuthority.ts", { "./supabase": { supabase: inert }, "./entitlementAuthority": { withAuthorityReadDeadline: async (operation) => await operation } });
const task = JSON.parse(read("docs/assurance/tasks/pre-release-identity-entitlement-authority-v1.json"));
const source = Object.fromEntries(Object.entries({ access: "_lib/accessEntitlements.ts", room: "_lib/roomRules.ts", callback: "app/auth-callback.tsx", legal: "_lib/accountLegalAcceptance.ts", session: "_lib/session.tsx", recovery: "app/reset-password.tsx", notifications: "_lib/notifications.ts", notificationEdge: "supabase/functions/notification-device-tokens/index.ts", premium: "_lib/premiumEntitlements.ts", monetization: "_lib/monetization.ts", revenuecat: "_lib/revenuecat.ts", creatorSetup: "_lib/creatorMonetizationSetup.ts", layout: "app/_layout.tsx", migration: "supabase/migrations/202608140001_wave1_identity_entitlement_authority.sql", webhook: "supabase/functions/revenuecat-webhook/index.ts" }).map(([key, path]) => [key, read(path)]));
assert.equal(task.stableDefectLedger.entries.flatMap((entry) => entry.manifestations).length, 31);
assert.deepEqual([task.rootDefects.length, task.stateTransitionModel.machines.length, task.stateTransitionModel.states.length, task.stateTransitionModel.transitions.length, task.invariants.length], [6, 6, 32, 48, 34]);
assert.deepEqual([task.taskLocalEdgeEvidence.dispositions.length, task.taskLocalEdgeEvidence.modelDeltas.length, task.taskLocalGoverningEdgeClosure.findings.length], [23, 8, 0]);
const binding = { userId: "11111111-1111-4111-8111-111111111111", accountId: "11111111-1111-4111-8111-111111111111", sessionGeneration: "22222222-2222-4222-8222-222222222222", state: "ACTIVE", restoreOnly: false };
const entitlementFor = (key, state = "ACTIVE", extra = {}) => ent.normalizeEntitlementAuthorityReadback({ entitlementKey: key, expectedBinding: binding, readback: { ...binding, entitlementKey: key, state, authoritative: true, grantsProtectedAccess: state === "ACTIVE" || state === "GRACE", source: "revenuecat", expiresAt: null, revokedAt: null, authoritativeAt: "2026-08-14T12:00:00Z", ...extra } });
const entitlement = (state = "ACTIVE", extra = {}) => entitlementFor("premium", state, extra);
const creatorReadback = (extra = {}) => creator.parseCreatorEligibilityReadback({ ...binding, authoritative: true, authoritySource: "money_flow_control", state: "VERIFIED", accountStatus: "ACTIVE", age18Plus: true, legalAccepted: true, creatorRole: true, moderationState: "CLEAR", market: "UNITED_STATES", rolloutEligible: true, platformCapability: true, providerEligible: true, kycComplete: true, taxComplete: true, sanctionsClear: true, payoutEligible: true, canCreateMoneyExposure: true, canProcessHistoricalObligations: true, minimumAge: 18, rollout: "CONTROLLED_1_PERCENT_UNITED_STATES", version: 1, evaluatedAt: "2026-08-14T12:00:00Z", ...extra });
const snapshotFor = (userId, targets = {}, activeEntitlementIds = []) => ({ status: "ready", configuration: { mode: "ios-release", apiKey: "test", shouldConfigure: true }, userId, revenueCatAppUserId: userId ?? "", isAnonymousCustomer: false, canMakePayments: true, customerInfoLoaded: true, offeringsLoaded: true, currentOfferingId: null, availableOfferingIds: [], activeEntitlementIds, activeProductIds: [], targets, issues: [], updatedAt: 1 });
const monetizationGateWitness = () => { const active = { status: "entitled", hasEntitlement: true, entitlementAuthoritative: true, entitlementState: "ACTIVE", offeringAvailable: true, packageCount: 1, recommendedPackageId: "pkg" }; const unknown = { status: "available", hasEntitlement: false, entitlementAuthoritative: false, entitlementState: "UNKNOWN", offeringAvailable: true, packageCount: 1, recommendedPackageId: "premium" }; const gate = monetization.buildMonetizationGateResolution(snapshotFor(binding.userId, { premium_watch_party_access: active, premium_subscription: unknown }), { primaryTargetId: "premium_watch_party_access", qualifyingTargetIds: ["premium_watch_party_access", "premium_subscription"] }); return gate.entitlementAuthorityAvailable && gate.entitlementState === "ACTIVE" && gate.purchaseTargetId === undefined && gate.recommendedPackageId === undefined && !gate.canPurchase; };
const monetizationCacheWitness = () => { const replacement = { ...binding, userId: "replacement", accountId: "replacement", sessionGeneration: "replacement-generation" }; const stale = snapshotFor(binding.userId, {}, ["premium"]); monetizationAuthority = binding; monetization.setCachedMonetizationSnapshot(stale, binding); monetizationAuthority = replacement; const direct = monetization.setCachedMonetizationSnapshot(stale, binding); const cached = monetization.getCachedMonetizationSnapshot(); return direct.userId === replacement.userId && cached.userId === replacement.userId && direct.activeEntitlementIds.length === 0 && cached.activeEntitlementIds.length === 0; };
const explicitNullEntitlementWitness = async () => { premiumAuthorityReads = 0; premiumRpcCalls = 0; const [decision] = await premiumRuntime.readCurrentUserEntitlements(["premium"], { authority: null }); return decision.state === "UNKNOWN" && premiumAuthorityReads === 0 && premiumRpcCalls === 0; };
const atomicRecoveryCleanupWitness = async () => { let current = { access_token: "captured", user: { id: binding.userId } }; let tail = Promise.resolve(); let signal; const started = new Promise((resolve) => { signal = resolve; }); const auth = { initializePromise: Promise.resolve(), lockAcquireTimeout: 100, _acquireLock: (_timeout, operation) => { const run = tail.then(operation, operation); tail = run.then(() => undefined, () => undefined); return run; }, _useSession: (operation) => operation({ data: { session: current }, error: null }), _signOut: async () => { signal(); await new Promise((resolve) => setTimeout(resolve, 2)); current = null; return { error: null }; } }; const clearing = authorityRuntime.clearExactLocalAuthSession(auth, binding.userId, "captured"); await started; const replacing = auth._acquireLock(100, async () => { current = { access_token: "replacement", user: { id: "replacement" } }; }); const [cleared] = await Promise.all([clearing, replacing]); return cleared && current?.user.id === "replacement"; };
let revenueCatAuthority = binding; let revenueCatLogins = []; let releaseRevenueCat = () => {};
const revenueCatPurchases = { configure: () => {}, addCustomerInfoUpdateListener: () => {}, setLogHandler: () => {}, getAppUserID: async () => "$RCAnonymousID:test", logIn: (userId) => { revenueCatLogins.push(userId); if (revenueCatLogins.length === 1) return new Promise((_resolve, reject) => { releaseRevenueCat = () => reject(new Error("released")); }); return Promise.reject(new Error("done")); } };
const shortDeadline = async (operation, fallback) => { try { return await Promise.race([Promise.resolve(operation), new Promise((resolve) => setTimeout(() => resolve(fallback), 2))]); } catch { return fallback; } };
const revenueCatRuntime = loadStubbed("_lib/revenuecat.ts", { "react-native": { Platform: { OS: "ios" }, Linking: {} }, "react-native-purchases": { default: revenueCatPurchases, LOG_LEVEL: {}, PRODUCT_CATEGORY: {} }, "expo-application": { applicationId: "com.chillywood.mobile" }, "./accountSessionAuthority": { readCurrentAccountSessionAuthority: async () => revenueCatAuthority, sameAccountSessionAuthority: sameBinding }, "./entitlementAuthority": { withAuthorityReadDeadline: shortDeadline }, "./logger": { debugLog: () => {}, reportRuntimeError: () => {} }, "./runtimeConfig": { getRuntimeConfig: () => ({ revenueCat: { iosPublicSdkKey: "test", appStorePurchasesEnabled: true } }) } });
const revenueCatQueueWitness = async () => { revenueCatLogins = []; revenueCatAuthority = binding; const first = await revenueCatRuntime.syncRevenueCatCustomerIdentity(binding.userId); revenueCatAuthority = { ...binding, userId: "replacement", accountId: "replacement", sessionGeneration: "replacement-generation" }; const second = await revenueCatRuntime.syncRevenueCatCustomerIdentity("replacement"); const held = revenueCatLogins.length === 1; releaseRevenueCat(); await new Promise((resolve) => setTimeout(resolve, 5)); return first.status === "unavailable" && second.status === "unavailable" && held && revenueCatLogins[1] === "replacement"; };
const envelope = () => links.createAuthRedirectEnvelope("/settings?section=notifications", { id: "redirect-1", now: 100, ttlMs: 100 });
const pairs = [
  [() => links.resolveApplicationRoute("/profile/profile-proof") === "/profile/profile-proof", () => links.resolveApplicationRoute("https://evil.example/profile/profile-proof") === null],
  [() => links.resolveApplicationRoute("/terms") === "/terms", () => links.resolveApplicationRoute("/not-registered") === null],
  [() => links.resolveApplicationRoute("/settings?section=notifications") === "/settings?section=notifications", () => links.resolveApplicationRoute("/settings?premium=true") === null],
  [() => links.resolveApplicationRoute("/profile/%252e%252e") === null, () => links.resolveApplicationRoute("//evil.example/settings") === null && links.parseApplicationLink("/auth-callback?code=a&error=denied") === null && !source.callback.includes("mergeAuthCallbackState")],
  [() => links.consumeAuthRedirectEnvelope(envelope(), binding, new Set(), 150).route === "/settings?section=notifications" && source.recovery.includes("CapturedRecoverySession"), () => { const bound = links.validateAuthRedirectEnvelope(envelope(), binding, 150); return links.consumeAuthRedirectEnvelope(bound, { ...binding, sessionGeneration: "stale" }, new Set(), 150).route === null && source.recovery.includes("sameAccountSessionAuthority(captured, recoveryAuthority)"); }],
  [() => source.legal.includes('"wave1_legal_requirements_readback"'), () => !source.legal.includes(".from(USER_ACCOUNT_LEGAL_ACCEPTANCES_TABLE)")],
  [() => ["user_id", "document_version", "market", "role_key", "capability", "accepted_at", "authority_source"].every((field) => source.migration.includes(`"${field}"`)), () => source.migration.includes('acceptance."role_key" = v_role')],
  [() => source.legal.includes('"wave1_accept_legal_documents"'), () => source.migration.includes("revoke insert, update, delete on table public.\"user_account_legal_acceptances\"")],
  [() => source.migration.includes("legal_version_mismatch"), () => source.legal.includes("bundled.version !== requirement.version")],
  [() => ["terms", "privacy", "community_guidelines", "creator_terms", "money_terms"].every((key) => source.migration.includes(`'${key}'`)), () => source.migration.includes("wave1_legal_document_one_active_version")],
  [() => source.migration.includes("retention_expires_at") && source.migration.includes("interval '7 years'"), () => source.migration.includes("wave1_purge_expired_authority_evidence")],
  [() => ["UNKNOWN", "INACTIVE", "ACTIVE", "GRACE"].every((state) => ent.ENTITLEMENT_AUTHORITY_STATES.includes(state)), () => ent.createUnknownEntitlementDecision("premium").state !== ent.createInactiveEntitlementDecision({ entitlementKey: "premium", binding, authoritativeAt: "2026-08-14T12:00:00Z" }).state],
  [async () => await ent.withAuthorityReadDeadline(new Promise(() => {}), "fallback", 1) === "fallback", () => [{ accountId: "replacement" }, { source: "client" }, { grantsProtectedAccess: false }, { authoritativeAt: "malformed" }].every((extra) => entitlement("ACTIVE", extra).state === "UNKNOWN")],
  [() => ent.entitlementGrantsProtectedAccess(entitlement("ACTIVE")) && ent.entitlementGrantsProtectedAccess(entitlement("GRACE")) && ent.resolveAlternativeEntitlementAuthority([entitlementFor("premium_watch_party", "ACTIVE"), ent.createUnknownEntitlementDecision("premium")], 2).state === "ACTIVE" && ent.resolveAlternativeEntitlementAuthority([entitlementFor("premium_watch_party", "GRACE"), ent.createUnknownEntitlementDecision("premium")], 2).state === "GRACE" && ent.resolveAlternativeEntitlementAuthority([entitlementFor("premium_watch_party", "GRACE"), entitlement("ACTIVE")], 2).state === "ACTIVE" && monetizationGateWitness(), () => !ent.entitlementGrantsProtectedAccess(entitlement("INACTIVE")) && !ent.entitlementGrantsProtectedAccess(ent.createUnknownEntitlementDecision("premium")) && ent.resolveAlternativeEntitlementAuthority([entitlement("INACTIVE"), ent.createUnknownEntitlementDecision("paid_content")], 2).state === "UNKNOWN" && ent.resolveAlternativeEntitlementAuthority([entitlement("INACTIVE"), entitlement("REVOKED")], 2).authoritative],
  [() => ent.createUnknownEntitlementDecision("premium", "query_failed").authoritative === false, async () => !source.premium.includes(".upsert(") && source.monetization.includes("Premium status unavailable") && source.monetization.includes("if (options?.userId === null) return createEmptyMonetizationSnapshot") && (await monetization.readMonetizationSnapshot({ userId: null })).userId === null && await explicitNullEntitlementWitness()],
  [() => entitlement("ACTIVE").sessionGeneration === binding.sessionGeneration, () => [{ userId: "replacement" }, { accountId: "replacement" }, { sessionGeneration: "replacement" }, { restoreOnly: true }].every((extra) => entitlement("ACTIVE", extra).state === "UNKNOWN")],
  [() => ent.rejectStaleEntitlementDecision(entitlement("ACTIVE"), binding).state === "ACTIVE" && source.revenuecat.includes("runRevenueCatMutation"), () => ent.rejectStaleEntitlementDecision(entitlement("ACTIVE"), { ...binding, sessionGeneration: "replacement" }).state === "UNKNOWN" && source.revenuecat.includes("requireRevenueCatMutationAuthority({ authority })")],
  [() => source.webhook.includes("duplicateEvent") && source.webhook.includes("staleEvent"), () => source.webhook.includes("entitlementUnchanged")],
  [() => source.access.includes('| "entitlement_unknown"') && source.room.includes('| "entitlement_unknown"'), () => (source.access.match(/\? "user_entitlement"/gu) ?? []).length === 2 && !/(?:as AccessReason|as RoomAccessReason|as unknown as|type (?:AccessReason|RoomAccessReason) = string)/u.test(source.access + source.room)],
  [() => source.monetization.includes('from "./entitlementAuthority"') && source.premium.includes('from "./entitlementAuthority"'), () => source.creatorSetup.includes("wave1_creator_eligibility_readback") && source.revenuecat.includes("sameAccountSessionAuthority")],
  [() => source.migration.includes('primary key ("platform", "install_id")'), () => source.migration.includes('constraint "wave1_push_owner_account_check"')],
  [() => ["sign_out", "account_switch", "auth_invalidation", "account_deletion", "recovery_replacement", "auth_loss"].every((reason) => source.session.includes(`"${reason}"`)), () => source.session.includes("revokePushOwnershipForSession") && source.session.includes("syncRevenueCatCustomerIdentity(null)")],
  [() => source.migration.includes('"ownership_state" = \'ACCOUNT_BOUND\' and "enabled"'), () => source.migration.includes('"session_generation" = v_session->>\'sessionGeneration\'') && source.notificationEdge.includes("requestAccepted: true")],
  [() => source.notifications.includes("serializePushRevocationLedger") && source.notifications.includes("retryPendingPushRevocationsInternal"), () => !source.notifications.includes("entries.slice(-8)") && source.notificationEdge.includes("requestAccepted: false")],
  [() => source.creatorSetup.includes("readMyCreatorEligibilityAuthority"), () => source.migration.includes("revoke all on table") && source.migration.includes("wave1_creator_eligibility")],
  [() => creatorReadback().state === "VERIFIED", () => creatorReadback({ providerEligible: null }).state === "PENDING_VERIFICATION"],
  [() => creatorReadback().inputs.age18Plus === true && creatorReadback().inputs.market === "UNITED_STATES", () => creatorReadback({ market: "OTHER" }).state !== "VERIFIED"],
  [() => creator.canCreateCreatorMoneyExposure(creatorReadback()), () => !creator.canCreateCreatorMoneyExposure(creator.parseCreatorEligibilityReadback({ state: "VERIFIED" }))],
  [() => !creator.canCreateCreatorMoneyExposure(creatorReadback({ state: "SUSPENDED" })), () => !creator.canCreateCreatorMoneyExposure(creatorReadback({ state: "REVOKED" }))],
  [() => creator.canProcessCreatorHistoricalObligation("refund"), () => creator.canProcessCreatorHistoricalObligation("reversal")],
  [async () => source.session.includes("operation !== sequence") && source.session.includes('setAuthorityStatus("recovery_only")') && source.session.includes("publishAccountSessionAuthoritySnapshot(null)") && source.session.includes("AsyncStorage.setItem(PASSWORD_RECOVERY_SESSION_STORAGE_KEY, PENDING_RECOVERY)") && source.session.includes("parseAccountSessionAuthorityReadback({ ...value, authoritative: true }) ?? PENDING_RECOVERY") && source.session.includes("catch { return PENDING_RECOVERY; }") && source.session.includes("getSession().catch(() => null); if (!result) return false") && source.session.includes("if (saved) recoveryQuarantineIntent = false") && source.session.includes("storedRecoveryBinding !== PENDING_RECOVERY") && source.session.includes("clearQuarantinedPasswordRecoverySession") && source.recovery.includes("clearQuarantinedPasswordRecoverySession(true)") && source.recovery.includes("await beginPasswordRecoverySessionQuarantine()") && source.recovery.includes("candidate ?? before.session") && source.recovery.includes("await abandonRecoveryCandidate(session)") && source.recovery.includes("recoveryInputConsumedRef.current = false") && source.recovery.includes("if (cleared) router.replace") && !source.recovery.includes('markRecoveryReady("recovery_session")') && source.recovery.includes('redirectType !== "PASSWORD_RECOVERY"') && source.recovery.includes("recoveryProofRef.current") && authorityRuntime.recoverySessionIsQuarantined("SIGNED_IN", binding, binding) && authorityRuntime.recoverySessionIsQuarantined("TOKEN_REFRESHED", binding, binding) && authorityRuntime.recoverySessionIsQuarantined("INITIAL_SESSION", binding, "PENDING_RECOVERY") && !authorityRuntime.recoverySessionIsQuarantined("INITIAL_SESSION", { ...binding, sessionGeneration: "replacement" }, binding) && source.callback.includes("clearExactLocalAuthSession") && !source.callback.includes("supabase.auth.signOut()") && await atomicRecoveryCleanupWitness(), async () => entitlement("ACTIVE", { sessionGeneration: "old" }).state === "UNKNOWN" && source.revenuecat.includes("withAuthorityReadDeadline(\n    queued") && await revenueCatQueueWitness()],
  [() => source.layout.includes('authorityStatus === "unknown"') && source.layout.includes('state === "active"') && source.layout.includes("acceptedLegalVerificationKey !== legalVerificationKey") && source.monetization.includes("Premium status unavailable"), () => /unavailable and unverified[\s\S]{0,120}Protected access remains locked/iu.test(source.monetization) && source.monetization.includes("Account changed before monetization authority could be committed") && monetizationCacheWitness()],
  [() => source.notifications.includes("queued for retry") && source.migration.includes("evaluationSequence"), () => source.notifications.includes("push_revocation_ledger_invalid") && source.notificationEdge.includes("exactReceipt") && !source.webhook.includes("raw_provider_payload_stored: true")],
  [() => new Set(task.stateTransitionModel.states).size === 32 && new Set(task.stateTransitionModel.transitions.map((entry) => entry.id)).size === 48, () => task.taskLocalGoverningEdgeClosure.accounting.unresolvedSet.length === 0],
];
assert.equal(pairs.length, 34);
task.invariants.forEach((invariant, index) => test(`${invariant.id}: ${invariant.positiveWitness} / ${invariant.negativeWitness}`, async () => { assert.equal(await pairs[index][0](), true); assert.equal(await pairs[index][1](), true); }));
