create table if not exists public.platform_role_memberships (
  id bigint generated by default as identity primary key,
  role text not null,
  user_id text,
  email text,
  status text not null default 'active',
  notes text,
  granted_by text,
  granted_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'platform_role_memberships_role_check'
      and conrelid = 'public.platform_role_memberships'::regclass
  ) then
    alter table public.platform_role_memberships
      add constraint platform_role_memberships_role_check
      check (role in ('operator', 'moderator'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'platform_role_memberships_status_check'
      and conrelid = 'public.platform_role_memberships'::regclass
  ) then
    alter table public.platform_role_memberships
      add constraint platform_role_memberships_status_check
      check (status in ('active', 'revoked'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'platform_role_memberships_identity_check'
      and conrelid = 'public.platform_role_memberships'::regclass
  ) then
    alter table public.platform_role_memberships
      add constraint platform_role_memberships_identity_check
      check (
        nullif(trim(coalesce(user_id, '')), '') is not null
        or nullif(trim(coalesce(email, '')), '') is not null
      );
  end if;
end $$;

create unique index if not exists platform_role_memberships_user_role_idx
  on public.platform_role_memberships (user_id, role)
  where user_id is not null and length(trim(user_id)) > 0;

create unique index if not exists platform_role_memberships_email_role_idx
  on public.platform_role_memberships ((lower(email)), role)
  where email is not null and length(trim(email)) > 0;

create index if not exists platform_role_memberships_role_status_idx
  on public.platform_role_memberships (role, status, granted_at desc);

alter table if exists public.platform_role_memberships enable row level security;

create or replace function public.has_platform_role(required_roles text[])
returns boolean
language sql
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and coalesce(array_length(required_roles, 1), 0) > 0
    and exists (
      select 1
      from public.platform_role_memberships membership
      where membership.status = 'active'
        and membership.role = any(required_roles)
        and (
          membership.user_id = auth.uid()::text
          or (
            nullif(trim(coalesce(auth.jwt() ->> 'email', '')), '') is not null
            and lower(membership.email) = lower(trim(coalesce(auth.jwt() ->> 'email', '')))
          )
        )
    );
$$;

revoke all on function public.has_platform_role(text[]) from public;
grant execute on function public.has_platform_role(text[]) to authenticated;

grant select on public.platform_role_memberships to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'platform_role_memberships'
      and policyname = 'platform_role_memberships_select_own'
  ) then
    create policy platform_role_memberships_select_own
      on public.platform_role_memberships
      for select
      to authenticated
      using (
        auth.uid() is not null
        and (
          user_id = auth.uid()::text
          or (
            nullif(trim(coalesce(auth.jwt() ->> 'email', '')), '') is not null
            and lower(email) = lower(trim(coalesce(auth.jwt() ->> 'email', '')))
          )
        )
      );
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from pg_class
    where relnamespace = 'public'::regnamespace
      and relname = 'safety_reports'
      and relkind = 'r'
  ) then
    grant select, insert on public.safety_reports to authenticated;

    if exists (
      select 1
      from pg_class
      where relnamespace = 'public'::regnamespace
        and relname = 'safety_reports_id_seq'
        and relkind = 'S'
    ) then
      grant usage, select on sequence public.safety_reports_id_seq to authenticated;
    end if;

    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = 'safety_reports'
        and policyname = 'safety_reports_select_review_queue'
    ) then
      create policy safety_reports_select_review_queue
        on public.safety_reports
        for select
        to authenticated
        using (public.has_platform_role(array['operator', 'moderator']));
    end if;
  end if;
end $$;
