export type AutonomousSystemId =
  | "livekit_operator"
  | "media_automation"
  | "money_flow_control"
  | "notification_delivery_operator"
  | "release_ota_operator"
  | "security_owner_operator"
  | "moderation_safety_operator"
  | "observability_runtime_operator"
  | "owner_command_operator";

export type AutonomousCandidateSystemId = never;

export type AutonomousActivationMode =
  | "off"
  | "dry_run"
  | "manual_cli"
  | "bounded_run"
  | "limited_scheduled_if_approved"
  | "limited_scheduled_probe"
  | "limited_scheduled_safe_recovery";

export type AutonomousApprovalLevel = 0 | 1 | 2 | 3 | 4;

export type AutonomousSystemSurface = {
  id: string;
  approvalLevel: AutonomousApprovalLevel;
  allowedReadScope: readonly string[];
  allowedWriteScope: readonly string[];
  forbiddenScope: readonly string[];
  proofScript: string;
  guardScript: string;
  rollbackBehavior: string;
  killSwitchOrFallback: string;
  ownerApprovalRequired: boolean;
};

export type AutonomousSystemContract = {
  id: AutonomousSystemId;
  displayName: string;
  status: string;
  activationModes: readonly AutonomousActivationMode[];
  activeActivationMode: AutonomousActivationMode;
  schedulerStatus: string;
  allowedSurfaces: readonly string[];
  allowedWrites: readonly string[];
  forbidden: readonly string[];
  requiredGates: readonly string[];
  requiredProofScripts: readonly string[];
  requiredGuardScripts: readonly string[];
  surfaces: readonly AutonomousSystemSurface[];
};

export type AutonomousCandidateSystemContract = {
  id: AutonomousCandidateSystemId;
  displayName: string;
  status: "candidate_foundation_only";
  activeActivationMode: "off";
  schedulerStatus: "no_scheduler_no_daemon_no_worker";
  scopeCandidates: readonly string[];
  allowedWrites: readonly [];
  forbidden: readonly string[];
  ownerApprovalRequiredForActivation: true;
  activationRequirements: readonly string[];
};

export const AUTONOMOUS_SYSTEM_EXPANSION_RULES = [
  "system id",
  "action/surface id",
  "activation mode",
  "allowed read scope",
  "allowed write scope",
  "forbidden scope",
  "approval level",
  "proof script",
  "guard script",
  "rollback/quarantine behavior",
  "kill switch/fallback behavior",
  "owner/admin approval requirement for Level 3/4",
] as const;

export const AUTONOMOUS_HIGH_RISK_DOMAINS = [
  "auth/RLS",
  "billing/provider",
  "Premium entitlement",
  "payout/cashout",
  "destructive DB",
  "public/private exposure",
  "app store/public release",
  "provider plan/add-on",
] as const;

export const AUTONOMOUS_SYSTEMS_REGISTRY = [
  {
    id: "media_automation",
    displayName: "Media Autonomous System",
    status: "bounded_source_and_cli_automation_with_object_storage_shutdown_readiness_closed",
    activeActivationMode: "bounded_run",
    schedulerStatus: "no_daemon_no_cron_no_queue_processor_enabled",
    activationModes: ["off", "dry_run", "manual_cli", "bounded_run", "limited_scheduled_if_approved"],
    allowedSurfaces: [
      "media scan",
      "catalog readiness",
      "auto-detect planning",
      "source-aware rendition ladder",
      "transcode worker",
      "media_renditions audit",
      "R2 public/free playback",
      "Premium protected HD rows",
      "object-storage R2 migration/readiness",
      "backup/restore",
    ],
    allowedWrites: [
      "scoped media_transcode_jobs",
      "scoped media_renditions",
      "scan result writes through trusted scanner authority",
      "migration audit/resolution metadata",
      "private backup/export artifacts",
    ],
    forbidden: [
      "private/Premium/original public exposure",
      "unscanned/moderation-blocked processing",
      "broad uncapped backfill",
      "fake audit pass",
      "deleting private source objects without approval",
      "billing/Premium/auth/RLS/payout changes",
    ],
    requiredGates: [
      "backup/restore",
      "scan/moderation",
      "audit before trust",
      "rollback/quarantine",
      "kill switch/emergency stop",
      "fallback",
      "secret scan",
    ],
    requiredProofScripts: [
      "proof:media-automation-controller",
      "proof:media-automation-cli",
      "proof:media-object-storage-zero-hetzner",
    ],
    requiredGuardScripts: [
      "guard:autonomous-operating-model",
      "guard:media-delivery-architecture",
      "guard:media-object-storage-migration",
      "guard:vod-quality-policy",
    ],
    surfaces: [
      {
        id: "safe_media_scan_and_catalog_readiness",
        approvalLevel: 1,
        allowedReadScope: ["candidate media metadata", "scanner readiness metadata"],
        allowedWriteScope: ["trusted scanner result writes", "readiness audit metadata"],
        forbiddenScope: ["private source exposure", "manual Premium grant", "auth/RLS mutation"],
        proofScript: "proof:media-scan-automation",
        guardScript: "guard:media-delivery-architecture",
        rollbackBehavior: "mark affected candidates blocked/quarantined through scanner policy",
        killSwitchOrFallback: "media automation emergency stop and signed-origin fallback",
        ownerApprovalRequired: false,
      },
      {
        id: "bounded_public_transcode_and_rendition_audit",
        approvalLevel: 2,
        allowedReadScope: ["public-safe source metadata", "clean scan/moderation status"],
        allowedWriteScope: ["scoped media_transcode_jobs", "scoped media_renditions"],
        forbiddenScope: ["private/Premium/original public CDN", "broad uncapped backfill"],
        proofScript: "proof:media-automation-cli",
        guardScript: "guard:media-delivery-architecture",
        rollbackBehavior: "scoped rollback plan and quarantine for failed rows",
        killSwitchOrFallback: "media automation pause/emergency-stop and signed-origin fallback",
        ownerApprovalRequired: false,
      },
      {
        id: "object_storage_migration_and_shutdown_readiness",
        approvalLevel: 2,
        allowedReadScope: ["redacted storage metadata", "backend verified object inventory"],
        allowedWriteScope: ["migration audit/resolution metadata", "private R2 backup/export artifacts"],
        forbiddenScope: ["delete Hetzner objects", "touch Hetzner LiveKit", "fake R2 objects"],
        proofScript: "proof:media-object-storage-zero-hetzner",
        guardScript: "guard:media-object-storage-migration",
        rollbackBehavior: "retain Hetzner read fallback until owner shutdown decision",
        killSwitchOrFallback: "migration fallback retention and no-delete gate",
        ownerApprovalRequired: false,
      },
      {
        id: "broad_media_backfill_or_new_scheduler",
        approvalLevel: 3,
        allowedReadScope: ["explicitly approved catalog scope"],
        allowedWriteScope: ["owner-approved bounded writes only"],
        forbiddenScope: ["uncapped production backfill", "new daemon without approval"],
        proofScript: "proof:autonomous-systems-contract",
        guardScript: "guard:autonomous-systems-contract",
        rollbackBehavior: "owner-approved rollback/quarantine plan required before execution",
        killSwitchOrFallback: "owner-approved emergency stop required before execution",
        ownerApprovalRequired: true,
      },
    ],
  },
  {
    id: "livekit_operator",
    displayName: "LiveKit Autonomous Operator",
    status: "limited_scheduled_safe_recovery_active_systemd_timer",
    activeActivationMode: "limited_scheduled_safe_recovery",
    schedulerStatus: "chillywood-livekit-operator-watch-once.timer_every_5_minutes",
    activationModes: ["manual_cli", "limited_scheduled_probe", "limited_scheduled_safe_recovery"],
    allowedSurfaces: [
      "live_stage",
      "watch_party_live",
      "party_room_live_sidecar",
      "chat_call",
      "livekit_token",
      "livekit_router",
      "heartbeat_monitor",
      "host_agent",
      "render_telemetry",
    ],
    allowedWrites: [
      "livekit_operator_events",
      "livekit_surface_health_snapshots",
      "livekit_operator_recovery_actions",
      "livekit_operator_learning_state",
      "legitimate heartbeat monitor invocation",
      "scoped safe recovery audit",
    ],
    forbidden: [
      "fake heartbeat",
      "stale cutoff loosening",
      "broad DB mutation",
      "marking unhealthy server active without host proof",
      "secret rotation",
      "TURN credential changes",
      "provider/server replacement",
      "Premium bypass",
      "R2/media writes",
      "auto-source OTA without policy gate",
    ],
    requiredGates: [
      "narrow token",
      "constant-time token validation",
      "RLS/client-write deny",
      "audit every action",
      "safe recovery only",
      "learning cannot override Level 3/4 owner approval",
      "scheduler status must match actual installed systemd/GitHub/Cloudflare state",
    ],
    requiredProofScripts: [
      "proof:livekit-autonomous-operator",
      "proof:livekit-surface-health",
      "proof:livekit-render-telemetry",
      "proof:livekit-operator-recovery-loop",
    ],
    requiredGuardScripts: [
      "guard:livekit-autonomous-operator-policy",
      "guard:livekit-heartbeat-monitor-policy",
      "guard:watch-party-livekit-camera",
    ],
    surfaces: [
      {
        id: "backend_router_and_token_health",
        approvalLevel: 2,
        allowedReadScope: ["livekit server health", "token issuer audit summaries"],
        allowedWriteScope: ["livekit operator health/audit/learning tables"],
        forbiddenScope: ["stale cutoff loosening", "fake heartbeat", "non-LiveKit table mutation"],
        proofScript: "proof:livekit-surface-health",
        guardScript: "guard:livekit-autonomous-operator-policy",
        rollbackBehavior: "audit-only report or scoped recovery action rollback",
        killSwitchOrFallback: "pause affected LiveKit surface reporting without changing Premium gates",
        ownerApprovalRequired: false,
      },
      {
        id: "render_telemetry_regression_detection",
        approvalLevel: 1,
        allowedReadScope: ["sanitized client render/token telemetry"],
        allowedWriteScope: ["livekit_operator_events", "livekit_surface_health_snapshots"],
        forbiddenScope: ["participant tokens", "room tokens", "secrets", "direct recovery from client event"],
        proofScript: "proof:livekit-render-telemetry",
        guardScript: "guard:livekit-autonomous-operator-policy",
        rollbackBehavior: "operator incident report and source patch recommendation only",
        killSwitchOrFallback: "stable in-surface LiveKit shell and fallback roster suppression guard",
        ownerApprovalRequired: false,
      },
      {
        id: "safe_heartbeat_or_counter_recovery",
        approvalLevel: 2,
        allowedReadScope: ["heartbeat age", "capacity counters", "host proof summaries"],
        allowedWriteScope: ["legitimate heartbeat monitor invocation", "scoped recovery audit rows"],
        forbiddenScope: ["manual heartbeat timestamp writes", "mark server active without host proof"],
        proofScript: "proof:livekit-operator-recovery-loop",
        guardScript: "guard:livekit-heartbeat-monitor-policy",
        rollbackBehavior: "record recovery failed and leave router fail-closed",
        killSwitchOrFallback: "operator safe recovery disable flag",
        ownerApprovalRequired: false,
      },
      {
        id: "secret_rotation_turn_or_server_replacement",
        approvalLevel: 4,
        allowedReadScope: ["redacted incident summary", "host proof summary"],
        allowedWriteScope: ["owner-approved external provider action only"],
        forbiddenScope: ["automatic secret rotation", "automatic provider/server replacement"],
        proofScript: "proof:autonomous-systems-contract",
        guardScript: "guard:autonomous-systems-contract",
        rollbackBehavior: "owner-approved rollback and external provider confirmation required",
        killSwitchOrFallback: "owner-approved emergency plan required",
        ownerApprovalRequired: true,
      },
    ],
  },
  {
    id: "money_flow_control",
    displayName: "Money Flow & Ledger Control Plane",
    status: "scoped_write_capable_guarded",
    activeActivationMode: "limited_scheduled_probe",
    schedulerStatus: "chillywood-money-operator-watch-once.timer_every_10_minutes",
    activationModes: ["off", "dry_run", "manual_cli", "limited_scheduled_probe", "limited_scheduled_if_approved"],
    allowedSurfaces: [
      "premium_revenue",
      "revenuecat_entitlements_readback",
      "google_play_receipts_readback",
      "revenuecat_webhook_delivery",
      "google_play_webhook_delivery",
      "stripe_connect_webhook_delivery",
      "stripe_merch_webhook_delivery",
      "provider_readiness_audit",
      "provider_delivery_error_rate",
      "stale_provider_dashboard_integration_detection",
      "duplicate_webhook_integration_detection",
      "provider_access_broker",
      "provider_dashboard_readback",
      "provider_test_delivery_status",
      "stripe_connect_foundation",
      "creator_payout_ledger",
      "payout_review_queue",
      "payout_batches",
      "provider_transfer_records",
      "network_billing",
      "sponsor_deals",
      "fraud_holds",
      "usage_metering",
      "refunds_disputes_future",
      "tax_compliance_future",
    ],
    allowedWrites: [
      "money_operator_events",
      "money_reconciliation_runs",
      "money_reconciliation_findings",
      "money_provider_sync_status",
      "money_duplicate_event_detections",
      "money_required_review_flags",
      "money_flow_health_snapshots",
      "money_operator_learning_state",
      "record reconciliation findings",
      "mark provider sync stale/synced/failed",
      "mark duplicate provider/webhook event",
      "mark ledger/payout/revenue item requires_review",
      "record blocked action",
      "record external confirmation requirement",
      "write sandbox/test-mode proof result",
      "update learning state",
      "provider webhook delivery health/status/finding/report records",
      "provider delivery-history readback metadata",
      "provider error-rate classification",
      "stale/duplicate provider dashboard integration detection",
      "provider access capability/status rows",
      "provider access audit events",
      "provider dashboard repair request rows",
      "autonomous approval request creation",
    ],
    forbidden: [
      "fake MRR/ARR",
      "fake creator earnings",
      "fake payable balance",
      "fake paid status",
      "fake transfer complete",
      "manual Premium grant",
      "Premium entitlement edit outside provider proof",
      "real money movement without Level 4",
      "payout release without provider confirmation",
      "charging customers from foundation tables",
      "marking test-mode data as production",
      "provider secrets in logs/docs/artifacts",
    ],
    requiredGates: [
      "owner/super-admin approval for Level 3",
      "owner/super-admin approval plus external provider confirmation for Level 4",
      "fresh preflight before execution",
      "exact scope match",
      "emergency stop blocks non-read-only money mutations",
      "provider readback before money movement closure",
      "provider webhook reliability loop cannot mutate dashboards without approval",
      "provider access broker cannot print secrets or mutate dashboards without approval",
      "100% provider webhook error rate records failed/blocked status and reconciliation finding",
      "test-mode provider proof cannot satisfy production readiness",
      "money operator narrow token",
      "money operator client write denial",
      "scoped write tables only",
      "no manual Premium grants",
      "no fake revenue/earnings/payable balances",
      "secret scan",
    ],
    requiredProofScripts: [
      "proof:money-flow-control",
      "proof:money-operator-write-scope",
      "proof:money-external-confirmation",
      "proof:provider-webhook-reliability",
      "proof:money-provider-reliability-loop",
      "proof:provider-access-broker",
      "proof:provider-dashboard-access-policy",
      "proof:autonomous-approval-live-flow",
      "proof:autonomous-systems-contract",
    ],
    requiredGuardScripts: [
      "guard:money-flow-control",
      "guard:provider-webhook-reliability",
      "guard:provider-access-broker",
      "guard:autonomous-systems-contract",
      "guard:autonomous-operating-model",
    ],
    surfaces: [
      {
        id: "read_only_money_reconciliation",
        approvalLevel: 1,
        allowedReadScope: ["money ledger summary rows", "provider readiness labels", "redacted reconciliation metadata"],
        allowedWriteScope: ["money_reconciliation_runs", "money_flow_health_snapshots", "approval request creation"],
        forbiddenScope: ["provider charge", "payout release", "manual Premium grant", "fake ledger closure"],
        proofScript: "proof:money-flow-control",
        guardScript: "guard:money-flow-control",
        rollbackBehavior: "delete no data; correct report copy or mark report superseded",
        killSwitchOrFallback: "money_flow_control emergency stop keeps read-only reporting available",
        ownerApprovalRequired: false,
      },
      {
        id: "sandbox_test_mode_provider_proof",
        approvalLevel: 2,
        allowedReadScope: ["sandbox/test-mode provider status", "zero-dollar proof metadata", "duplicate event checks"],
        allowedWriteScope: ["money_operator_events", "money_provider_sync_status", "money_duplicate_event_detections", "zero-dollar/sandbox proof rows"],
        forbiddenScope: ["production money movement", "user-visible paid action unless explicitly sandbox", "test-mode data marked production"],
        proofScript: "proof:money-operator-write-scope",
        guardScript: "guard:money-flow-control",
        rollbackBehavior: "mark sandbox proof row superseded or failed; no production mutation exists",
        killSwitchOrFallback: "money_flow_control emergency stop blocks non-read-only mutations",
        ownerApprovalRequired: false,
      },
      {
        id: "scoped_money_operator_reconciliation_writes",
        approvalLevel: 2,
        allowedReadScope: ["redacted ledger/provider/reconciliation metadata", "provider sync health labels", "duplicate event hashes"],
        allowedWriteScope: [
          "money_operator_events",
          "money_reconciliation_runs",
          "money_reconciliation_findings",
          "money_provider_sync_status",
          "money_duplicate_event_detections",
          "money_required_review_flags",
          "money_flow_health_snapshots",
          "money_operator_learning_state",
        ],
        forbiddenScope: ["mark payout paid", "release payout", "charge customer", "manual Premium grant", "fake revenue", "fake payable balance"],
        proofScript: "proof:money-operator-write-scope",
        guardScript: "guard:money-flow-control",
        rollbackBehavior: "mark operator finding/review/event superseded; never mark paid or settled",
        killSwitchOrFallback: "money_flow_control emergency stop blocks non-read-only/review writes",
        ownerApprovalRequired: false,
      },
      {
        id: "provider_webhook_reliability_loop",
        approvalLevel: 2,
        allowedReadScope: [
          "provider webhook delivery status",
          "redacted provider dashboard delivery history",
          "endpoint host/path without secret values",
          "event type and integration id hash",
        ],
        allowedWriteScope: [
          "money_operator_events",
          "money_provider_sync_status",
          "money_reconciliation_findings",
          "money_duplicate_event_detections",
          "money_required_review_flags",
          "autonomous approval request creation for dashboard mutation",
        ],
        forbiddenScope: [
          "provider dashboard mutation without owner approval",
          "manual Premium grant",
          "money movement",
          "test-mode proof claimed production",
          "provider secret logging",
        ],
        proofScript: "proof:money-provider-reliability-loop",
        guardScript: "guard:provider-webhook-reliability",
        rollbackBehavior: "mark provider reliability finding superseded or reviewed; never delete provider dashboard integrations autonomously",
        killSwitchOrFallback: "money_flow_control emergency stop blocks non-read-only money mutations; provider reliability reporting remains read-only/status-only",
        ownerApprovalRequired: false,
      },
      {
        id: "provider_access_broker",
        approvalLevel: 2,
        allowedReadScope: [
          "provider API read-only webhook metadata",
          "provider delivery health/status when APIs expose it",
          "dashboard owner-session TEST outcome metadata",
          "missing credential names only",
        ],
        allowedWriteScope: [
          "provider_access_capabilities",
          "provider_access_audit_events",
          "provider_dashboard_repair_requests",
          "money_operator_events",
          "money_provider_sync_status",
          "autonomous approval request creation for dashboard mutation",
        ],
        forbiddenScope: [
          "provider secret output",
          "provider dashboard mutation without approval",
          "provider product changes",
          "Stripe live-mode switch",
          "charge, payout, transfer, invoice, checkout session, payment link, cashout",
          "manual Premium grant",
        ],
        proofScript: "proof:provider-access-broker",
        guardScript: "guard:provider-access-broker",
        rollbackBehavior: "mark provider access capability/readback/repair request superseded; never mutate provider dashboards autonomously",
        killSwitchOrFallback: "money_flow_control emergency stop blocks non-read-only money mutations; provider access readback remains status-only",
        ownerApprovalRequired: false,
      },
      {
        id: "production_money_setup_or_policy_mutation",
        approvalLevel: 3,
        allowedReadScope: ["explicitly scoped production readiness evidence"],
        allowedWriteScope: ["owner-approved setup/policy mutation only"],
        forbiddenScope: ["real customer charge", "real payout", "manual Premium grant", "provider secrets"],
        proofScript: "proof:money-flow-control",
        guardScript: "guard:money-flow-control",
        rollbackBehavior: "owner-approved rollback plan required before execution",
        killSwitchOrFallback: "money_flow_control emergency stop required before execution",
        ownerApprovalRequired: true,
      },
      {
        id: "real_money_movement_or_public_money_launch",
        approvalLevel: 4,
        allowedReadScope: ["explicitly scoped provider confirmation/readback"],
        allowedWriteScope: ["owner-approved provider-confirmed external money action only"],
        forbiddenScope: ["execution without external provider confirmation", "fake paid status", "fake transfer complete", "cashout without confirmation"],
        proofScript: "proof:money-flow-control",
        guardScript: "guard:money-flow-control",
        rollbackBehavior: "owner-approved rollback and external provider reversal/confirmation plan required",
        killSwitchOrFallback: "money_flow_control emergency stop and provider halt plan required",
        ownerApprovalRequired: true,
      },
    ],
  },
  {
    id: "notification_delivery_operator",
    displayName: "Notification Delivery Operator",
    status: "scoped_write_capable_guarded",
    activeActivationMode: "limited_scheduled_safe_recovery",
    schedulerStatus: "chillywood-notification-operator-watch-once.timer_every_5_minutes",
    activationModes: ["off", "manual_cli", "limited_scheduled_probe", "limited_scheduled_safe_recovery"],
    allowedSurfaces: [
      "expo_push_delivery",
      "device_token_health",
      "notification_preferences_readback",
      "notification_delivery_attempts",
      "notification_retry_queue",
      "money_notification_delivery",
      "livekit_live_room_notifications",
      "chat_call_push_notifications",
      "creator_notification_delivery",
    ],
    allowedWrites: [
      "notification_operator_events",
      "notification_delivery_health_snapshots",
      "notification_delivery_attempts",
      "notification_provider_sync_status",
      "notification_required_review_flags",
      "notification_duplicate_dedupe_records",
      "user_push_tokens disabled/revoked only after provider says DeviceNotRegistered",
      "autonomous approval requests",
      "notification_operator_learning_state",
    ],
    forbidden: [
      "marketing blast sends",
      "bypass notification preferences",
      "owner/admin alert leakage to normal users",
      "money/payment claims without provider proof",
      "changing push provider credentials",
      "sending notifications as fake system events",
      "broad user messaging without approval",
    ],
    requiredGates: [
      "preference respect",
      "token redaction",
      "retry caps",
      "dedupe",
      "audit",
      "emergency stop",
      "owner approval for broad campaigns/provider config",
    ],
    requiredProofScripts: ["proof:notification-delivery-operator", "proof:autonomous-systems-contract"],
    requiredGuardScripts: ["guard:notification-delivery-operator", "guard:autonomous-systems-contract"],
    surfaces: [
      {
        id: "delivery_health_and_attempt_audit",
        approvalLevel: 2,
        allowedReadScope: ["redacted Expo/provider delivery status", "notification preference readback", "delivery attempt metadata"],
        allowedWriteScope: ["notification_operator_events", "notification_delivery_health_snapshots", "notification_delivery_attempts", "notification_provider_sync_status"],
        forbiddenScope: ["notification preference bypass", "push credential output", "fake system event sends"],
        proofScript: "proof:notification-delivery-operator",
        guardScript: "guard:notification-delivery-operator",
        rollbackBehavior: "mark notification operator event/attempt superseded; never delete provider evidence",
        killSwitchOrFallback: "notification_delivery_operator emergency stop blocks safe writes and retry records",
        ownerApprovalRequired: false,
      },
      {
        id: "device_token_cleanup_with_provider_evidence",
        approvalLevel: 2,
        allowedReadScope: ["provider DeviceNotRegistered evidence", "redacted device token hash"],
        allowedWriteScope: ["notification_required_review_flags", "user_push_tokens disabled/revoked only after provider says DeviceNotRegistered"],
        forbiddenScope: ["token deletion without provider evidence", "raw token output", "push provider credential mutation"],
        proofScript: "proof:notification-delivery-operator",
        guardScript: "guard:notification-delivery-operator",
        rollbackBehavior: "review flag can be superseded; token disable requires provider evidence audit",
        killSwitchOrFallback: "notification_delivery_operator emergency stop blocks token cleanup writes",
        ownerApprovalRequired: false,
      },
      {
        id: "broad_notification_campaign_or_provider_config",
        approvalLevel: 3,
        allowedReadScope: ["explicitly scoped audience and provider config summary"],
        allowedWriteScope: ["owner-approved notification campaign/config change only"],
        forbiddenScope: ["marketing blast without approval", "preference bypass", "owner/admin alert leakage"],
        proofScript: "proof:notification-delivery-operator",
        guardScript: "guard:notification-delivery-operator",
        rollbackBehavior: "owner-approved campaign stop/rollback plan required",
        killSwitchOrFallback: "notification_delivery_operator emergency stop and provider send halt required",
        ownerApprovalRequired: true,
      },
    ],
  },
  {
    id: "release_ota_operator",
    displayName: "Release / OTA Operator",
    status: "scoped_write_capable_guarded",
    activeActivationMode: "limited_scheduled_probe",
    schedulerStatus: "chillywood-release-operator-watch-once.timer_every_30_minutes",
    activationModes: ["off", "manual_cli", "limited_scheduled_probe"],
    allowedSurfaces: [
      "release_diagnostics",
      "eas_update_health",
      "runtime_channel_updateid_readback",
      "embedded_launch_detection",
      "emergency_launch_detection",
      "ota_rollout_health",
      "install_proof_status",
      "release_rollback_readiness",
    ],
    allowedWrites: [
      "release_operator_events",
      "release_health_snapshots",
      "ota_diagnostics_readback_records",
      "rollout_anomaly_findings",
      "release_required_review_flags",
      "release_approval_requests",
      "rollback_readiness_records",
      "release_operator_learning_state",
    ],
    forbidden: [
      "auto-publish production OTA without approval",
      "auto-rollback production OTA without approval",
      "submit Play/App Store release",
      "change runtimeVersion policy",
      "change public release track",
      "change store listing",
      "hide emergency launch",
      "fake installed proof",
    ],
    requiredGates: [
      "release diagnostics proof",
      "runtime/channel match",
      "installed updateId proof",
      "emergency/embedded launch audit",
      "owner approval for publish/rollback/public release",
      "route/runtime validation",
    ],
    requiredProofScripts: ["proof:release-ota-operator", "proof:autonomous-systems-contract"],
    requiredGuardScripts: ["guard:release-ota-operator", "guard:autonomous-systems-contract"],
    surfaces: [
      {
        id: "release_diagnostics_and_rollout_health",
        approvalLevel: 1,
        allowedReadScope: ["release diagnostics", "runtime/channel/updateId readback", "embedded/emergency launch state"],
        allowedWriteScope: ["release_operator_events", "release_health_snapshots", "ota_diagnostics_readback_records", "rollout_anomaly_findings"],
        forbiddenScope: ["fake installed proof", "hide emergency launch", "publish OTA"],
        proofScript: "proof:release-ota-operator",
        guardScript: "guard:release-ota-operator",
        rollbackBehavior: "mark release finding superseded; no release state changed",
        killSwitchOrFallback: "release_ota_operator emergency stop blocks safe writes while read/report remains available",
        ownerApprovalRequired: false,
      },
      {
        id: "rollback_readiness_without_execution",
        approvalLevel: 2,
        allowedReadScope: ["redacted rollout anomaly evidence", "release proof status"],
        allowedWriteScope: ["rollback_readiness_records", "release_required_review_flags"],
        forbiddenScope: ["execute rollback", "publish production OTA", "change runtimeVersion policy"],
        proofScript: "proof:release-ota-operator",
        guardScript: "guard:release-ota-operator",
        rollbackBehavior: "mark readiness record superseded; owner-approved rollback remains separate",
        killSwitchOrFallback: "release_ota_operator emergency stop blocks readiness writes",
        ownerApprovalRequired: false,
      },
      {
        id: "production_publish_or_rollback",
        approvalLevel: 4,
        allowedReadScope: ["explicit release proof and owner-approved rollout scope"],
        allowedWriteScope: ["owner-approved EAS publish/rollback only"],
        forbiddenScope: ["automatic OTA publish", "automatic production rollback", "store release mutation"],
        proofScript: "proof:release-ota-operator",
        guardScript: "guard:release-ota-operator",
        rollbackBehavior: "owner-approved release rollback plan and installed proof required",
        killSwitchOrFallback: "release emergency stop and owner-approved rollout halt required",
        ownerApprovalRequired: true,
      },
    ],
  },
  {
    id: "security_owner_operator",
    displayName: "Security / Owner Authority Operator",
    status: "scoped_write_capable_guarded",
    activeActivationMode: "limited_scheduled_probe",
    schedulerStatus: "chillywood-security-owner-operator-watch-once.timer_every_15_minutes",
    activationModes: ["off", "manual_cli", "limited_scheduled_probe", "limited_scheduled_safe_recovery"],
    allowedSurfaces: [
      "owner_super_admin_role_integrity",
      "platform_role_memberships_readback",
      "rachi_operator_self_approval_prevention",
      "autonomous_approval_integrity",
      "admin_route_exposure",
      "secret_scan_health",
      "rls_policy_health_readonly",
      "security_incident_flags",
      "emergency_pause_requests",
    ],
    allowedWrites: [
      "security_operator_events",
      "security_health_snapshots",
      "security_required_review_flags",
      "owner_authority_integrity_findings",
      "approval_integrity_findings",
      "secret_scan_findings",
      "autonomous approval requests",
      "emergency pause request records",
      "security_operator_learning_state",
    ],
    forbidden: [
      "assign/revoke owner role autonomously",
      "mutate auth/RLS autonomously",
      "rotate secrets without approval",
      "ban/suspend users directly",
      "expose owner controls to non-owner",
      "let Rachi/operator approve themselves",
      "delete audit rows",
      "broad system shutdown without approval except existing approved emergency-stop path",
    ],
    requiredGates: [
      "owner/super_admin verification",
      "immutable audit",
      "no client privileged writes",
      "no secret output",
      "owner approval for auth/RLS/role mutation",
      "emergency stop audit",
    ],
    requiredProofScripts: ["proof:security-owner-operator", "proof:autonomous-approval-live-flow", "proof:autonomous-systems-contract"],
    requiredGuardScripts: ["guard:security-owner-operator", "guard:autonomous-systems-contract"],
    surfaces: [
      {
        id: "owner_and_approval_integrity_findings",
        approvalLevel: 1,
        allowedReadScope: ["platform_role_memberships readback", "autonomous approval audit summaries", "admin route exposure summary"],
        allowedWriteScope: ["owner_authority_integrity_findings", "approval_integrity_findings", "security_health_snapshots", "security_required_review_flags"],
        forbiddenScope: ["owner role mutation", "approve request", "RLS mutation", "audit deletion"],
        proofScript: "proof:security-owner-operator",
        guardScript: "guard:security-owner-operator",
        rollbackBehavior: "mark security finding superseded after owner/admin review; never delete audit rows",
        killSwitchOrFallback: "security_owner_operator emergency stop blocks safe writes; read/report remains available",
        ownerApprovalRequired: false,
      },
      {
        id: "secret_scan_and_security_incident_flags",
        approvalLevel: 1,
        allowedReadScope: ["redacted secret-scan status", "security incident metadata"],
        allowedWriteScope: ["secret_scan_findings", "security_required_review_flags", "security_operator_events"],
        forbiddenScope: ["secret output", "secret rotation", "provider credential mutation"],
        proofScript: "proof:security-owner-operator",
        guardScript: "guard:security-owner-operator",
        rollbackBehavior: "mark redacted finding reviewed/superseded",
        killSwitchOrFallback: "security_owner_operator emergency stop blocks incident write automation",
        ownerApprovalRequired: false,
      },
      {
        id: "owner_role_auth_rls_or_secret_rotation",
        approvalLevel: 4,
        allowedReadScope: ["explicit owner/security preflight summary"],
        allowedWriteScope: ["owner-approved server-side security mutation only"],
        forbiddenScope: ["autonomous owner role mutation", "RLS weakening", "Rachi/operator self-approval", "secret rotation without approval"],
        proofScript: "proof:security-owner-operator",
        guardScript: "guard:security-owner-operator",
        rollbackBehavior: "owner-approved rollback and security verification required",
        killSwitchOrFallback: "security emergency stop and owner approval required before execution",
        ownerApprovalRequired: true,
      },
    ],
  },
  {
    id: "moderation_safety_operator",
    displayName: "Moderation / Safety Operator",
    status: "scoped_write_capable_guarded",
    activeActivationMode: "limited_scheduled_probe",
    schedulerStatus: "chillywood-moderation-safety-operator-watch-once.timer_every_10_minutes",
    activationModes: ["off", "manual_cli", "limited_scheduled_probe", "limited_scheduled_safe_recovery"],
    allowedSurfaces: [
      "moderation_queue_health",
      "user_report_backlog",
      "stale_case_detection",
      "duplicate_report_detection",
      "content_safety_review_flags",
      "fraud_hold_recommendations",
      "creator_upload_review_flags",
      "live_room_safety_review_flags",
    ],
    allowedWrites: [
      "moderation_operator_events",
      "moderation_health_snapshots",
      "moderation_required_review_flags",
      "moderation_duplicate_report_detections",
      "moderation_case_priority_flags",
      "moderation_stale_case_findings",
      "safety_review_recommendations",
      "autonomous approval requests",
      "moderation_operator_learning_state",
    ],
    forbidden: [
      "permanent ban/suspend/restrict without approval",
      "delete content without approval",
      "disable uploads/live/account without approval",
      "enforce fraud holds without approval",
      "change user rights automatically",
      "public/private exposure changes",
      "moderation action without audit",
      "hidden enforcement with no appeal/review trail",
    ],
    requiredGates: [
      "audit every recommendation/action",
      "appeal/review path for enforcement",
      "owner/staff approval for account rights changes",
      "emergency stop",
      "no fake enforcement state",
      "no secret/PII leakage beyond approved admin surfaces",
    ],
    requiredProofScripts: ["proof:moderation-safety-operator", "proof:autonomous-systems-contract"],
    requiredGuardScripts: ["guard:moderation-safety-operator", "guard:autonomous-systems-contract"],
    surfaces: [
      {
        id: "moderation_queue_health_and_review_flags",
        approvalLevel: 2,
        allowedReadScope: ["moderation queue summaries", "report backlog metadata", "stale case metadata"],
        allowedWriteScope: ["moderation_operator_events", "moderation_health_snapshots", "moderation_required_review_flags", "moderation_stale_case_findings"],
        forbiddenScope: ["ban/suspend/restrict", "content delete", "hidden enforcement", "user rights change"],
        proofScript: "proof:moderation-safety-operator",
        guardScript: "guard:moderation-safety-operator",
        rollbackBehavior: "mark review/finding rows superseded; enforcement remains separately reviewed",
        killSwitchOrFallback: "moderation_safety_operator emergency stop blocks safe writes; read/report remains available",
        ownerApprovalRequired: false,
      },
      {
        id: "duplicate_report_detection_and_safety_recommendations",
        approvalLevel: 2,
        allowedReadScope: ["duplicate report metadata", "content safety review summary", "fraud hold recommendation evidence"],
        allowedWriteScope: ["moderation_duplicate_report_detections", "moderation_case_priority_flags", "safety_review_recommendations"],
        forbiddenScope: ["delete reports", "enforce fraud holds", "disable uploads/live/account"],
        proofScript: "proof:moderation-safety-operator",
        guardScript: "guard:moderation-safety-operator",
        rollbackBehavior: "mark recommendation superseded; no user rights changed",
        killSwitchOrFallback: "moderation_safety_operator emergency stop blocks recommendation writes",
        ownerApprovalRequired: false,
      },
      {
        id: "account_rights_content_delete_or_enforcement",
        approvalLevel: 3,
        allowedReadScope: ["explicit case evidence and staff/owner review scope"],
        allowedWriteScope: ["owner/staff-approved enforcement only"],
        forbiddenScope: ["hidden enforcement", "no appeal/review trail", "public/private exposure change without approval"],
        proofScript: "proof:moderation-safety-operator",
        guardScript: "guard:moderation-safety-operator",
        rollbackBehavior: "owner/staff-approved appeal and reversal plan required",
        killSwitchOrFallback: "moderation emergency stop and staff/owner review required",
        ownerApprovalRequired: true,
      },
    ],
  },
  {
    id: "observability_runtime_operator",
    displayName: "Observability / Runtime Health Operator",
    status: "scoped_write_capable_guarded",
    activeActivationMode: "limited_scheduled_probe",
    schedulerStatus: "chillywood-observability-operator-watch-once.timer_every_10_minutes",
    activationModes: ["off", "manual_cli", "limited_scheduled_probe", "limited_scheduled_safe_recovery"],
    allowedSurfaces: [
      "crashlytics_crash_health",
      "native_crash_clusters",
      "js_error_clusters",
      "anr_runtime_findings",
      "app_startup_performance",
      "screen_render_performance",
      "network_error_rate",
      "edge_function_error_rate",
      "backend_error_rate_findings",
      "analytics_delivery_health",
      "firebase_performance_health",
      "release_diagnostics_health",
      "ota_updateid_runtime_channel_mismatch",
      "embedded_launch_detection",
      "emergency_launch_detection",
      "cross_system_incident_correlation",
    ],
    allowedWrites: [
      "observability_operator_events",
      "runtime_health_snapshots",
      "crash_cluster_findings",
      "js_error_findings",
      "performance_regression_findings",
      "analytics_delivery_findings",
      "release_health_findings",
      "backend_error_rate_findings",
      "observability_required_review_flags",
      "observability_operator_learning_state",
      "autonomous approval requests",
    ],
    forbidden: [
      "delete crash evidence",
      "silence crash reporting",
      "collect extra PII without approval",
      "log secrets/tokens",
      "publish OTA",
      "rollback OTA",
      "change Remote Config/feature flags without approval",
      "hide emergency launch",
      "fake installed proof",
      "mutate auth/RLS",
      "move money",
      "grant Premium",
      "change provider config",
      "change LiveKit routing",
      "change R2/media behavior",
    ],
    requiredGates: [
      "secret redaction",
      "PII minimization",
      "no raw tokens",
      "no crash evidence deletion",
      "audit every action",
      "emergency stop",
      "approval request for OTA rollback/publish/feature flag changes",
      "approval request for any provider/analytics config mutation",
      "release diagnostics proof for update-related findings",
    ],
    requiredProofScripts: ["proof:observability-runtime-operator", "proof:monitoring-analytics-crash-runtime-diagnostics", "proof:autonomous-systems-contract"],
    requiredGuardScripts: ["guard:observability-runtime-operator", "guard:monitoring-analytics-crash-policy", "guard:autonomous-systems-contract"],
    surfaces: [
      {
        id: "crash_and_error_cluster_detection",
        approvalLevel: 2,
        allowedReadScope: ["redacted crash/error summaries", "stack signature hashes", "app version/updateId/runtime/channel"],
        allowedWriteScope: ["crash_cluster_findings", "js_error_findings", "observability_required_review_flags", "observability_operator_events"],
        forbiddenScope: ["raw secrets", "auth/session tokens", "user PII beyond allowed hashes", "deleting crash evidence"],
        proofScript: "proof:observability-runtime-operator",
        guardScript: "guard:observability-runtime-operator",
        rollbackBehavior: "mark observability finding superseded after review; never delete crash evidence",
        killSwitchOrFallback: "observability_runtime_operator emergency stop blocks safe writes; read/report remains available",
        ownerApprovalRequired: false,
      },
      {
        id: "performance_regression_detection",
        approvalLevel: 2,
        allowedReadScope: ["app startup timings", "screen render latency", "Firebase Performance summaries", "network timing summaries"],
        allowedWriteScope: ["performance_regression_findings", "runtime_health_snapshots", "observability_operator_events"],
        forbiddenScope: ["hidden user tracking", "provider config mutation"],
        proofScript: "proof:observability-runtime-operator",
        guardScript: "guard:observability-runtime-operator",
        rollbackBehavior: "mark performance finding superseded after review; no provider config changed",
        killSwitchOrFallback: "observability_runtime_operator emergency stop blocks safe writes; read/report remains available",
        ownerApprovalRequired: false,
      },
      {
        id: "release_runtime_diagnostics_monitor",
        approvalLevel: 2,
        allowedReadScope: ["release diagnostics", "updateId/runtime/channel", "embedded/emergency launch state"],
        allowedWriteScope: ["release_health_findings", "observability_required_review_flags", "autonomous approval requests"],
        forbiddenScope: ["publish OTA", "rollback OTA", "fake installed proof"],
        proofScript: "proof:observability-runtime-operator",
        guardScript: "guard:observability-runtime-operator",
        rollbackBehavior: "mark release-health finding superseded; publish/rollback remains separate owner-approved action",
        killSwitchOrFallback: "observability_runtime_operator emergency stop blocks safe writes; release publish/rollback remains blocked",
        ownerApprovalRequired: false,
      },
      {
        id: "analytics_delivery_health",
        approvalLevel: 1,
        allowedReadScope: ["analytics delivery summaries", "provider status labels"],
        allowedWriteScope: ["analytics_delivery_findings", "runtime_health_snapshots"],
        forbiddenScope: ["provider key output", "analytics schema mutation"],
        proofScript: "proof:observability-runtime-operator",
        guardScript: "guard:observability-runtime-operator",
        rollbackBehavior: "mark analytics-delivery finding superseded; no provider schema changed",
        killSwitchOrFallback: "observability_runtime_operator emergency stop blocks safe writes; read/report remains available",
        ownerApprovalRequired: false,
      },
      {
        id: "observability_config_or_feature_flag_mutation",
        approvalLevel: 3,
        allowedReadScope: ["explicitly scoped incident evidence"],
        allowedWriteScope: ["owner-approved config mutation only"],
        forbiddenScope: ["silent Remote Config mutation", "provider secret mutation"],
        proofScript: "proof:observability-runtime-operator",
        guardScript: "guard:observability-runtime-operator",
        rollbackBehavior: "owner-approved config rollback and proof plan required",
        killSwitchOrFallback: "observability emergency stop and owner approval required before config execution",
        ownerApprovalRequired: true,
      },
      {
        id: "production_release_rollback_or_publish",
        approvalLevel: 4,
        allowedReadScope: ["release health evidence", "installed proof evidence"],
        allowedWriteScope: ["owner-approved release action only"],
        forbiddenScope: ["automatic public release/rollback without owner approval"],
        proofScript: "proof:observability-runtime-operator",
        guardScript: "guard:observability-runtime-operator",
        rollbackBehavior: "owner-approved release rollback/publish rollback plan and installed proof required",
        killSwitchOrFallback: "observability release emergency stop and owner approval required before release execution",
        ownerApprovalRequired: true,
      },
    ],
  },
  {
    id: "owner_command_operator",
    displayName: "Owner Command / Judgment Execution Operator",
    status: "scoped_command_router_guarded",
    activeActivationMode: "manual_cli",
    schedulerStatus: "no_scheduler_no_daemon_no_worker_manual_or_owner_invoked_only",
    activationModes: ["off", "manual_cli"],
    allowedSurfaces: [
      "owner_command_classification",
      "owner_command_routing",
      "owner_command_preflight",
      "owner_command_dry_run",
      "owner_command_safe_execution",
      "owner_command_approval_request_creation",
      "owner_command_blocker_reporting",
      "owner_command_proof_reporting",
    ],
    allowedWrites: [
      "owner_command_requests",
      "owner_command_events",
      "owner_command_execution_steps",
      "owner_command_blockers",
      "autonomous approval request creation",
      "target operator safe report/audit invocation only",
    ],
    forbidden: [
      "direct target-table mutation outside routed operator",
      "Level 3/4 execution without approval",
      "Level 4 execution without external confirmation",
      "bypassing target autonomous operator",
      "bypassing emergency stop",
      "bypassing fresh preflight",
      "broad DB mutation",
      "money movement",
      "manual Premium grant",
      "release publish/rollback",
      "auth/RLS mutation",
      "user ban/restriction/content delete",
      "provider mutation",
      "R2/private exposure",
      "secrets in command payloads/logs",
    ],
    requiredGates: [
      "owner/super_admin command authority",
      "registry scope match",
      "target operator routing",
      "fresh preflight",
      "exact scope match",
      "emergency state check",
      "audit every step",
      "Level 3/4 approval request",
      "Level 4 external confirmation where applicable",
      "secret redaction",
    ],
    requiredProofScripts: [
      "proof:owner-command-operator",
      "proof:owner-command-routing",
      "proof:owner-command-approval-gates",
    ],
    requiredGuardScripts: ["guard:owner-command-operator", "guard:autonomous-systems-contract"],
    surfaces: [
      {
        id: "safe_owner_report_or_status_command",
        approvalLevel: 1,
        allowedReadScope: ["owner-authorized command text", "target operator status/report surfaces", "redacted proof rows"],
        allowedWriteScope: ["owner_command_events", "owner_command_execution_steps", "safe target operator report rows"],
        forbiddenScope: ["target-domain mutation", "secret output", "approval bypass"],
        proofScript: "proof:owner-command-operator",
        guardScript: "guard:owner-command-operator",
        rollbackBehavior: "mark command superseded or blocked; no target-domain rollback required for report-only work",
        killSwitchOrFallback: "owner_command_operator emergency stop blocks command writes; target systems remain separately governed",
        ownerApprovalRequired: false,
      },
      {
        id: "safe_scoped_owner_command_execution",
        approvalLevel: 2,
        allowedReadScope: ["owner-authorized command text", "target system registry scope", "fresh preflight report"],
        allowedWriteScope: ["owner_command audit/blocker/proof rows", "safe routed operator action only"],
        forbiddenScope: ["direct DB mutation outside target operator", "scope expansion", "high-risk target execution"],
        proofScript: "proof:owner-command-routing",
        guardScript: "guard:owner-command-operator",
        rollbackBehavior: "stop remaining steps and use target operator rollback/quarantine plan for any scoped action",
        killSwitchOrFallback: "owner_command_operator and target operator emergency states must be active before execution",
        ownerApprovalRequired: false,
      },
      {
        id: "high_risk_owner_command_request",
        approvalLevel: 3,
        allowedReadScope: ["explicit command text", "target operator scope", "risk/preflight evidence"],
        allowedWriteScope: ["approval request only", "owner_command blocker/proof rows"],
        forbiddenScope: ["execution before owner approval", "bypassing target autonomous operator", "auth/RLS/user-rights/provider mutation"],
        proofScript: "proof:owner-command-approval-gates",
        guardScript: "guard:owner-command-operator",
        rollbackBehavior: "approval denial/cancel/supersede leaves target systems unchanged",
        killSwitchOrFallback: "approval request only; target execution requires active emergency state and fresh preflight",
        ownerApprovalRequired: true,
      },
      {
        id: "real_world_or_external_impact_owner_command",
        approvalLevel: 4,
        allowedReadScope: ["explicit command text", "target operator proof", "external confirmation evidence"],
        allowedWriteScope: ["approval request only until external confirmation", "owner_command blocker/proof rows"],
        forbiddenScope: ["money movement without external confirmation", "public release without confirmation", "private exposure", "provider mutation without confirmation"],
        proofScript: "proof:owner-command-approval-gates",
        guardScript: "guard:owner-command-operator",
        rollbackBehavior: "owner-approved rollback plan and external confirmation required before execution",
        killSwitchOrFallback: "approval request only; Level 4 execution stays blocked until owner approval plus external confirmation",
        ownerApprovalRequired: true,
      },
    ],
  },
] as const satisfies readonly AutonomousSystemContract[];

export const AUTONOMOUS_CANDIDATE_SYSTEMS_REGISTRY = [] as const satisfies readonly AutonomousCandidateSystemContract[];

export const AUTONOMOUS_SYSTEM_IDS = AUTONOMOUS_SYSTEMS_REGISTRY.map((system) => system.id);
export const AUTONOMOUS_CANDIDATE_SYSTEM_IDS: readonly AutonomousCandidateSystemId[] = [];

export const findAutonomousSystemContract = (id: AutonomousSystemId) => (
  AUTONOMOUS_SYSTEMS_REGISTRY.find((system) => system.id === id) ?? null
);

export const listAutonomousApprovalRequiredSurfaces = () => (
  AUTONOMOUS_SYSTEMS_REGISTRY.flatMap((system) => (
    system.surfaces
      .filter((surface) => surface.approvalLevel >= 3 || surface.ownerApprovalRequired)
      .map((surface) => ({
        systemId: system.id,
        surfaceId: surface.id,
        approvalLevel: surface.approvalLevel,
        proofScript: surface.proofScript,
        guardScript: surface.guardScript,
      }))
  ))
);
