const { createRunOncePlugin, withPodfile } = require("@expo/config-plugins");

const PLUGIN_NAME = "with-livekit-ios-static-framework-compatibility";
const START_MARKER = `# @generated by ${PLUGIN_NAME} - start`;
const END_MARKER = `# @generated by ${PLUGIN_NAME} - end`;
const PODFILE_POST_INSTALL_END = "  end\nend\n";
const NON_MODULAR_HEADER_WARNING_FLAG = "-Wno-non-modular-include-in-framework-module";

const LIVEKIT_COMPATIBILITY_BLOCK = `${START_MARKER}
    # LiveKit WebRTC is a framework module when use_frameworks! is static, while
    # its React dependencies expose headers that are intentionally non-modular.
    # Module precompilation happens from both the WebRTC target and its LiveKit
    # consumer, so scope the compatibility setting to those two pods only.
    installer.pods_project.targets.each do |target|
      next unless [
        'livekit-react-native-webrtc',
        'livekit_react_native_webrtc',
        'livekit-react-native',
        'livekit_react_native'
      ].include?(target.name)

      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        build_configuration.build_settings['OTHER_CFLAGS'] = '$(inherited) ${NON_MODULAR_HEADER_WARNING_FLAG}'
      end
    end
    ${END_MARKER}
`;

function addLiveKitCompatibilityBlock(contents) {
  let nextContents = contents;
  const existingStartIndex = nextContents.indexOf(START_MARKER);
  if (existingStartIndex !== -1) {
    const existingEndIndex = nextContents.indexOf(END_MARKER, existingStartIndex);
    if (existingEndIndex === -1) {
      throw new Error(`${PLUGIN_NAME}: generated block is missing its end marker.`);
    }
    const afterExistingEnd = existingEndIndex + END_MARKER.length;
    const afterTrailingNewline = nextContents[afterExistingEnd] === "\n"
      ? afterExistingEnd + 1
      : afterExistingEnd;
    nextContents = `${nextContents.slice(0, existingStartIndex)}${nextContents.slice(afterTrailingNewline)}`;
  }

  const postInstallIndex = nextContents.indexOf("  post_install do |installer|");
  if (postInstallIndex === -1) {
    throw new Error(`${PLUGIN_NAME}: Expo Podfile is missing its post_install hook.`);
  }

  const postInstallEndIndex = nextContents.indexOf(PODFILE_POST_INSTALL_END, postInstallIndex);
  if (postInstallEndIndex === -1) {
    throw new Error(`${PLUGIN_NAME}: unable to locate the end of Expo's post_install hook.`);
  }

  return `${nextContents.slice(0, postInstallEndIndex)}${LIVEKIT_COMPATIBILITY_BLOCK}${nextContents.slice(postInstallEndIndex)}`;
}

function withLiveKitIosStaticFrameworkCompatibility(config) {
  return withPodfile(config, (nextConfig) => {
    nextConfig.modResults.contents = addLiveKitCompatibilityBlock(nextConfig.modResults.contents);
    return nextConfig;
  });
}

module.exports = createRunOncePlugin(
  withLiveKitIosStaticFrameworkCompatibility,
  PLUGIN_NAME,
  "1.0.0",
);
