const { createRunOncePlugin, withPodfile } = require("@expo/config-plugins");

const PLUGIN_NAME = "with-livekit-ios-static-framework-compatibility";
const START_MARKER = `# @generated by ${PLUGIN_NAME} - start`;
const END_MARKER = `# @generated by ${PLUGIN_NAME} - end`;
const PODFILE_POST_INSTALL_END = "  end\nend\n";

const LIVEKIT_COMPATIBILITY_BLOCK = `${START_MARKER}
    # LiveKit WebRTC is a framework module when use_frameworks! is static, while
    # its React dependencies expose headers that are intentionally non-modular.
    # Scope the compatibility setting to this pod instead of weakening the app.
    installer.pods_project.targets.each do |target|
      next unless ['livekit-react-native-webrtc', 'livekit_react_native_webrtc'].include?(target.name)

      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
    ${END_MARKER}
`;

function addLiveKitCompatibilityBlock(contents) {
  if (contents.includes(START_MARKER)) return contents;

  const postInstallIndex = contents.indexOf("  post_install do |installer|");
  if (postInstallIndex === -1) {
    throw new Error(`${PLUGIN_NAME}: Expo Podfile is missing its post_install hook.`);
  }

  const postInstallEndIndex = contents.indexOf(PODFILE_POST_INSTALL_END, postInstallIndex);
  if (postInstallEndIndex === -1) {
    throw new Error(`${PLUGIN_NAME}: unable to locate the end of Expo's post_install hook.`);
  }

  return `${contents.slice(0, postInstallEndIndex)}${LIVEKIT_COMPATIBILITY_BLOCK}${contents.slice(postInstallEndIndex)}`;
}

function withLiveKitIosStaticFrameworkCompatibility(config) {
  return withPodfile(config, (nextConfig) => {
    nextConfig.modResults.contents = addLiveKitCompatibilityBlock(nextConfig.modResults.contents);
    return nextConfig;
  });
}

module.exports = createRunOncePlugin(
  withLiveKitIosStaticFrameworkCompatibility,
  PLUGIN_NAME,
  "1.0.0",
);
