create table public."channel_audience_blocks" (
    "channel_user_id" text not null,
    "blocked_user_id" text not null,
    "blocked_by_user_id" text not null,
    "reason" text,
    "blocked_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public."channel_audience_requests" (
    "id" bigint generated by default as identity not null,
    "channel_user_id" text not null,
    "requester_user_id" text not null,
    "request_kind" text default 'follow'::text not null,
    "status" text default 'pending'::text not null,
    "note" text,
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    "reviewed_at" timestamp with time zone,
    "reviewed_by" text,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public."channel_followers" (
    "channel_user_id" text not null,
    "follower_user_id" text not null,
    "followed_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public."channel_subscribers" (
    "channel_user_id" text not null,
    "subscriber_user_id" text not null,
    "status" text default 'active'::text not null,
    "source" text default 'manual'::text not null,
    "started_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    "expires_at" timestamp with time zone,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table only public."channel_audience_blocks"
    add constraint "channel_audience_blocks_pkey" PRIMARY KEY (channel_user_id, blocked_user_id);
alter table only public."channel_audience_blocks"
    add constraint "channel_audience_blocks_self_block_check" CHECK (channel_user_id <> blocked_user_id);

alter table only public."channel_audience_requests"
    add constraint "channel_audience_requests_pkey" PRIMARY KEY (id);
alter table only public."channel_audience_requests"
    add constraint "channel_audience_requests_kind_check" CHECK (request_kind = ANY (ARRAY['follow'::text, 'subscriber_access'::text]));
alter table only public."channel_audience_requests"
    add constraint "channel_audience_requests_self_request_check" CHECK (channel_user_id <> requester_user_id);
alter table only public."channel_audience_requests"
    add constraint "channel_audience_requests_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'declined'::text, 'canceled'::text]));

alter table only public."channel_followers"
    add constraint "channel_followers_pkey" PRIMARY KEY (channel_user_id, follower_user_id);
alter table only public."channel_followers"
    add constraint "channel_followers_self_follow_check" CHECK (channel_user_id <> follower_user_id);

alter table only public."channel_subscribers"
    add constraint "channel_subscribers_pkey" PRIMARY KEY (channel_user_id, subscriber_user_id);
alter table only public."channel_subscribers"
    add constraint "channel_subscribers_self_subscribe_check" CHECK (channel_user_id <> subscriber_user_id);
alter table only public."channel_subscribers"
    add constraint "channel_subscribers_source_check" CHECK (source = ANY (ARRAY['manual'::text, 'billing_sync'::text, 'operator_grant'::text]));
alter table only public."channel_subscribers"
    add constraint "channel_subscribers_status_check" CHECK (status = ANY (ARRAY['active'::text, 'grace_period'::text, 'canceled'::text, 'expired'::text, 'revoked'::text]));

create index "channel_audience_blocks_blocked_user_idx"
    ON public."channel_audience_blocks" USING btree (blocked_user_id, blocked_at DESC);
create index "channel_audience_blocks_channel_idx"
    ON public."channel_audience_blocks" USING btree (channel_user_id, blocked_at DESC);
create index "channel_audience_requests_channel_status_idx"
    ON public."channel_audience_requests" USING btree (channel_user_id, status, created_at DESC);
create unique index "channel_audience_requests_pending_unique"
    ON public."channel_audience_requests" USING btree (channel_user_id, requester_user_id, request_kind)
    WHERE (status = 'pending'::text);
create index "channel_audience_requests_requester_status_idx"
    ON public."channel_audience_requests" USING btree (requester_user_id, status, created_at DESC);
create index "channel_followers_channel_idx"
    ON public."channel_followers" USING btree (channel_user_id, followed_at DESC);
create index "channel_followers_follower_idx"
    ON public."channel_followers" USING btree (follower_user_id, followed_at DESC);
create index "channel_subscribers_channel_status_idx"
    ON public."channel_subscribers" USING btree (channel_user_id, status, updated_at DESC);
create index "channel_subscribers_subscriber_status_idx"
    ON public."channel_subscribers" USING btree (subscriber_user_id, status, updated_at DESC);

alter table public."channel_audience_blocks" enable row level security;
alter table public."channel_audience_requests" enable row level security;
alter table public."channel_followers" enable row level security;
alter table public."channel_subscribers" enable row level security;

create policy "channel_audience_blocks_delete_owner_or_operator"
    on public."channel_audience_blocks"
    for delete
    to "authenticated"
    using (
        (auth.uid() IS NOT NULL)
        AND (
            channel_user_id = (auth.uid())::text
            OR has_platform_role(ARRAY['operator'::text])
        )
    );

create policy "channel_audience_blocks_insert_owner_or_operator"
    on public."channel_audience_blocks"
    for insert
    to "authenticated"
    with check (
        (auth.uid() IS NOT NULL)
        AND (
            (
                channel_user_id = (auth.uid())::text
                AND blocked_by_user_id = (auth.uid())::text
            )
            OR has_platform_role(ARRAY['operator'::text])
        )
    );

create policy "channel_audience_blocks_select_self_owner_or_operator"
    on public."channel_audience_blocks"
    for select
    to "authenticated"
    using (
        (auth.uid() IS NOT NULL)
        AND (
            channel_user_id = (auth.uid())::text
            OR blocked_user_id = (auth.uid())::text
            OR has_platform_role(ARRAY['operator'::text])
        )
    );

create policy "channel_audience_requests_delete_requester_owner_or_operator"
    on public."channel_audience_requests"
    for delete
    to "authenticated"
    using (
        (auth.uid() IS NOT NULL)
        AND (
            requester_user_id = (auth.uid())::text
            OR channel_user_id = (auth.uid())::text
            OR has_platform_role(ARRAY['operator'::text])
        )
    );

create policy "channel_audience_requests_insert_requester"
    on public."channel_audience_requests"
    for insert
    to "authenticated"
    with check (
        (auth.uid() IS NOT NULL)
        AND requester_user_id = (auth.uid())::text
        AND channel_user_id <> (auth.uid())::text
        AND status = 'pending'::text
        AND reviewed_at IS NULL
        AND reviewed_by IS NULL
    );

create policy "channel_audience_requests_select_requester_owner_or_operator"
    on public."channel_audience_requests"
    for select
    to "authenticated"
    using (
        (auth.uid() IS NOT NULL)
        AND (
            requester_user_id = (auth.uid())::text
            OR channel_user_id = (auth.uid())::text
            OR has_platform_role(ARRAY['operator'::text])
        )
    );

create policy "channel_audience_requests_update_owner_or_operator"
    on public."channel_audience_requests"
    for update
    to "authenticated"
    using (
        (auth.uid() IS NOT NULL)
        AND (
            channel_user_id = (auth.uid())::text
            OR has_platform_role(ARRAY['operator'::text])
        )
    )
    with check (
        (auth.uid() IS NOT NULL)
        AND (
            channel_user_id = (auth.uid())::text
            OR has_platform_role(ARRAY['operator'::text])
        )
    );

create policy "channel_followers_delete_self_owner_or_operator"
    on public."channel_followers"
    for delete
    to "authenticated"
    using (
        (auth.uid() IS NOT NULL)
        AND (
            follower_user_id = (auth.uid())::text
            OR channel_user_id = (auth.uid())::text
            OR has_platform_role(ARRAY['operator'::text])
        )
    );

create policy "channel_followers_insert_own"
    on public."channel_followers"
    for insert
    to "authenticated"
    with check (
        (auth.uid() IS NOT NULL)
        AND follower_user_id = (auth.uid())::text
        AND channel_user_id <> (auth.uid())::text
    );

create policy "channel_followers_select_self_owner_or_operator"
    on public."channel_followers"
    for select
    to "authenticated"
    using (
        (auth.uid() IS NOT NULL)
        AND (
            follower_user_id = (auth.uid())::text
            OR channel_user_id = (auth.uid())::text
            OR has_platform_role(ARRAY['operator'::text])
        )
    );

create policy "channel_subscribers_delete_operator"
    on public."channel_subscribers"
    for delete
    to "authenticated"
    using ((auth.uid() IS NOT NULL) AND has_platform_role(ARRAY['operator'::text]));

create policy "channel_subscribers_insert_operator"
    on public."channel_subscribers"
    for insert
    to "authenticated"
    with check ((auth.uid() IS NOT NULL) AND has_platform_role(ARRAY['operator'::text]));

create policy "channel_subscribers_select_self_owner_or_operator"
    on public."channel_subscribers"
    for select
    to "authenticated"
    using (
        (auth.uid() IS NOT NULL)
        AND (
            subscriber_user_id = (auth.uid())::text
            OR channel_user_id = (auth.uid())::text
            OR has_platform_role(ARRAY['operator'::text])
        )
    );

create policy "channel_subscribers_update_operator"
    on public."channel_subscribers"
    for update
    to "authenticated"
    using ((auth.uid() IS NOT NULL) AND has_platform_role(ARRAY['operator'::text]))
    with check ((auth.uid() IS NOT NULL) AND has_platform_role(ARRAY['operator'::text]));

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_audience_blocks" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_audience_blocks" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_audience_blocks" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_audience_blocks" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_audience_requests" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_audience_requests" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_audience_requests" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_audience_requests" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_followers" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_followers" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_followers" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_followers" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_subscribers" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_subscribers" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_subscribers" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
    on table public."channel_subscribers" to "service_role";

grant USAGE, SELECT
    on sequence public."channel_audience_requests_id_seq" to "anon";
grant USAGE, SELECT
    on sequence public."channel_audience_requests_id_seq" to "authenticated";
grant USAGE, SELECT
    on sequence public."channel_audience_requests_id_seq" to "postgres";
grant USAGE, SELECT
    on sequence public."channel_audience_requests_id_seq" to "service_role";
