do $$
declare
  proof_viewer_user_id text := '4b5e7761-5bf1-4e18-9eb7-d6037a0eb32f';
  fixture_playback_item_id uuid := 'fc63e1ba-d744-4350-9a96-a6ef5f35491e';
  fixture_broadcast_session_id uuid := '048a879b-7174-450e-a6cc-0b1758ec4879';
  fixture_playback_record_id uuid := 'abba8e59-3cd2-4306-93e4-6ac7f93a76f3';
  fixture_ended_item_id uuid := 'd5f75ba8-98ef-4fa9-a913-f41e407715b2';
  fixture_reuse_disabled_item_id uuid := '01f66803-a879-443e-acbc-a147a7bba1b8';
  fixture_private_item_id uuid := 'ff249d8e-44eb-4d7c-a978-7cb8c4d45002';
  fixture_blocked_item_id uuid := '5d681640-7246-42f1-bba9-14e146d4235d';
begin
  insert into public."room_broadcast_sessions" (
    "id",
    "source_type",
    "source_room_id",
    "watch_party_room_id",
    "host_user_id",
    "channel_user_id",
    "broadcast_status",
    "egress_provider",
    "egress_status",
    "hls_playback_url",
    "playback_url_status",
    "rights_status",
    "access_type",
    "ad_policy",
    "is_publicly_watchable",
    "is_spectator_playback_enabled",
    "requires_premium",
    "requires_ticket",
    "cost_guard_status",
    "started_at",
    "metadata",
    "updated_at"
  ) values (
    fixture_broadcast_session_id,
    'manual_foundation',
    'spectator_fixture_content_20260526',
    null,
    proof_viewer_user_id,
    proof_viewer_user_id,
    'active_later',
    'manual_foundation',
    'active_later',
    'https://test-streams.mux.dev/x36xhzz/url_6/193039199_mp4_h264_aac_hq_7.m3u8',
    'public_safe_available',
    'licensed_for_public_stream',
    'public_free',
    'no_ads',
    true,
    true,
    false,
    false,
    'foundation',
    timezone('utc'::text, now()),
    jsonb_build_object(
      'd7f_public_safe_approved', true,
      'spectator_child_room_fixture', true,
      'fixture_scope', 'android_runtime_validation',
      'content_title', 'Big Buck Bunny',
      'content_attribution', 'Big Buck Bunny by Blender Foundation, CC BY 3.0',
      'fixture_public_hls_source', 'Mux public test stream',
      'full_room_token_for_spectators', false,
      'original_room_publish_permission', false,
      'raw_hls_url_returned_to_public', false,
      'spectator_playback_enabled', true
    ),
    timezone('utc'::text, now())
  )
  on conflict ("id") do update
  set
    "source_type" = excluded."source_type",
    "source_room_id" = excluded."source_room_id",
    "host_user_id" = excluded."host_user_id",
    "channel_user_id" = excluded."channel_user_id",
    "broadcast_status" = excluded."broadcast_status",
    "egress_provider" = excluded."egress_provider",
    "egress_status" = excluded."egress_status",
    "hls_playback_url" = excluded."hls_playback_url",
    "playback_url_status" = excluded."playback_url_status",
    "rights_status" = excluded."rights_status",
    "access_type" = excluded."access_type",
    "ad_policy" = excluded."ad_policy",
    "is_publicly_watchable" = excluded."is_publicly_watchable",
    "is_spectator_playback_enabled" = excluded."is_spectator_playback_enabled",
    "requires_premium" = excluded."requires_premium",
    "requires_ticket" = excluded."requires_ticket",
    "cost_guard_status" = excluded."cost_guard_status",
    "metadata" = excluded."metadata",
    "updated_at" = excluded."updated_at";

  insert into public."spectator_hls_playback_records" (
    "id",
    "broadcast_session_id",
    "source_room_id",
    "watch_party_room_id",
    "host_user_id",
    "channel_user_id",
    "visibility",
    "playback_status",
    "playlist_path",
    "rights_status",
    "access_type",
    "is_publicly_watchable",
    "is_spectator_playback_enabled",
    "requires_premium",
    "requires_ticket",
    "metadata",
    "updated_at"
  ) values (
    fixture_playback_record_id,
    fixture_broadcast_session_id,
    'spectator_fixture_content_20260526',
    null,
    proof_viewer_user_id,
    proof_viewer_user_id,
    'public',
    'live',
    'x36xhzz/url_6/193039199_mp4_h264_aac_hq_7.m3u8',
    'licensed_for_public_stream',
    'public_free',
    true,
    true,
    false,
    false,
    jsonb_build_object(
      'd7f_public_safe_gate', true,
      'spectator_child_room_fixture', true,
      'fixture_scope', 'android_runtime_validation',
      'content_attribution', 'Big Buck Bunny by Blender Foundation, CC BY 3.0',
      'full_room_token_for_spectators', false,
      'raw_hls_url_visible_to_public', false,
      'source_type', 'creator_video'
    ),
    timezone('utc'::text, now())
  )
  on conflict ("id") do update
  set
    "broadcast_session_id" = excluded."broadcast_session_id",
    "source_room_id" = excluded."source_room_id",
    "host_user_id" = excluded."host_user_id",
    "channel_user_id" = excluded."channel_user_id",
    "visibility" = excluded."visibility",
    "playback_status" = excluded."playback_status",
    "playlist_path" = excluded."playlist_path",
    "rights_status" = excluded."rights_status",
    "access_type" = excluded."access_type",
    "is_publicly_watchable" = excluded."is_publicly_watchable",
    "is_spectator_playback_enabled" = excluded."is_spectator_playback_enabled",
    "requires_premium" = excluded."requires_premium",
    "requires_ticket" = excluded."requires_ticket",
    "metadata" = excluded."metadata",
    "updated_at" = excluded."updated_at";

  insert into public."discovery_feed_items" (
    "id",
    "item_type",
    "source_type",
    "source_id",
    "owner_user_id",
    "channel_user_id",
    "host_user_id",
    "room_id",
    "title",
    "subtitle",
    "thumbnail_url",
    "visibility",
    "access_type",
    "rights_status",
    "ad_policy",
    "discovery_surface",
    "published_at",
    "live_state",
    "moderation_status",
    "is_publicly_discoverable",
    "is_spectator_enabled",
    "is_spectator_playback_enabled",
    "requires_premium_to_join",
    "requires_ticket_to_watch",
    "requires_subscription_to_watch",
    "category_key",
    "ranking_score",
    "ranking_reason",
    "metadata",
    "allow_spectator_view",
    "allow_watch_party_from_spectator",
    "allow_live_reaction_rooms",
    "allow_public_share",
    "allow_replay_watch_party",
    "updated_at"
  ) values (
    fixture_playback_item_id,
    'creator_upload',
    'creator_video',
    'spectator_fixture_content_20260526',
    proof_viewer_user_id,
    proof_viewer_user_id,
    proof_viewer_user_id,
    'spectator_fixture_content_20260526',
    'Chi''llwood Safe Playback Fixture',
    'Public-safe playback fixture for Android validation. Big Buck Bunny by Blender Foundation, CC BY 3.0.',
    null,
    'public',
    'public_free',
    'licensed_for_public_stream',
    'no_ads',
    'none',
    timezone('utc'::text, now()),
    'not_live',
    'clean',
    true,
    true,
    true,
    false,
    false,
    false,
    'spectator_validation',
    0,
    'manual_foundation',
    jsonb_build_object(
      'spectator_child_room_fixture', true,
      'fixture_scope', 'android_runtime_validation',
      'platformName', 'Chi''llwood Safe Fixtures',
      'creatorName', 'Blender Foundation',
      'source_kind', 'creator_video',
      'content_title', 'Big Buck Bunny',
      'content_attribution', 'Big Buck Bunny by Blender Foundation, CC BY 3.0',
      'full_room_token_for_spectators', false,
      'original_room_publish_permission', false,
      'raw_hls_url_visible_to_public', false
    ),
    true,
    true,
    false,
    true,
    false,
    timezone('utc'::text, now())
  )
  on conflict ("id") do update
  set
    "item_type" = excluded."item_type",
    "source_type" = excluded."source_type",
    "source_id" = excluded."source_id",
    "owner_user_id" = excluded."owner_user_id",
    "channel_user_id" = excluded."channel_user_id",
    "host_user_id" = excluded."host_user_id",
    "room_id" = excluded."room_id",
    "title" = excluded."title",
    "subtitle" = excluded."subtitle",
    "thumbnail_url" = excluded."thumbnail_url",
    "visibility" = excluded."visibility",
    "access_type" = excluded."access_type",
    "rights_status" = excluded."rights_status",
    "ad_policy" = excluded."ad_policy",
    "discovery_surface" = excluded."discovery_surface",
    "published_at" = excluded."published_at",
    "live_state" = excluded."live_state",
    "moderation_status" = excluded."moderation_status",
    "is_publicly_discoverable" = excluded."is_publicly_discoverable",
    "is_spectator_enabled" = excluded."is_spectator_enabled",
    "is_spectator_playback_enabled" = excluded."is_spectator_playback_enabled",
    "requires_premium_to_join" = excluded."requires_premium_to_join",
    "requires_ticket_to_watch" = excluded."requires_ticket_to_watch",
    "requires_subscription_to_watch" = excluded."requires_subscription_to_watch",
    "category_key" = excluded."category_key",
    "ranking_score" = excluded."ranking_score",
    "ranking_reason" = excluded."ranking_reason",
    "metadata" = excluded."metadata",
    "allow_spectator_view" = excluded."allow_spectator_view",
    "allow_watch_party_from_spectator" = excluded."allow_watch_party_from_spectator",
    "allow_live_reaction_rooms" = excluded."allow_live_reaction_rooms",
    "allow_public_share" = excluded."allow_public_share",
    "allow_replay_watch_party" = excluded."allow_replay_watch_party",
    "updated_at" = excluded."updated_at";

  insert into public."discovery_feed_items" (
    "id",
    "item_type",
    "source_type",
    "source_id",
    "owner_user_id",
    "channel_user_id",
    "host_user_id",
    "room_id",
    "title",
    "subtitle",
    "visibility",
    "access_type",
    "rights_status",
    "ad_policy",
    "discovery_surface",
    "published_at",
    "ended_at",
    "live_state",
    "moderation_status",
    "is_publicly_discoverable",
    "is_spectator_enabled",
    "is_spectator_playback_enabled",
    "requires_premium_to_join",
    "requires_ticket_to_watch",
    "requires_subscription_to_watch",
    "category_key",
    "ranking_score",
    "ranking_reason",
    "metadata",
    "allow_spectator_view",
    "allow_watch_party_from_spectator",
    "allow_live_reaction_rooms",
    "allow_public_share",
    "allow_replay_watch_party",
    "updated_at"
  )
  values
    (
      fixture_ended_item_id,
      'live_room',
      'watch_party_room',
      'spectator_fixture_ended_20260526',
      proof_viewer_user_id,
      proof_viewer_user_id,
      proof_viewer_user_id,
      'spectator_fixture_ended_20260526',
      'Chi''llwood Ended Source Fixture',
      'Public-safe ended source fixture for Android validation.',
      'public',
      'public_free',
      'creator_owned',
      'no_ads',
      'none',
      timezone('utc'::text, now()) - interval '2 hours',
      timezone('utc'::text, now()) - interval '1 hour',
      'ended',
      'clean',
      true,
      true,
      false,
      false,
      false,
      false,
      'spectator_validation',
      0,
      'manual_foundation',
      jsonb_build_object(
        'spectator_child_room_fixture', true,
        'fixture_scope', 'android_runtime_validation',
        'platformName', 'Chi''llwood Safe Fixtures',
        'source_kind', 'live_stage',
        'full_room_token_for_spectators', false,
        'original_room_publish_permission', false
      ),
      true,
      false,
      false,
      true,
      false,
      timezone('utc'::text, now())
    ),
    (
      fixture_reuse_disabled_item_id,
      'creator_upload',
      'creator_video',
      'spectator_fixture_reuse_disabled_20260526',
      proof_viewer_user_id,
      proof_viewer_user_id,
      proof_viewer_user_id,
      'spectator_fixture_reuse_disabled_20260526',
      'Chi''llwood Reuse Disabled Fixture',
      'Public-safe source fixture with watch-party reuse disabled.',
      'public',
      'public_free',
      'creator_owned',
      'no_ads',
      'none',
      timezone('utc'::text, now()),
      null,
      'not_live',
      'clean',
      true,
      true,
      false,
      false,
      false,
      false,
      'spectator_validation',
      0,
      'manual_foundation',
      jsonb_build_object(
        'spectator_child_room_fixture', true,
        'fixture_scope', 'android_runtime_validation',
        'platformName', 'Chi''llwood Safe Fixtures',
        'source_kind', 'creator_video',
        'allow_watch_party_from_spectator', false
      ),
      true,
      false,
      false,
      true,
      false,
      timezone('utc'::text, now())
    ),
    (
      fixture_private_item_id,
      'live_room',
      'watch_party_room',
      'spectator_fixture_private_20260526',
      proof_viewer_user_id,
      proof_viewer_user_id,
      proof_viewer_user_id,
      'spectator_fixture_private_20260526',
      'Chi''llwood Private Source Fixture',
      'Private source fixture for denied Spectator validation.',
      'private',
      'private',
      'private_use_only',
      'ads_not_allowed',
      'none',
      timezone('utc'::text, now()),
      null,
      'not_live',
      'clean',
      false,
      false,
      false,
      true,
      false,
      false,
      'spectator_validation',
      0,
      'manual_foundation',
      jsonb_build_object(
        'spectator_child_room_fixture', true,
        'fixture_scope', 'android_runtime_validation',
        'private_source', true
      ),
      false,
      false,
      false,
      false,
      false,
      timezone('utc'::text, now())
    ),
    (
      fixture_blocked_item_id,
      'creator_upload',
      'creator_video',
      'spectator_fixture_blocked_20260526',
      proof_viewer_user_id,
      proof_viewer_user_id,
      proof_viewer_user_id,
      'spectator_fixture_blocked_20260526',
      'Chi''llwood Blocked Source Fixture',
      'Public-safe source fixture blocked for the Android proof account.',
      'public',
      'public_free',
      'creator_owned',
      'no_ads',
      'none',
      timezone('utc'::text, now()),
      null,
      'not_live',
      'clean',
      true,
      true,
      false,
      false,
      false,
      false,
      'spectator_validation',
      0,
      'manual_foundation',
      jsonb_build_object(
        'spectator_child_room_fixture', true,
        'fixture_scope', 'android_runtime_validation',
        'platformName', 'Chi''llwood Safe Fixtures',
        'blocked_for_android_proof_account', true
      ),
      true,
      false,
      false,
      true,
      false,
      timezone('utc'::text, now())
    )
  on conflict ("id") do update
  set
    "item_type" = excluded."item_type",
    "source_type" = excluded."source_type",
    "source_id" = excluded."source_id",
    "owner_user_id" = excluded."owner_user_id",
    "channel_user_id" = excluded."channel_user_id",
    "host_user_id" = excluded."host_user_id",
    "room_id" = excluded."room_id",
    "title" = excluded."title",
    "subtitle" = excluded."subtitle",
    "visibility" = excluded."visibility",
    "access_type" = excluded."access_type",
    "rights_status" = excluded."rights_status",
    "ad_policy" = excluded."ad_policy",
    "discovery_surface" = excluded."discovery_surface",
    "published_at" = excluded."published_at",
    "ended_at" = excluded."ended_at",
    "live_state" = excluded."live_state",
    "moderation_status" = excluded."moderation_status",
    "is_publicly_discoverable" = excluded."is_publicly_discoverable",
    "is_spectator_enabled" = excluded."is_spectator_enabled",
    "is_spectator_playback_enabled" = excluded."is_spectator_playback_enabled",
    "requires_premium_to_join" = excluded."requires_premium_to_join",
    "requires_ticket_to_watch" = excluded."requires_ticket_to_watch",
    "requires_subscription_to_watch" = excluded."requires_subscription_to_watch",
    "category_key" = excluded."category_key",
    "ranking_score" = excluded."ranking_score",
    "ranking_reason" = excluded."ranking_reason",
    "metadata" = excluded."metadata",
    "allow_spectator_view" = excluded."allow_spectator_view",
    "allow_watch_party_from_spectator" = excluded."allow_watch_party_from_spectator",
    "allow_live_reaction_rooms" = excluded."allow_live_reaction_rooms",
    "allow_public_share" = excluded."allow_public_share",
    "allow_replay_watch_party" = excluded."allow_replay_watch_party",
    "updated_at" = excluded."updated_at";

  insert into public."discovery_feed_item_blocks" (
    "feed_item_id",
    "blocked_user_id",
    "reason",
    "metadata"
  ) values (
    fixture_blocked_item_id,
    proof_viewer_user_id,
    'blocked_relationship',
    jsonb_build_object(
      'spectator_child_room_fixture', true,
      'fixture_scope', 'android_runtime_validation'
    )
  )
  on conflict ("feed_item_id", "blocked_user_id") do update
  set
    "reason" = excluded."reason",
    "metadata" = excluded."metadata";
end $$;

comment on table public."spectator_child_room_sources" is
  'Safe child-room source links. Android runtime fixtures were added in 202605260004 without storing original LiveKit tokens, publish grants, host controls, member lists, or raw private playback paths in child links.';
