do $$
declare
  proof_viewer_user_id text := '4b5e7761-5bf1-4e18-9eb7-d6037a0eb32f';
  replay_item_id uuid := '9c5f5655-1fbb-4ac8-9473-a5a8d73f3a19';
  replay_broadcast_session_id uuid := '7c05f5a4-3557-40a8-aa3a-82959f2895e0';
  replay_playback_record_id uuid := '40c25310-f0f9-46a3-bfdb-056a9405f6a0';
begin
  insert into public."room_broadcast_sessions" (
    "id",
    "source_type",
    "source_room_id",
    "watch_party_room_id",
    "host_user_id",
    "channel_user_id",
    "broadcast_status",
    "egress_provider",
    "egress_status",
    "hls_playback_url",
    "playback_url_status",
    "rights_status",
    "access_type",
    "ad_policy",
    "is_publicly_watchable",
    "is_spectator_playback_enabled",
    "requires_premium",
    "requires_ticket",
    "cost_guard_status",
    "started_at",
    "ended_at",
    "metadata",
    "updated_at"
  ) values (
    replay_broadcast_session_id,
    'manual_foundation',
    'spectator_fixture_replay_archive_20260526',
    null,
    proof_viewer_user_id,
    proof_viewer_user_id,
    'ended',
    'manual_foundation',
    'stopped_later',
    'https://test-streams.mux.dev/x36xhzz/url_6/193039199_mp4_h264_aac_hq_7.m3u8',
    'public_safe_available',
    'licensed_for_public_stream',
    'public_free',
    'no_ads',
    true,
    true,
    false,
    false,
    'foundation',
    timezone('utc'::text, now()) - interval '2 hours',
    timezone('utc'::text, now()) - interval '90 minutes',
    jsonb_build_object(
      'd7f_public_safe_approved', true,
      'spectator_child_room_fixture', true,
      'fixture_scope', 'android_replay_archive_validation',
      'source_kind', 'replay_archive',
      'content_title', 'Big Buck Bunny',
      'content_attribution', 'Big Buck Bunny by Blender Foundation, CC BY 3.0',
      'fixture_public_hls_source', 'Mux public test stream',
      'replay_archive_available', true,
      'source_is_live', false,
      'full_room_token_for_spectators', false,
      'original_room_publish_permission', false,
      'raw_hls_url_returned_to_public', false,
      'spectator_playback_enabled', true
    ),
    timezone('utc'::text, now())
  )
  on conflict ("id") do update
  set
    "source_type" = excluded."source_type",
    "source_room_id" = excluded."source_room_id",
    "host_user_id" = excluded."host_user_id",
    "channel_user_id" = excluded."channel_user_id",
    "broadcast_status" = excluded."broadcast_status",
    "egress_provider" = excluded."egress_provider",
    "egress_status" = excluded."egress_status",
    "hls_playback_url" = excluded."hls_playback_url",
    "playback_url_status" = excluded."playback_url_status",
    "rights_status" = excluded."rights_status",
    "access_type" = excluded."access_type",
    "ad_policy" = excluded."ad_policy",
    "is_publicly_watchable" = excluded."is_publicly_watchable",
    "is_spectator_playback_enabled" = excluded."is_spectator_playback_enabled",
    "requires_premium" = excluded."requires_premium",
    "requires_ticket" = excluded."requires_ticket",
    "cost_guard_status" = excluded."cost_guard_status",
    "started_at" = excluded."started_at",
    "ended_at" = excluded."ended_at",
    "metadata" = excluded."metadata",
    "updated_at" = excluded."updated_at";

  insert into public."spectator_hls_playback_records" (
    "id",
    "broadcast_session_id",
    "source_room_id",
    "watch_party_room_id",
    "host_user_id",
    "channel_user_id",
    "visibility",
    "playback_status",
    "playlist_path",
    "rights_status",
    "access_type",
    "is_publicly_watchable",
    "is_spectator_playback_enabled",
    "requires_premium",
    "requires_ticket",
    "metadata",
    "updated_at"
  ) values (
    replay_playback_record_id,
    replay_broadcast_session_id,
    'spectator_fixture_replay_archive_20260526',
    null,
    proof_viewer_user_id,
    proof_viewer_user_id,
    'public',
    'live',
    'x36xhzz/url_6/193039199_mp4_h264_aac_hq_7.m3u8',
    'licensed_for_public_stream',
    'public_free',
    true,
    true,
    false,
    false,
    jsonb_build_object(
      'd7f_public_safe_gate', true,
      'spectator_child_room_fixture', true,
      'fixture_scope', 'android_replay_archive_validation',
      'source_kind', 'replay_archive',
      'content_attribution', 'Big Buck Bunny by Blender Foundation, CC BY 3.0',
      'replay_archive_available', true,
      'source_is_live', false,
      'full_room_token_for_spectators', false,
      'raw_hls_url_visible_to_public', false
    ),
    timezone('utc'::text, now())
  )
  on conflict ("id") do update
  set
    "broadcast_session_id" = excluded."broadcast_session_id",
    "source_room_id" = excluded."source_room_id",
    "host_user_id" = excluded."host_user_id",
    "channel_user_id" = excluded."channel_user_id",
    "visibility" = excluded."visibility",
    "playback_status" = excluded."playback_status",
    "playlist_path" = excluded."playlist_path",
    "rights_status" = excluded."rights_status",
    "access_type" = excluded."access_type",
    "is_publicly_watchable" = excluded."is_publicly_watchable",
    "is_spectator_playback_enabled" = excluded."is_spectator_playback_enabled",
    "requires_premium" = excluded."requires_premium",
    "requires_ticket" = excluded."requires_ticket",
    "metadata" = excluded."metadata",
    "updated_at" = excluded."updated_at";

  insert into public."discovery_feed_items" (
    "id",
    "item_type",
    "source_type",
    "source_id",
    "owner_user_id",
    "channel_user_id",
    "host_user_id",
    "room_id",
    "title",
    "subtitle",
    "thumbnail_url",
    "visibility",
    "access_type",
    "rights_status",
    "ad_policy",
    "discovery_surface",
    "published_at",
    "ended_at",
    "live_state",
    "moderation_status",
    "is_publicly_discoverable",
    "is_spectator_enabled",
    "is_spectator_playback_enabled",
    "requires_premium_to_join",
    "requires_ticket_to_watch",
    "requires_subscription_to_watch",
    "category_key",
    "ranking_score",
    "ranking_reason",
    "metadata",
    "allow_spectator_view",
    "allow_watch_party_from_spectator",
    "allow_live_reaction_rooms",
    "allow_public_share",
    "allow_replay_watch_party",
    "updated_at"
  ) values (
    replay_item_id,
    'replay_later',
    'creator_video',
    'spectator_fixture_replay_archive_20260526',
    proof_viewer_user_id,
    proof_viewer_user_id,
    proof_viewer_user_id,
    'spectator_fixture_replay_archive_20260526',
    'Chi''llwood Replay Archive Fixture',
    'Public-safe replay archive fixture for Android validation. Big Buck Bunny by Blender Foundation, CC BY 3.0.',
    null,
    'public',
    'public_free',
    'licensed_for_public_stream',
    'no_ads',
    'none',
    timezone('utc'::text, now()) - interval '90 minutes',
    timezone('utc'::text, now()) - interval '90 minutes',
    'replay_available_later',
    'clean',
    true,
    true,
    true,
    false,
    false,
    false,
    'spectator_validation',
    0,
    'manual_foundation',
    jsonb_build_object(
      'spectator_child_room_fixture', true,
      'fixture_scope', 'android_replay_archive_validation',
      'platformName', 'Chi''llwood Safe Fixtures',
      'creatorName', 'Blender Foundation',
      'source_kind', 'replay_archive',
      'content_title', 'Big Buck Bunny',
      'content_attribution', 'Big Buck Bunny by Blender Foundation, CC BY 3.0',
      'replay_archive_available', true,
      'source_is_live', false,
      'full_room_token_for_spectators', false,
      'original_room_publish_permission', false,
      'raw_hls_url_visible_to_public', false
    ),
    true,
    true,
    false,
    true,
    true,
    timezone('utc'::text, now())
  )
  on conflict ("id") do update
  set
    "item_type" = excluded."item_type",
    "source_type" = excluded."source_type",
    "source_id" = excluded."source_id",
    "owner_user_id" = excluded."owner_user_id",
    "channel_user_id" = excluded."channel_user_id",
    "host_user_id" = excluded."host_user_id",
    "room_id" = excluded."room_id",
    "title" = excluded."title",
    "subtitle" = excluded."subtitle",
    "thumbnail_url" = excluded."thumbnail_url",
    "visibility" = excluded."visibility",
    "access_type" = excluded."access_type",
    "rights_status" = excluded."rights_status",
    "ad_policy" = excluded."ad_policy",
    "discovery_surface" = excluded."discovery_surface",
    "published_at" = excluded."published_at",
    "ended_at" = excluded."ended_at",
    "live_state" = excluded."live_state",
    "moderation_status" = excluded."moderation_status",
    "is_publicly_discoverable" = excluded."is_publicly_discoverable",
    "is_spectator_enabled" = excluded."is_spectator_enabled",
    "is_spectator_playback_enabled" = excluded."is_spectator_playback_enabled",
    "requires_premium_to_join" = excluded."requires_premium_to_join",
    "requires_ticket_to_watch" = excluded."requires_ticket_to_watch",
    "requires_subscription_to_watch" = excluded."requires_subscription_to_watch",
    "category_key" = excluded."category_key",
    "ranking_score" = excluded."ranking_score",
    "ranking_reason" = excluded."ranking_reason",
    "metadata" = excluded."metadata",
    "allow_spectator_view" = excluded."allow_spectator_view",
    "allow_watch_party_from_spectator" = excluded."allow_watch_party_from_spectator",
    "allow_live_reaction_rooms" = excluded."allow_live_reaction_rooms",
    "allow_public_share" = excluded."allow_public_share",
    "allow_replay_watch_party" = excluded."allow_replay_watch_party",
    "updated_at" = excluded."updated_at";
end $$;
