create table if not exists public."user_entitlements" (
  "user_id" text not null,
  "entitlement_key" text not null,
  "status" text default 'pending'::text not null,
  "source" text default 'operator_grant'::text not null,
  "starts_at" timestamp with time zone,
  "expires_at" timestamp with time zone,
  "revoked_at" timestamp with time zone,
  "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "metadata" jsonb default '{}'::jsonb not null,
  constraint "user_entitlements_pkey" primary key ("user_id", "entitlement_key")
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'user_entitlements_key_check'
  ) then
    alter table public."user_entitlements"
      add constraint "user_entitlements_key_check"
      check ("entitlement_key" in ('premium', 'premium_watch_party', 'premium_live', 'paid_content'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'user_entitlements_status_check'
  ) then
    alter table public."user_entitlements"
      add constraint "user_entitlements_status_check"
      check ("status" in ('active', 'trialing', 'grace_period', 'pending', 'expired', 'canceled', 'revoked'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'user_entitlements_source_check'
  ) then
    alter table public."user_entitlements"
      add constraint "user_entitlements_source_check"
      check ("source" in ('revenuecat', 'operator_grant', 'billing_sync', 'migration', 'test_grant'));
  end if;
end $$;

create index if not exists "user_entitlements_user_status_idx"
  on public."user_entitlements" using btree ("user_id", "status", "expires_at");

alter table public."user_entitlements" enable row level security;

drop policy if exists "user_entitlements_select_self_or_operator" on public."user_entitlements";
create policy "user_entitlements_select_self_or_operator"
  on public."user_entitlements"
  for select
  to public
  using (
    ((auth.uid() is not null) and ("user_id" = (auth.uid())::text))
    or public.has_platform_role(array['owner', 'operator'])
  );

drop policy if exists "user_entitlements_operator_insert" on public."user_entitlements";
create policy "user_entitlements_operator_insert"
  on public."user_entitlements"
  for insert
  to public
  with check (public.has_platform_role(array['owner', 'operator']));

drop policy if exists "user_entitlements_operator_update" on public."user_entitlements";
create policy "user_entitlements_operator_update"
  on public."user_entitlements"
  for update
  to public
  using (public.has_platform_role(array['owner', 'operator']))
  with check (public.has_platform_role(array['owner', 'operator']));

drop policy if exists "user_entitlements_operator_delete" on public."user_entitlements";
create policy "user_entitlements_operator_delete"
  on public."user_entitlements"
  for delete
  to public
  using (public.has_platform_role(array['owner', 'operator']));

create table if not exists public."billing_events" (
  "id" bigint generated by default as identity not null,
  "user_id" text,
  "event_type" text not null,
  "provider" text default 'manual'::text not null,
  "entitlement_key" text,
  "status" text,
  "occurred_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "metadata" jsonb default '{}'::jsonb not null,
  constraint "billing_events_pkey" primary key ("id")
);

create index if not exists "billing_events_user_occurred_idx"
  on public."billing_events" using btree ("user_id", "occurred_at" desc);

alter table public."billing_events" enable row level security;

drop policy if exists "billing_events_select_self_or_operator" on public."billing_events";
create policy "billing_events_select_self_or_operator"
  on public."billing_events"
  for select
  to public
  using (
    ((auth.uid() is not null) and ("user_id" = (auth.uid())::text))
    or public.has_platform_role(array['owner', 'operator'])
  );

drop policy if exists "billing_events_operator_insert" on public."billing_events";
create policy "billing_events_operator_insert"
  on public."billing_events"
  for insert
  to public
  with check (public.has_platform_role(array['owner', 'operator']));

drop policy if exists "billing_events_operator_update" on public."billing_events";
create policy "billing_events_operator_update"
  on public."billing_events"
  for update
  to public
  using (public.has_platform_role(array['owner', 'operator']))
  with check (public.has_platform_role(array['owner', 'operator']));

drop policy if exists "billing_events_operator_delete" on public."billing_events";
create policy "billing_events_operator_delete"
  on public."billing_events"
  for delete
  to public
  using (public.has_platform_role(array['owner', 'operator']));

drop policy if exists "user_subscriptions_insert_own" on public."user_subscriptions";
drop policy if exists "user_subscriptions_update_own" on public."user_subscriptions";
drop policy if exists "user_subscriptions_select_own" on public."user_subscriptions";

create policy "user_subscriptions_select_self_or_operator"
  on public."user_subscriptions"
  for select
  to public
  using (
    ((auth.uid() is not null) and ("user_id" = (auth.uid())::text))
    or public.has_platform_role(array['owner', 'operator'])
  );

create policy "user_subscriptions_operator_insert"
  on public."user_subscriptions"
  for insert
  to public
  with check (public.has_platform_role(array['owner', 'operator']));

create policy "user_subscriptions_operator_update"
  on public."user_subscriptions"
  for update
  to public
  using (public.has_platform_role(array['owner', 'operator']))
  with check (public.has_platform_role(array['owner', 'operator']));

drop policy if exists "watch_party_pass_unlocks_insert_own" on public."watch_party_pass_unlocks";
drop policy if exists "watch_party_pass_unlocks_update_own" on public."watch_party_pass_unlocks";
drop policy if exists "watch_party_pass_unlocks_select_own" on public."watch_party_pass_unlocks";

create policy "watch_party_pass_unlocks_select_self_or_operator"
  on public."watch_party_pass_unlocks"
  for select
  to public
  using (
    ((auth.uid() is not null) and ("user_id" = (auth.uid())::text))
    or public.has_platform_role(array['owner', 'operator'])
  );

create policy "watch_party_pass_unlocks_operator_insert"
  on public."watch_party_pass_unlocks"
  for insert
  to public
  with check (public.has_platform_role(array['owner', 'operator']));

create policy "watch_party_pass_unlocks_operator_update"
  on public."watch_party_pass_unlocks"
  for update
  to public
  using (public.has_platform_role(array['owner', 'operator']))
  with check (public.has_platform_role(array['owner', 'operator']));

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  on table public."user_entitlements" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  on table public."user_entitlements" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  on table public."user_entitlements" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  on table public."user_entitlements" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  on table public."billing_events" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  on table public."billing_events" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  on table public."billing_events" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  on table public."billing_events" to "service_role";
