-- Sandbox RevenueCat / Google Play product mappings for dynamic digital proof.
-- These rows enable purchase intents only for sandbox testing. They do not enable
-- production live money, public buy buttons, payable ledger rows, payouts,
-- cash-out, LiveKit publish permission, host power, or speaker authority.

insert into public."monetization_products" (
  "product_key",
  "product_type",
  "display_name",
  "description",
  "provider",
  "provider_product_id",
  "provider_base_plan_id",
  "revenuecat_entitlement",
  "applies_to_type",
  "applies_to_id",
  "environment",
  "status",
  "is_android_digital",
  "is_physical_good",
  "metadata"
)
values
  (
    'paid_content_access_sandbox_099',
    'paid_content_access',
    'Paid content sandbox access',
    'Reusable sandbox Google Play / RevenueCat price-tier product for paid content access proof. A backend purchase intent binds each purchase to one content item.',
    'revenuecat_google_play',
    'cw_paid_content_access_sandbox_099',
    null,
    null,
    'paid_content',
    null,
    'sandbox',
    'sandbox',
    true,
    false,
    jsonb_build_object(
      'sandbox_purchase_intents_enabled', true,
      'google_play_product_type', 'one_time_product',
      'revenuecat_product_type', 'consumable',
      'price_tier', '099',
      'public_buy_button_active', false,
      'not_payable', true,
      'requires_purchase_intent', true
    )
  ),
  (
    'watch_party_live_ticket_sandbox_099',
    'watch_party_live_ticket',
    'Watch-Party Live ticket sandbox',
    'Reusable sandbox Google Play / RevenueCat ticket product. Ticket access is viewing/listening only and never grants speaker, host, or LiveKit publish authority.',
    'revenuecat_google_play',
    'cw_watch_party_live_ticket_sandbox_099',
    null,
    null,
    'watch_party_live',
    null,
    'sandbox',
    'sandbox',
    true,
    false,
    jsonb_build_object(
      'sandbox_purchase_intents_enabled', true,
      'google_play_product_type', 'one_time_product',
      'revenuecat_product_type', 'consumable',
      'price_tier', '099',
      'public_buy_button_active', false,
      'not_payable', true,
      'requires_purchase_intent', true,
      'grants_livekit_publish', false,
      'host_approval_still_required', true
    )
  ),
  (
    'live_watch_party_access_pass_sandbox_099',
    'live_watch_party_access_pass',
    'Live Watch-Party access sandbox',
    'Reusable sandbox Google Play / RevenueCat access pass product. Access pass allows entry/viewing only when room policy and safety allow.',
    'revenuecat_google_play',
    'cw_live_watch_party_access_sandbox_099',
    null,
    null,
    'live_watch_party_access',
    null,
    'sandbox',
    'sandbox',
    true,
    false,
    jsonb_build_object(
      'sandbox_purchase_intents_enabled', true,
      'google_play_product_type', 'one_time_product',
      'revenuecat_product_type', 'consumable',
      'price_tier', '099',
      'public_buy_button_active', false,
      'not_payable', true,
      'requires_purchase_intent', true,
      'viewer_only', true,
      'grants_livekit_publish', false
    )
  ),
  (
    'live_watch_party_seat_pass_sandbox_099',
    'live_watch_party_seat_pass',
    'Live Watch-Party seat sandbox',
    'Reusable sandbox Google Play / RevenueCat seat eligibility product. Seat pass only makes the user eligible under policy; host approval and LiveKit token rules still win.',
    'revenuecat_google_play',
    'cw_live_watch_party_seat_sandbox_099',
    null,
    null,
    'live_watch_party_seat',
    null,
    'sandbox',
    'sandbox',
    true,
    false,
    jsonb_build_object(
      'sandbox_purchase_intents_enabled', true,
      'google_play_product_type', 'one_time_product',
      'revenuecat_product_type', 'consumable',
      'price_tier', '099',
      'public_buy_button_active', false,
      'not_payable', true,
      'requires_purchase_intent', true,
      'seat_eligibility_only', true,
      'grants_livekit_publish', false,
      'host_approval_still_required', true
    )
  ),
  (
    'creator_tip_sandbox_099',
    'creator_tip',
    'Creator tip sandbox',
    'Reusable sandbox Google Play / RevenueCat creator support product. Tips create sandbox ledger activity only and never create payable balances or payout eligibility.',
    'revenuecat_google_play',
    'cw_creator_tip_sandbox_099',
    null,
    null,
    'creator_tip',
    null,
    'sandbox',
    'sandbox',
    true,
    false,
    jsonb_build_object(
      'sandbox_purchase_intents_enabled', true,
      'google_play_product_type', 'one_time_product',
      'revenuecat_product_type', 'consumable',
      'price_tier', '099',
      'public_tip_button_active', false,
      'not_payable', true,
      'requires_purchase_intent', true,
      'creates_durable_access', false,
      'creates_payout_eligibility', false
    )
  ),
  (
    'event_pass_sandbox_099',
    'event_pass',
    'Event pass sandbox',
    'Reusable sandbox Google Play / RevenueCat event pass product. A backend purchase intent binds each purchase to one event.',
    'revenuecat_google_play',
    'cw_event_pass_sandbox_099',
    null,
    null,
    'event',
    null,
    'sandbox',
    'sandbox',
    true,
    false,
    jsonb_build_object(
      'sandbox_purchase_intents_enabled', true,
      'google_play_product_type', 'one_time_product',
      'revenuecat_product_type', 'consumable',
      'price_tier', '099',
      'public_buy_button_active', false,
      'not_payable', true,
      'requires_purchase_intent', true
    )
  )
on conflict ("product_key") do update
set
  "display_name" = excluded."display_name",
  "description" = excluded."description",
  "provider" = excluded."provider",
  "provider_product_id" = excluded."provider_product_id",
  "provider_base_plan_id" = excluded."provider_base_plan_id",
  "revenuecat_entitlement" = excluded."revenuecat_entitlement",
  "applies_to_type" = excluded."applies_to_type",
  "applies_to_id" = excluded."applies_to_id",
  "environment" = excluded."environment",
  "status" = excluded."status",
  "is_android_digital" = excluded."is_android_digital",
  "is_physical_good" = excluded."is_physical_good",
  "metadata" = public."monetization_products"."metadata" || excluded."metadata",
  "updated_at" = timezone('utc'::text, now());
