-- Canonical current-schema baseline for future bootstrap.
-- Generated from accepted live public schema truth on 2026-04-19.
-- Legacy migration chain remains archived in supabase/migrations_legacy/.

set check_function_bodies = false;
create schema if not exists public;

-- Schema grants
grant USAGE on schema public to PUBLIC;
grant USAGE on schema public to "anon";
grant USAGE on schema public to "authenticated";
grant USAGE, CREATE on schema public to "pg_database_owner";
grant USAGE on schema public to "postgres";
grant USAGE on schema public to "service_role";

-- Tables
create table public."app_configurations" (
    "config_key" text not null,
    "config" jsonb default '{}'::jsonb not null,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    "updated_by" text
);

create table public."beta_access_memberships" (
    "id" bigint generated by default as identity not null,
    "email" text,
    "user_id" text,
    "access_status" text default 'invited'::text not null,
    "cohort" text,
    "notes" text,
    "invited_by" text,
    "invited_at" timestamp with time zone default timezone('utc'::text, now()) not null,
    "activated_at" timestamp with time zone,
    "last_seen_at" timestamp with time zone,
    "onboarding_ack_at" timestamp with time zone
);

create table public."beta_feedback_items" (
    "id" bigint generated by default as identity not null,
    "reporter_user_id" text not null,
    "reporter_email" text,
    "reporter_display_name" text,
    "feedback_type" text not null,
    "category" text not null,
    "severity" text not null,
    "status" text default 'new'::text not null,
    "fix_window" text default 'next_beta'::text not null,
    "source_surface" text,
    "route_path" text,
    "title_id" text,
    "room_id" text,
    "summary" text not null,
    "details" text,
    "context" jsonb default '{}'::jsonb not null,
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public."chat_messages" (
    "id" uuid default gen_random_uuid() not null,
    "thread_id" uuid not null,
    "sender_user_id" text not null,
    "body" text not null,
    "message_type" text default 'text'::text not null,
    "created_at" timestamp with time zone default now() not null
);

create table public."chat_thread_members" (
    "thread_id" uuid not null,
    "user_id" text not null,
    "display_name" text,
    "avatar_url" text,
    "tagline" text,
    "joined_at" timestamp with time zone default now() not null,
    "last_read_at" timestamp with time zone,
    "unread_count" integer default 0 not null
);

create table public."chat_threads" (
    "id" uuid default gen_random_uuid() not null,
    "thread_kind" text default 'direct'::text not null,
    "participant_pair_key" text not null,
    "created_by" text not null,
    "created_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null,
    "last_message_at" timestamp with time zone,
    "last_message_preview" text,
    "active_communication_room_id" text,
    "active_call_type" text
);

create table public."communication_room_memberships" (
    "room_id" text not null,
    "user_id" text not null,
    "role" text default 'participant'::text not null,
    "membership_state" text default 'active'::text not null,
    "camera_enabled" boolean default false not null,
    "mic_enabled" boolean default true not null,
    "display_name" text,
    "avatar_url" text,
    "joined_at" timestamp with time zone default now() not null,
    "last_seen_at" timestamp with time zone default now() not null,
    "left_at" timestamp with time zone,
    "updated_at" timestamp with time zone default now() not null
);

create table public."communication_rooms" (
    "room_id" text not null,
    "room_code" text not null,
    "host_user_id" text not null,
    "status" text default 'active'::text not null,
    "created_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null,
    "linked_party_id" text,
    "linked_room_code" text,
    "linked_room_mode" text,
    "capture_policy" text default 'best_effort'::text not null,
    "content_access_rule" text default 'open'::text not null,
    "last_activity_at" timestamp with time zone default now() not null
);

create table public."creator_permissions" (
    "user_id" text not null,
    "can_use_party_pass_rooms" boolean default true not null,
    "can_use_premium_rooms" boolean default true not null,
    "can_publish_premium_titles" boolean default true not null,
    "can_use_sponsor_placements" boolean default true not null,
    "can_use_player_ads" boolean default true not null,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public."platform_role_memberships" (
    "id" bigint generated by default as identity not null,
    "role" text not null,
    "user_id" text,
    "email" text,
    "status" text default 'active'::text not null,
    "notes" text,
    "granted_by" text,
    "granted_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public."profiles" (
    "id" uuid default gen_random_uuid() not null,
    "display_name" text not null,
    "avatar_ur1" text,
    "bio" text
);

create table public."safety_reports" (
    "id" bigint generated by default as identity not null,
    "reporter_user_id" text not null,
    "target_type" text not null,
    "target_id" text not null,
    "category" text not null,
    "note" text,
    "room_id" text,
    "title_id" text,
    "context" jsonb default '{}'::jsonb not null,
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public."titles" (
    "id" uuid default gen_random_uuid() not null,
    "created_at" timestamp with time zone default now() not null,
    "title" text default 'NOT NULL'::text,
    "category" text default 'NOT NULL'::text,
    "year" integer,
    "runtime" text,
    "synopsis" text,
    "poster_url" text,
    "video_url" text,
    "featured" boolean default false,
    "is_published" boolean default true,
    "sort_order" bigint default 0,
    "hero" boolean default false,
    "trending" boolean default false,
    "status" text default 'published'::text,
    "release_date" timestamp with time zone,
    "top_row" boolean default false,
    "is_hero" boolean default false,
    "is_trending" boolean default false,
    "pin_to_top_row" boolean default false,
    "release_at" timestamp with time zone,
    "content_access_rule" text default 'open'::text not null,
    "ads_enabled" boolean default false not null,
    "sponsor_placement" text default 'none'::text not null,
    "sponsor_label" text
);

create table public."user_content_relationships" (
    "user_id" text not null,
    "title_id" text not null,
    "relationship_type" text not null,
    "updated_at" timestamp with time zone default now() not null
);

create table public."user_list" (
    "user_id" uuid not null,
    "title_id" text not null,
    "updated_at" timestamp with time zone default now() not null
);

create table public."user_profiles" (
    "user_id" text not null,
    "username" text not null,
    "avatar_index" integer default 0 not null,
    "display_name" text,
    "avatar_url" text,
    "tagline" text,
    "channel_role" text,
    "likes_visibility" text default 'public'::text not null,
    "shares_visibility" text default 'public'::text not null,
    "default_watch_party_join_policy" text,
    "default_watch_party_reactions_policy" text,
    "default_watch_party_content_access_rule" text,
    "default_watch_party_capture_policy" text,
    "default_communication_content_access_rule" text,
    "default_communication_capture_policy" text,
    "updated_at" timestamp with time zone default now() not null
);

create table public."user_subscriptions" (
    "user_id" text not null,
    "tier" text default 'free'::text not null,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public."videos" (
    "id" uuid default gen_random_uuid() not null,
    "owner_id" uuid not null,
    "title" text,
    "description" text,
    "playback_url" text,
    "thumb_url" text,
    "created_at" timestamp without time zone default now()
);

create table public."watch_history" (
    "user_id" uuid not null,
    "title_id" text not null,
    "play_count" integer default 1 not null,
    "last_position_millis" bigint default 0 not null,
    "duration_millis" bigint,
    "completed" boolean default false not null,
    "last_watched_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null
);

create table public."watch_party_pass_unlocks" (
    "id" bigint generated by default as identity not null,
    "room_id" text not null,
    "user_id" text not null,
    "unlocked_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public."watch_party_room_memberships" (
    "party_id" text not null,
    "user_id" text not null,
    "role" text default 'viewer'::text not null,
    "stage_role" text default 'listener'::text not null,
    "can_speak" boolean default false not null,
    "is_muted" boolean default false not null,
    "membership_state" text default 'active'::text not null,
    "camera_enabled" boolean default false not null,
    "mic_enabled" boolean default true not null,
    "display_name" text,
    "avatar_url" text,
    "camera_preview_url" text,
    "joined_at" timestamp with time zone default now() not null,
    "last_seen_at" timestamp with time zone default now() not null,
    "left_at" timestamp with time zone,
    "updated_at" timestamp with time zone default now() not null
);

create table public."watch_party_room_messages" (
    "id" uuid default gen_random_uuid() not null,
    "party_id" text not null,
    "user_id" text not null,
    "username" text not null,
    "text" text not null,
    "created_at" timestamp with time zone default now() not null
);

create table public."watch_party_rooms" (
    "party_id" text not null,
    "title_id" text,
    "host_user_id" uuid not null,
    "playback_position_millis" bigint default 0 not null,
    "playback_state" text default 'paused'::text not null,
    "is_active" boolean default true not null,
    "created_at" timestamp with time zone default now() not null,
    "started_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null,
    "room_type" text default 'title'::text not null,
    "join_policy" text default 'open'::text not null,
    "reactions_policy" text default 'enabled'::text not null,
    "content_access_rule" text default 'open'::text not null,
    "capture_policy" text default 'best_effort'::text not null,
    "last_activity_at" timestamp with time zone default now() not null
);

create table public."watch_party_sync_events" (
    "id" text not null,
    "party_id" text not null,
    "user_id" uuid not null,
    "kind" text not null,
    "playback_position_millis" bigint default 0 not null,
    "payload" jsonb default '{}'::jsonb not null,
    "created_at" timestamp with time zone default now() not null
);

-- Constraints
alter table only public."app_configurations" add constraint "app_configurations_pkey" PRIMARY KEY (config_key);
alter table only public."app_configurations" add constraint "app_configurations_singleton_key_check" CHECK (config_key = 'global'::text);

alter table only public."beta_access_memberships" add constraint "beta_access_memberships_pkey" PRIMARY KEY (id);
alter table only public."beta_access_memberships" add constraint "beta_access_memberships_status_check" CHECK (access_status = ANY (ARRAY['invited'::text, 'active'::text, 'paused'::text, 'revoked'::text]));

alter table only public."beta_feedback_items" add constraint "beta_feedback_items_pkey" PRIMARY KEY (id);
alter table only public."beta_feedback_items" add constraint "beta_feedback_items_category_check" CHECK (category = ANY (ARRAY['auth'::text, 'onboarding'::text, 'home'::text, 'player'::text, 'watch_party'::text, 'live_stage'::text, 'communication'::text, 'monetization'::text, 'moderation'::text, 'performance'::text, 'ui_copy'::text, 'other'::text]));
alter table only public."beta_feedback_items" add constraint "beta_feedback_items_fix_window_check" CHECK (fix_window = ANY (ARRAY['hotfix'::text, 'next_beta'::text, 'before_public'::text, 'later'::text]));
alter table only public."beta_feedback_items" add constraint "beta_feedback_items_severity_check" CHECK (severity = ANY (ARRAY['blocking'::text, 'major'::text, 'polish'::text, 'insight'::text]));
alter table only public."beta_feedback_items" add constraint "beta_feedback_items_status_check" CHECK (status = ANY (ARRAY['new'::text, 'confirmed'::text, 'planned'::text, 'fixed'::text, 'deferred'::text, 'needs_info'::text]));
alter table only public."beta_feedback_items" add constraint "beta_feedback_items_type_check" CHECK (feedback_type = ANY (ARRAY['bug'::text, 'product_feedback'::text, 'onboarding_feedback'::text]));

alter table only public."chat_messages" add constraint "chat_messages_pkey" PRIMARY KEY (id);
alter table only public."chat_messages" add constraint "chat_messages_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES chat_threads(id) ON DELETE CASCADE;
alter table only public."chat_messages" add constraint "chat_messages_message_type_check" CHECK (message_type = 'text'::text);

alter table only public."chat_thread_members" add constraint "chat_thread_members_pkey" PRIMARY KEY (thread_id, user_id);
alter table only public."chat_thread_members" add constraint "chat_thread_members_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES chat_threads(id) ON DELETE CASCADE;
alter table only public."chat_thread_members" add constraint "chat_thread_members_unread_count_check" CHECK (unread_count >= 0);

alter table only public."chat_threads" add constraint "chat_threads_pkey" PRIMARY KEY (id);
alter table only public."chat_threads" add constraint "chat_threads_participant_pair_key_key" UNIQUE (participant_pair_key);
alter table only public."chat_threads" add constraint "chat_threads_active_communication_room_id_fkey" FOREIGN KEY (active_communication_room_id) REFERENCES communication_rooms(room_id) ON DELETE SET NULL;
alter table only public."chat_threads" add constraint "chat_threads_active_call_type_check" CHECK (active_call_type = ANY (ARRAY['voice'::text, 'video'::text]));
alter table only public."chat_threads" add constraint "chat_threads_thread_kind_check" CHECK (thread_kind = 'direct'::text);

alter table only public."communication_room_memberships" add constraint "communication_room_memberships_pkey" PRIMARY KEY (room_id, user_id);
alter table only public."communication_room_memberships" add constraint "communication_room_memberships_room_id_fkey" FOREIGN KEY (room_id) REFERENCES communication_rooms(room_id) ON DELETE CASCADE;
alter table only public."communication_room_memberships" add constraint "communication_room_memberships_role_check" CHECK (role = ANY (ARRAY['host'::text, 'participant'::text]));
alter table only public."communication_room_memberships" add constraint "communication_room_memberships_state_check" CHECK (membership_state = ANY (ARRAY['active'::text, 'reconnecting'::text, 'left'::text, 'removed'::text]));

alter table only public."communication_rooms" add constraint "communication_rooms_pkey" PRIMARY KEY (room_id);
alter table only public."communication_rooms" add constraint "communication_rooms_room_code_key" UNIQUE (room_code);
alter table only public."communication_rooms" add constraint "communication_rooms_capture_policy_check" CHECK (capture_policy = ANY (ARRAY['best_effort'::text, 'host_managed'::text]));
alter table only public."communication_rooms" add constraint "communication_rooms_content_access_rule_check" CHECK (content_access_rule = ANY (ARRAY['open'::text, 'party_pass'::text, 'premium'::text]));
alter table only public."communication_rooms" add constraint "communication_rooms_linked_room_mode_check" CHECK (linked_room_mode IS NULL OR (linked_room_mode = ANY (ARRAY['live'::text, 'hybrid'::text])));
alter table only public."communication_rooms" add constraint "communication_rooms_status_check" CHECK (status = ANY (ARRAY['active'::text, 'ended'::text]));

alter table only public."creator_permissions" add constraint "creator_permissions_pkey" PRIMARY KEY (user_id);

alter table only public."platform_role_memberships" add constraint "platform_role_memberships_pkey" PRIMARY KEY (id);
alter table only public."platform_role_memberships" add constraint "platform_role_memberships_identity_check" CHECK (NULLIF(TRIM(BOTH FROM COALESCE(user_id, ''::text)), ''::text) IS NOT NULL OR NULLIF(TRIM(BOTH FROM COALESCE(email, ''::text)), ''::text) IS NOT NULL);
alter table only public."platform_role_memberships" add constraint "platform_role_memberships_role_check" CHECK (role = ANY (ARRAY['operator'::text, 'moderator'::text]));
alter table only public."platform_role_memberships" add constraint "platform_role_memberships_status_check" CHECK (status = ANY (ARRAY['active'::text, 'revoked'::text]));

alter table only public."profiles" add constraint "profiles_pkey" PRIMARY KEY (id);

alter table only public."safety_reports" add constraint "safety_reports_pkey" PRIMARY KEY (id);
alter table only public."safety_reports" add constraint "safety_reports_category_check" CHECK (category = ANY (ARRAY['abuse'::text, 'harassment'::text, 'impersonation'::text, 'copyright'::text, 'safety'::text, 'other'::text]));
alter table only public."safety_reports" add constraint "safety_reports_target_type_check" CHECK (target_type = ANY (ARRAY['participant'::text, 'room'::text, 'title'::text]));

alter table only public."titles" add constraint "titles_pkey" PRIMARY KEY (id);
alter table only public."titles" add constraint "titles_content_access_rule_check" CHECK (content_access_rule = ANY (ARRAY['open'::text, 'premium'::text]));
alter table only public."titles" add constraint "titles_sponsor_placement_check" CHECK (sponsor_placement = ANY (ARRAY['none'::text, 'detail_banner'::text, 'player_banner'::text]));

alter table only public."user_content_relationships" add constraint "user_content_relationships_pkey" PRIMARY KEY (user_id, title_id, relationship_type);
alter table only public."user_content_relationships" add constraint "user_content_relationships_relationship_type_check" CHECK (relationship_type = ANY (ARRAY['like'::text, 'share'::text]));

alter table only public."user_list" add constraint "user_list_pkey" PRIMARY KEY (user_id, title_id);
alter table only public."user_list" add constraint "user_list_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table only public."user_profiles" add constraint "user_profiles_pkey" PRIMARY KEY (user_id);

alter table only public."user_subscriptions" add constraint "user_subscriptions_pkey" PRIMARY KEY (user_id);
alter table only public."user_subscriptions" add constraint "user_subscriptions_tier_check" CHECK (tier = ANY (ARRAY['free'::text, 'premium'::text]));

alter table only public."videos" add constraint "videos_pkey" PRIMARY KEY (id);

alter table only public."watch_history" add constraint "watch_history_pkey" PRIMARY KEY (user_id, title_id);
alter table only public."watch_history" add constraint "watch_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table only public."watch_party_pass_unlocks" add constraint "watch_party_pass_unlocks_pkey" PRIMARY KEY (id);

alter table only public."watch_party_room_memberships" add constraint "watch_party_room_memberships_pkey" PRIMARY KEY (party_id, user_id);
alter table only public."watch_party_room_memberships" add constraint "watch_party_room_memberships_party_id_fkey" FOREIGN KEY (party_id) REFERENCES watch_party_rooms(party_id) ON DELETE CASCADE;
alter table only public."watch_party_room_memberships" add constraint "watch_party_room_memberships_role_check" CHECK (role = ANY (ARRAY['host'::text, 'viewer'::text]));
alter table only public."watch_party_room_memberships" add constraint "watch_party_room_memberships_stage_role_check" CHECK (stage_role = ANY (ARRAY['host'::text, 'speaker'::text, 'listener'::text]));
alter table only public."watch_party_room_memberships" add constraint "watch_party_room_memberships_state_check" CHECK (membership_state = ANY (ARRAY['active'::text, 'reconnecting'::text, 'left'::text, 'removed'::text]));

alter table only public."watch_party_room_messages" add constraint "watch_party_room_messages_pkey" PRIMARY KEY (id);

alter table only public."watch_party_rooms" add constraint "watch_party_rooms_pkey" PRIMARY KEY (party_id);
alter table only public."watch_party_rooms" add constraint "watch_party_rooms_host_user_id_fkey" FOREIGN KEY (host_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only public."watch_party_rooms" add constraint "watch_party_room_type_check" CHECK (room_type = ANY (ARRAY['title'::text, 'live'::text]));
alter table only public."watch_party_rooms" add constraint "watch_party_rooms_capture_policy_check" CHECK (capture_policy = ANY (ARRAY['best_effort'::text, 'host_managed'::text]));
alter table only public."watch_party_rooms" add constraint "watch_party_rooms_content_access_rule_check" CHECK (content_access_rule = ANY (ARRAY['open'::text, 'party_pass'::text, 'premium'::text]));
alter table only public."watch_party_rooms" add constraint "watch_party_rooms_join_policy_check" CHECK (join_policy = ANY (ARRAY['open'::text, 'locked'::text]));
alter table only public."watch_party_rooms" add constraint "watch_party_rooms_playback_state_check" CHECK (playback_state = ANY (ARRAY['playing'::text, 'paused'::text, 'buffering'::text]));
alter table only public."watch_party_rooms" add constraint "watch_party_rooms_reactions_policy_check" CHECK (reactions_policy = ANY (ARRAY['enabled'::text, 'muted'::text]));
alter table only public."watch_party_rooms" add constraint "watch_party_rooms_room_type_check" CHECK (room_type = ANY (ARRAY['title'::text, 'live'::text]));

alter table only public."watch_party_sync_events" add constraint "watch_party_sync_events_pkey" PRIMARY KEY (id);
alter table only public."watch_party_sync_events" add constraint "watch_party_sync_events_party_id_fkey" FOREIGN KEY (party_id) REFERENCES watch_party_rooms(party_id) ON DELETE CASCADE;
alter table only public."watch_party_sync_events" add constraint "watch_party_sync_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only public."watch_party_sync_events" add constraint "watch_party_sync_events_kind_check" CHECK (kind = ANY (ARRAY['seek'::text, 'play'::text, 'pause'::text, 'join'::text, 'leave'::text, 'reaction'::text]));

-- Functions
CREATE OR REPLACE FUNCTION public.acknowledge_beta_onboarding()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  current_user_id text := nullif(trim(auth.uid()::text), '');
  current_email text := lower(nullif(trim(coalesce(auth.jwt() ->> 'email', '')), ''));
  membership public.beta_access_memberships%rowtype;
begin
  if current_user_id is null then
    return null;
  end if;

  update public.beta_access_memberships
  set onboarding_ack_at = coalesce(onboarding_ack_at, timezone('utc', now())),
      last_seen_at = timezone('utc', now())
  where access_status = 'active'
    and (
      user_id = current_user_id
      or (current_email is not null and lower(email) = current_email)
    )
  returning * into membership;

  if not found then
    return null;
  end if;

  return to_jsonb(membership);
end;
$function$;

CREATE OR REPLACE FUNCTION public.activate_beta_membership()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  current_user_id text := nullif(trim(auth.uid()::text), '');
  current_email text := lower(nullif(trim(coalesce(auth.jwt() ->> 'email', '')), ''));
  membership public.beta_access_memberships%rowtype;
begin
  if current_user_id is null then
    return null;
  end if;

  select *
  into membership
  from public.beta_access_memberships
  where user_id = current_user_id
     or (current_email is not null and lower(email) = current_email)
  order by case when user_id = current_user_id then 0 else 1 end, invited_at desc
  limit 1;

  if not found then
    return null;
  end if;

  update public.beta_access_memberships
  set user_id = coalesce(nullif(trim(beta_access_memberships.user_id), ''), current_user_id),
      email = coalesce(nullif(trim(beta_access_memberships.email), ''), current_email),
      access_status = case
        when beta_access_memberships.access_status = 'invited' then 'active'
        else beta_access_memberships.access_status
      end,
      activated_at = case
        when beta_access_memberships.access_status = 'invited'
          then coalesce(beta_access_memberships.activated_at, timezone('utc', now()))
        else beta_access_memberships.activated_at
      end,
      last_seen_at = timezone('utc', now())
  where id = membership.id
  returning * into membership;

  return to_jsonb(membership);
end;
$function$;

CREATE OR REPLACE FUNCTION public.app_configurations_sanitize_before_write()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.config := public.sanitize_app_configuration(new.config);
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.can_access_chat_thread(target_thread_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.chat_threads thread
    where thread.id = target_thread_id
      and thread.created_by = auth.uid()::text

    union all

    select 1
    from public.chat_thread_members member
    where member.thread_id = target_thread_id
      and member.user_id = auth.uid()::text
  );
$function$;

CREATE OR REPLACE FUNCTION public.can_manage_chat_thread_members(target_thread_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.chat_threads thread
    where thread.id = target_thread_id
      and thread.created_by = auth.uid()::text
  );
$function$;

CREATE OR REPLACE FUNCTION public.communication_room_join_allowed(target_room_id text, joining_user_id text)
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  with active_members as (
    select count(*)::int as count
    from public.communication_room_memberships membership
    where membership.room_id = target_room_id
      and membership.membership_state in ('active', 'reconnecting')
      and membership.last_seen_at >= now() - interval '25 seconds'
      and membership.user_id <> joining_user_id
  )
  select exists (
    select 1
    from public.communication_rooms room
    where room.room_id = target_room_id
      and room.status = 'active'
      and (
        room.host_user_id = joining_user_id
        or (select count from active_members) < 4
      )
  );
$function$;

CREATE OR REPLACE FUNCTION public.has_active_beta_access()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.beta_access_memberships membership
    where membership.access_status = 'active'
      and (
        membership.user_id = auth.uid()::text
        or (
          nullif(trim(coalesce(auth.jwt() ->> 'email', '')), '') is not null
          and lower(membership.email) = lower(trim(coalesce(auth.jwt() ->> 'email', '')))
        )
      )
  );
$function$;

CREATE OR REPLACE FUNCTION public.has_platform_role(required_roles text[])
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select auth.uid() is not null
    and coalesce(array_length(required_roles, 1), 0) > 0
    and exists (
      select 1
      from public.platform_role_memberships membership
      where membership.status = 'active'
        and membership.role = any(required_roles)
        and (
          membership.user_id = auth.uid()::text
          or (
            nullif(trim(coalesce(auth.jwt() ->> 'email', '')), '') is not null
            and lower(membership.email) = lower(trim(coalesce(auth.jwt() ->> 'email', '')))
          )
        )
    );
$function$;

CREATE OR REPLACE FUNCTION public.sanitize_app_configuration(input_config jsonb)
 RETURNS jsonb
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select
    jsonb_set(
      jsonb_set(
        jsonb_set(
          jsonb_set(
            jsonb_set(
              jsonb_set(
                case
                  when jsonb_typeof(coalesce(input_config, '{}'::jsonb)) = 'object'
                    then coalesce(input_config, '{}'::jsonb)
                  else '{}'::jsonb
                end,
                '{branding,appDisplayName}',
                to_jsonb('Chi''llywood'::text),
                true
              ),
              '{branding,watchPartyLabel}',
              to_jsonb('Live Watch-Party'::text),
              true
            ),
            '{branding,liveWaitingRoomTitle}',
            to_jsonb('Live Waiting Room'::text),
            true
          ),
          '{branding,partyWaitingRoomTitle}',
          to_jsonb('Party Waiting Room'::text),
          true
        ),
        '{branding,liveRoomTitle}',
        to_jsonb('Live Room'::text),
        true
      ),
      '{branding,partyRoomTitle}',
      to_jsonb('Party Room'::text),
      true
    );
$function$;

CREATE OR REPLACE FUNCTION public.set_chat_thread_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.sync_chat_thread_after_message_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  update public.chat_threads
  set
    last_message_at = new.created_at,
    last_message_preview = left(new.body, 160),
    updated_at = now()
  where id = new.thread_id;

  update public.chat_thread_members
  set
    unread_count = 0,
    last_read_at = new.created_at
  where thread_id = new.thread_id
    and user_id = new.sender_user_id;

  update public.chat_thread_members
  set unread_count = unread_count + 1
  where thread_id = new.thread_id
    and user_id <> new.sender_user_id;

  return new;
end;
$function$;

-- Indexes
CREATE INDEX beta_access_memberships_cohort_idx ON beta_access_memberships USING btree (cohort, invited_at DESC);
CREATE UNIQUE INDEX beta_access_memberships_email_idx ON beta_access_memberships USING btree (lower(email)) WHERE email IS NOT NULL AND length(TRIM(BOTH FROM email)) > 0;
CREATE INDEX beta_access_memberships_status_idx ON beta_access_memberships USING btree (access_status, invited_at DESC);
CREATE UNIQUE INDEX beta_access_memberships_user_idx ON beta_access_memberships USING btree (user_id) WHERE user_id IS NOT NULL AND length(TRIM(BOTH FROM user_id)) > 0;

CREATE INDEX beta_feedback_items_category_idx ON beta_feedback_items USING btree (category, created_at DESC);
CREATE INDEX beta_feedback_items_reporter_idx ON beta_feedback_items USING btree (reporter_user_id, created_at DESC);
CREATE INDEX beta_feedback_items_status_idx ON beta_feedback_items USING btree (status, severity, fix_window, created_at DESC);

CREATE INDEX chat_messages_thread_created_idx ON chat_messages USING btree (thread_id, created_at);

CREATE INDEX chat_thread_members_user_idx ON chat_thread_members USING btree (user_id, unread_count DESC, joined_at DESC);

CREATE INDEX chat_threads_last_message_idx ON chat_threads USING btree (last_message_at DESC NULLS LAST, updated_at DESC);

CREATE INDEX communication_room_memberships_room_seen_idx ON communication_room_memberships USING btree (room_id, last_seen_at DESC);
CREATE INDEX communication_room_memberships_room_state_idx ON communication_room_memberships USING btree (room_id, membership_state);

CREATE UNIQUE INDEX communication_rooms_active_linked_party_uidx ON communication_rooms USING btree (linked_party_id) WHERE status = 'active'::text AND linked_party_id IS NOT NULL;
CREATE INDEX communication_rooms_host_user_id_idx ON communication_rooms USING btree (host_user_id);
CREATE INDEX communication_rooms_linked_party_id_idx ON communication_rooms USING btree (linked_party_id);
CREATE INDEX communication_rooms_status_idx ON communication_rooms USING btree (status);

CREATE UNIQUE INDEX platform_role_memberships_email_role_idx ON platform_role_memberships USING btree (lower(email), role) WHERE email IS NOT NULL AND length(TRIM(BOTH FROM email)) > 0;
CREATE INDEX platform_role_memberships_role_status_idx ON platform_role_memberships USING btree (role, status, granted_at DESC);
CREATE UNIQUE INDEX platform_role_memberships_user_role_idx ON platform_role_memberships USING btree (user_id, role) WHERE user_id IS NOT NULL AND length(TRIM(BOTH FROM user_id)) > 0;

CREATE INDEX safety_reports_reporter_idx ON safety_reports USING btree (reporter_user_id, created_at DESC);
CREATE INDEX safety_reports_target_idx ON safety_reports USING btree (target_type, target_id, created_at DESC);

CREATE INDEX user_content_relationships_title_idx ON user_content_relationships USING btree (title_id, updated_at DESC);
CREATE INDEX user_content_relationships_user_type_idx ON user_content_relationships USING btree (user_id, relationship_type, updated_at DESC);

CREATE INDEX user_list_updated_idx ON user_list USING btree (user_id, updated_at DESC);

CREATE INDEX user_profiles_updated_at_idx ON user_profiles USING btree (updated_at DESC);

CREATE INDEX watch_history_last_watched_idx ON watch_history USING btree (user_id, last_watched_at DESC);

CREATE UNIQUE INDEX watch_party_pass_unlocks_room_user_idx ON watch_party_pass_unlocks USING btree (room_id, user_id);

CREATE INDEX watch_party_room_memberships_party_seen_idx ON watch_party_room_memberships USING btree (party_id, last_seen_at DESC);
CREATE INDEX watch_party_room_memberships_party_state_idx ON watch_party_room_memberships USING btree (party_id, membership_state);

CREATE INDEX watch_party_room_messages_party_created_idx ON watch_party_room_messages USING btree (party_id, created_at DESC);

CREATE INDEX watch_party_rooms_host_idx ON watch_party_rooms USING btree (host_user_id, updated_at DESC);

CREATE INDEX watch_party_sync_events_party_created_idx ON watch_party_sync_events USING btree (party_id, created_at DESC);

-- Triggers
CREATE TRIGGER app_configurations_sanitize_before_write BEFORE INSERT OR UPDATE ON app_configurations FOR EACH ROW EXECUTE FUNCTION app_configurations_sanitize_before_write();

CREATE TRIGGER chat_messages_sync_thread AFTER INSERT ON chat_messages FOR EACH ROW EXECUTE FUNCTION sync_chat_thread_after_message_insert();

CREATE TRIGGER chat_threads_set_updated_at BEFORE UPDATE ON chat_threads FOR EACH ROW EXECUTE FUNCTION set_chat_thread_updated_at();

-- Row level security
alter table public."app_configurations" enable row level security;
alter table public."beta_access_memberships" enable row level security;
alter table public."beta_feedback_items" enable row level security;
alter table public."chat_messages" enable row level security;
alter table public."chat_thread_members" enable row level security;
alter table public."chat_threads" enable row level security;
alter table public."communication_room_memberships" enable row level security;
alter table public."communication_rooms" enable row level security;
alter table public."creator_permissions" enable row level security;
alter table public."platform_role_memberships" enable row level security;
alter table public."profiles" enable row level security;
alter table public."safety_reports" enable row level security;
alter table public."titles" enable row level security;
alter table public."user_content_relationships" enable row level security;
alter table public."user_list" enable row level security;
alter table public."user_profiles" enable row level security;
alter table public."user_subscriptions" enable row level security;
alter table public."videos" enable row level security;
alter table public."watch_history" enable row level security;
alter table public."watch_party_pass_unlocks" enable row level security;
alter table public."watch_party_room_memberships" enable row level security;
alter table public."watch_party_room_messages" enable row level security;
alter table public."watch_party_rooms" enable row level security;
alter table public."watch_party_sync_events" enable row level security;

-- Policies
create policy "app_configurations_insert_operator" on public."app_configurations" for insert to "authenticated" with check (((auth.uid() IS NOT NULL) AND has_platform_role(ARRAY['operator'::text])));
create policy "app_configurations_select_policy" on public."app_configurations" for select to PUBLIC using (true);
create policy "app_configurations_update_operator" on public."app_configurations" for update to "authenticated" using (((auth.uid() IS NOT NULL) AND has_platform_role(ARRAY['operator'::text]))) with check (((auth.uid() IS NOT NULL) AND has_platform_role(ARRAY['operator'::text])));

create policy "beta_access_memberships_select_own" on public."beta_access_memberships" for select to PUBLIC using (((auth.uid() IS NOT NULL) AND ((user_id = (auth.uid())::text) OR ((NULLIF(TRIM(BOTH FROM COALESCE((auth.jwt() ->> 'email'::text), ''::text)), ''::text) IS NOT NULL) AND (lower(email) = lower(TRIM(BOTH FROM COALESCE((auth.jwt() ->> 'email'::text), ''::text))))))));

create policy "beta_feedback_items_insert_own" on public."beta_feedback_items" for insert to PUBLIC with check (((auth.uid() IS NOT NULL) AND (reporter_user_id = (auth.uid())::text)));
create policy "beta_feedback_items_select_own" on public."beta_feedback_items" for select to PUBLIC using (((auth.uid() IS NOT NULL) AND (reporter_user_id = (auth.uid())::text)));

create policy "chat_messages_insert_policy" on public."chat_messages" for insert to "authenticated" with check (((sender_user_id = (auth.uid())::text) AND (message_type = 'text'::text) AND can_access_chat_thread(thread_id)));
create policy "chat_messages_select_policy" on public."chat_messages" for select to "authenticated" using (can_access_chat_thread(thread_id));

create policy "chat_thread_members_insert_policy" on public."chat_thread_members" for insert to "authenticated" with check (can_manage_chat_thread_members(thread_id));
create policy "chat_thread_members_select_policy" on public."chat_thread_members" for select to "authenticated" using (can_access_chat_thread(thread_id));
create policy "chat_thread_members_update_policy" on public."chat_thread_members" for update to "authenticated" using ((user_id = (auth.uid())::text)) with check ((user_id = (auth.uid())::text));

create policy "chat_threads_insert_policy" on public."chat_threads" for insert to "authenticated" with check (((auth.uid() IS NOT NULL) AND (thread_kind = 'direct'::text)));
create policy "chat_threads_select_policy" on public."chat_threads" for select to "authenticated" using (can_access_chat_thread(id));
create policy "chat_threads_update_policy" on public."chat_threads" for update to "authenticated" using (can_access_chat_thread(id)) with check (can_access_chat_thread(id));

create policy "communication_room_memberships_host_update_policy" on public."communication_room_memberships" for update to PUBLIC using ((EXISTS ( SELECT 1
   FROM communication_rooms room
  WHERE ((room.room_id = communication_room_memberships.room_id) AND (room.host_user_id = (auth.uid())::text))))) with check ((EXISTS ( SELECT 1
   FROM communication_rooms room
  WHERE ((room.room_id = communication_room_memberships.room_id) AND (room.host_user_id = (auth.uid())::text)))));
create policy "communication_room_memberships_select_policy" on public."communication_room_memberships" for select to PUBLIC using ((EXISTS ( SELECT 1
   FROM communication_rooms room
  WHERE (room.room_id = communication_room_memberships.room_id))));
create policy "communication_room_memberships_self_insert_policy" on public."communication_room_memberships" for insert to PUBLIC with check (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text) AND communication_room_join_allowed(room_id, (auth.uid())::text)));
create policy "communication_room_memberships_self_update_policy" on public."communication_room_memberships" for update to PUBLIC using (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text))) with check (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text)));

create policy "communication_rooms_host_update_policy" on public."communication_rooms" for update to PUBLIC using (((auth.uid() IS NOT NULL) AND (host_user_id = (auth.uid())::text))) with check (((auth.uid() IS NOT NULL) AND (host_user_id = (auth.uid())::text)));
create policy "communication_rooms_insert_policy" on public."communication_rooms" for insert to PUBLIC with check (((auth.uid() IS NOT NULL) AND (host_user_id = (auth.uid())::text)));
create policy "communication_rooms_select_policy" on public."communication_rooms" for select to PUBLIC using (true);

create policy "creator_permissions_insert_operator" on public."creator_permissions" for insert to "authenticated" with check (((auth.uid() IS NOT NULL) AND has_platform_role(ARRAY['operator'::text])));
create policy "creator_permissions_select_self_or_operator" on public."creator_permissions" for select to "authenticated" using (((auth.uid() IS NOT NULL) AND ((user_id = (auth.uid())::text) OR has_platform_role(ARRAY['operator'::text]))));
create policy "creator_permissions_update_operator" on public."creator_permissions" for update to "authenticated" using (((auth.uid() IS NOT NULL) AND has_platform_role(ARRAY['operator'::text]))) with check (((auth.uid() IS NOT NULL) AND has_platform_role(ARRAY['operator'::text])));

create policy "platform_role_memberships_select_own" on public."platform_role_memberships" for select to "authenticated" using (((auth.uid() IS NOT NULL) AND ((user_id = (auth.uid())::text) OR ((NULLIF(TRIM(BOTH FROM COALESCE((auth.jwt() ->> 'email'::text), ''::text)), ''::text) IS NOT NULL) AND (lower(email) = lower(TRIM(BOTH FROM COALESCE((auth.jwt() ->> 'email'::text), ''::text))))))));

create policy "Public profiles readable" on public."profiles" for select to PUBLIC using (true);
create policy "Users can insert own profile" on public."profiles" for insert to PUBLIC with check ((auth.uid() = id));
create policy "Users can update own profile" on public."profiles" for update to PUBLIC using ((auth.uid() = id));

create policy "safety_reports_insert_own" on public."safety_reports" for insert to PUBLIC with check (((auth.uid() IS NOT NULL) AND (reporter_user_id = (auth.uid())::text)));
create policy "safety_reports_select_own" on public."safety_reports" for select to PUBLIC using (((auth.uid() IS NOT NULL) AND (reporter_user_id = (auth.uid())::text)));
create policy "safety_reports_select_review_queue" on public."safety_reports" for select to "authenticated" using (has_platform_role(ARRAY['operator'::text, 'moderator'::text]));

create policy "Enable read access for all users" on public."titles" for select to PUBLIC using (true);

create policy "user_content_relationships_delete_policy" on public."user_content_relationships" for delete to "authenticated" using ((user_id = (auth.uid())::text));
create policy "user_content_relationships_insert_policy" on public."user_content_relationships" for insert to "authenticated" with check (((user_id = (auth.uid())::text) AND (relationship_type = ANY (ARRAY['like'::text, 'share'::text]))));
create policy "user_content_relationships_select_policy" on public."user_content_relationships" for select to "authenticated" using (((user_id = (auth.uid())::text) OR ((relationship_type = 'like'::text) AND (EXISTS ( SELECT 1
   FROM user_profiles profile
  WHERE ((profile.user_id = user_content_relationships.user_id) AND (COALESCE(profile.likes_visibility, 'public'::text) = 'public'::text))))) OR ((relationship_type = 'share'::text) AND (EXISTS ( SELECT 1
   FROM user_profiles profile
  WHERE ((profile.user_id = user_content_relationships.user_id) AND (COALESCE(profile.shares_visibility, 'public'::text) = 'public'::text)))))));
create policy "user_content_relationships_update_policy" on public."user_content_relationships" for update to "authenticated" using ((user_id = (auth.uid())::text)) with check (((user_id = (auth.uid())::text) AND (relationship_type = ANY (ARRAY['like'::text, 'share'::text]))));

create policy "user_list_owner_delete" on public."user_list" for delete to PUBLIC using ((auth.uid() = user_id));
create policy "user_list_owner_insert" on public."user_list" for insert to PUBLIC with check ((auth.uid() = user_id));
create policy "user_list_owner_select" on public."user_list" for select to PUBLIC using ((auth.uid() = user_id));
create policy "user_list_owner_update" on public."user_list" for update to PUBLIC using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));

create policy "user_profiles_insert_policy" on public."user_profiles" for insert to "authenticated" with check ((user_id = (auth.uid())::text));
create policy "user_profiles_select_policy" on public."user_profiles" for select to "authenticated" using (true);
create policy "user_profiles_update_policy" on public."user_profiles" for update to "authenticated" using ((user_id = (auth.uid())::text)) with check ((user_id = (auth.uid())::text));

create policy "user_subscriptions_insert_own" on public."user_subscriptions" for insert to PUBLIC with check (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text)));
create policy "user_subscriptions_select_own" on public."user_subscriptions" for select to PUBLIC using (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text)));
create policy "user_subscriptions_update_own" on public."user_subscriptions" for update to PUBLIC using (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text))) with check (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text)));

create policy "Public videos readable" on public."videos" for select to PUBLIC using (true);
create policy "Users can delete own videos" on public."videos" for delete to PUBLIC using ((auth.uid() = owner_id));
create policy "Users can insert own videos" on public."videos" for insert to PUBLIC with check ((auth.uid() = owner_id));
create policy "Users can update own videos" on public."videos" for update to PUBLIC using ((auth.uid() = owner_id));

create policy "watch_history_owner_delete" on public."watch_history" for delete to PUBLIC using ((auth.uid() = user_id));
create policy "watch_history_owner_insert" on public."watch_history" for insert to PUBLIC with check ((auth.uid() = user_id));
create policy "watch_history_owner_select" on public."watch_history" for select to PUBLIC using ((auth.uid() = user_id));
create policy "watch_history_owner_update" on public."watch_history" for update to PUBLIC using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));

create policy "watch_party_pass_unlocks_insert_own" on public."watch_party_pass_unlocks" for insert to PUBLIC with check (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text)));
create policy "watch_party_pass_unlocks_select_own" on public."watch_party_pass_unlocks" for select to PUBLIC using (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text)));
create policy "watch_party_pass_unlocks_update_own" on public."watch_party_pass_unlocks" for update to PUBLIC using (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text))) with check (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text)));

create policy "watch_party_room_memberships_host_update_policy" on public."watch_party_room_memberships" for update to PUBLIC using ((EXISTS ( SELECT 1
   FROM watch_party_rooms room
  WHERE ((room.party_id = watch_party_room_memberships.party_id) AND (room.host_user_id = auth.uid()))))) with check ((EXISTS ( SELECT 1
   FROM watch_party_rooms room
  WHERE ((room.party_id = watch_party_room_memberships.party_id) AND (room.host_user_id = auth.uid())))));
create policy "watch_party_room_memberships_select_policy" on public."watch_party_room_memberships" for select to PUBLIC using ((EXISTS ( SELECT 1
   FROM watch_party_rooms room
  WHERE (room.party_id = watch_party_room_memberships.party_id))));
create policy "watch_party_room_memberships_self_insert_policy" on public."watch_party_room_memberships" for insert to PUBLIC with check (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text) AND (EXISTS ( SELECT 1
   FROM watch_party_rooms room
  WHERE ((room.party_id = watch_party_room_memberships.party_id) AND ((room.host_user_id = auth.uid()) OR (room.join_policy = 'open'::text)))))));
create policy "watch_party_room_memberships_self_update_policy" on public."watch_party_room_memberships" for update to PUBLIC using (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text))) with check (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text)));

create policy "watch_party_room_messages_insert_policy" on public."watch_party_room_messages" for insert to PUBLIC with check (((auth.uid() IS NOT NULL) AND (user_id = (auth.uid())::text) AND (EXISTS ( SELECT 1
   FROM watch_party_room_memberships membership
  WHERE ((membership.party_id = watch_party_room_messages.party_id) AND (membership.user_id = (auth.uid())::text) AND (membership.membership_state = ANY (ARRAY['active'::text, 'reconnecting'::text])))))));
create policy "watch_party_room_messages_select_policy" on public."watch_party_room_messages" for select to PUBLIC using ((EXISTS ( SELECT 1
   FROM watch_party_rooms room
  WHERE (room.party_id = watch_party_room_messages.party_id))));

create policy "allow_anon_insert_watch_party" on public."watch_party_rooms" for insert to PUBLIC with check (true);
create policy "watch_party_rooms_authenticated_select" on public."watch_party_rooms" for select to PUBLIC using ((auth.role() = 'authenticated'::text));
create policy "watch_party_rooms_host_delete" on public."watch_party_rooms" for delete to PUBLIC using ((auth.uid() = host_user_id));
create policy "watch_party_rooms_host_insert" on public."watch_party_rooms" for insert to PUBLIC with check ((auth.uid() = host_user_id));
create policy "watch_party_rooms_host_update" on public."watch_party_rooms" for update to PUBLIC using ((auth.uid() = host_user_id)) with check ((auth.uid() = host_user_id));
create policy "watch_party_rooms_host_update_policy" on public."watch_party_rooms" for update to PUBLIC using (((auth.uid() IS NOT NULL) AND (host_user_id = auth.uid()))) with check (((auth.uid() IS NOT NULL) AND (host_user_id = auth.uid())));
create policy "watch_party_rooms_insert_policy" on public."watch_party_rooms" for insert to PUBLIC with check (((auth.uid() IS NOT NULL) AND (host_user_id = auth.uid())));
create policy "watch_party_rooms_select_policy" on public."watch_party_rooms" for select to PUBLIC using (true);

create policy "watch_party_sync_events_authenticated_select" on public."watch_party_sync_events" for select to PUBLIC using ((auth.role() = 'authenticated'::text));
create policy "watch_party_sync_events_insert_policy" on public."watch_party_sync_events" for insert to PUBLIC with check (((auth.uid() IS NOT NULL) AND (user_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM watch_party_room_memberships membership
  WHERE ((membership.party_id = watch_party_sync_events.party_id) AND (membership.user_id = (auth.uid())::text) AND (membership.membership_state = ANY (ARRAY['active'::text, 'reconnecting'::text])))))));
create policy "watch_party_sync_events_owner_delete" on public."watch_party_sync_events" for delete to PUBLIC using ((auth.uid() = user_id));
create policy "watch_party_sync_events_owner_insert" on public."watch_party_sync_events" for insert to PUBLIC with check ((auth.uid() = user_id));
create policy "watch_party_sync_events_owner_update" on public."watch_party_sync_events" for update to PUBLIC using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "watch_party_sync_events_select_policy" on public."watch_party_sync_events" for select to PUBLIC using (true);

-- Table grants
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."app_configurations" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."app_configurations" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."app_configurations" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."app_configurations" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."beta_access_memberships" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."beta_access_memberships" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."beta_access_memberships" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."beta_access_memberships" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."beta_feedback_items" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."beta_feedback_items" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."beta_feedback_items" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."beta_feedback_items" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."chat_messages" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."chat_messages" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."chat_messages" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."chat_messages" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."chat_thread_members" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."chat_thread_members" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."chat_thread_members" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."chat_thread_members" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."chat_threads" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."chat_threads" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."chat_threads" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."chat_threads" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."communication_room_memberships" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."communication_room_memberships" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."communication_room_memberships" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."communication_room_memberships" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."communication_rooms" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."communication_rooms" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."communication_rooms" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."communication_rooms" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."creator_permissions" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."creator_permissions" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."creator_permissions" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."platform_role_memberships" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."platform_role_memberships" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."platform_role_memberships" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."platform_role_memberships" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."profiles" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."profiles" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."profiles" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."profiles" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."safety_reports" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."safety_reports" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."safety_reports" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."safety_reports" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."titles" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."titles" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."titles" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."titles" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_content_relationships" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_content_relationships" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_content_relationships" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_content_relationships" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_list" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_list" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_list" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_list" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_profiles" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_profiles" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_profiles" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_subscriptions" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_subscriptions" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_subscriptions" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."user_subscriptions" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."videos" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."videos" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."videos" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."videos" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_history" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_history" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_history" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_history" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_pass_unlocks" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_pass_unlocks" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_pass_unlocks" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_pass_unlocks" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_room_memberships" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_room_memberships" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_room_memberships" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_room_memberships" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_room_messages" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_room_messages" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_room_messages" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_room_messages" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_rooms" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_rooms" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_rooms" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_rooms" to "service_role";

grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_sync_events" to "anon";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_sync_events" to "authenticated";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_sync_events" to "postgres";
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public."watch_party_sync_events" to "service_role";

-- Function grants
grant EXECUTE on function public."acknowledge_beta_onboarding"() to "anon";
grant EXECUTE on function public."acknowledge_beta_onboarding"() to "authenticated";
grant EXECUTE on function public."acknowledge_beta_onboarding"() to "postgres";
grant EXECUTE on function public."acknowledge_beta_onboarding"() to "service_role";

grant EXECUTE on function public."activate_beta_membership"() to "anon";
grant EXECUTE on function public."activate_beta_membership"() to "authenticated";
grant EXECUTE on function public."activate_beta_membership"() to "postgres";
grant EXECUTE on function public."activate_beta_membership"() to "service_role";

grant EXECUTE on function public."app_configurations_sanitize_before_write"() to PUBLIC;
grant EXECUTE on function public."app_configurations_sanitize_before_write"() to "anon";
grant EXECUTE on function public."app_configurations_sanitize_before_write"() to "authenticated";
grant EXECUTE on function public."app_configurations_sanitize_before_write"() to "postgres";
grant EXECUTE on function public."app_configurations_sanitize_before_write"() to "service_role";

grant EXECUTE on function public."can_access_chat_thread"(target_thread_id uuid) to "anon";
grant EXECUTE on function public."can_access_chat_thread"(target_thread_id uuid) to "authenticated";
grant EXECUTE on function public."can_access_chat_thread"(target_thread_id uuid) to "postgres";
grant EXECUTE on function public."can_access_chat_thread"(target_thread_id uuid) to "service_role";

grant EXECUTE on function public."can_manage_chat_thread_members"(target_thread_id uuid) to "anon";
grant EXECUTE on function public."can_manage_chat_thread_members"(target_thread_id uuid) to "authenticated";
grant EXECUTE on function public."can_manage_chat_thread_members"(target_thread_id uuid) to "postgres";
grant EXECUTE on function public."can_manage_chat_thread_members"(target_thread_id uuid) to "service_role";

grant EXECUTE on function public."communication_room_join_allowed"(target_room_id text, joining_user_id text) to PUBLIC;
grant EXECUTE on function public."communication_room_join_allowed"(target_room_id text, joining_user_id text) to "anon";
grant EXECUTE on function public."communication_room_join_allowed"(target_room_id text, joining_user_id text) to "authenticated";
grant EXECUTE on function public."communication_room_join_allowed"(target_room_id text, joining_user_id text) to "postgres";
grant EXECUTE on function public."communication_room_join_allowed"(target_room_id text, joining_user_id text) to "service_role";

grant EXECUTE on function public."has_active_beta_access"() to "anon";
grant EXECUTE on function public."has_active_beta_access"() to "authenticated";
grant EXECUTE on function public."has_active_beta_access"() to "postgres";
grant EXECUTE on function public."has_active_beta_access"() to "service_role";

grant EXECUTE on function public."has_platform_role"(required_roles text[]) to "anon";
grant EXECUTE on function public."has_platform_role"(required_roles text[]) to "authenticated";
grant EXECUTE on function public."has_platform_role"(required_roles text[]) to "postgres";
grant EXECUTE on function public."has_platform_role"(required_roles text[]) to "service_role";

grant EXECUTE on function public."sanitize_app_configuration"(input_config jsonb) to PUBLIC;
grant EXECUTE on function public."sanitize_app_configuration"(input_config jsonb) to "anon";
grant EXECUTE on function public."sanitize_app_configuration"(input_config jsonb) to "authenticated";
grant EXECUTE on function public."sanitize_app_configuration"(input_config jsonb) to "postgres";
grant EXECUTE on function public."sanitize_app_configuration"(input_config jsonb) to "service_role";

grant EXECUTE on function public."set_chat_thread_updated_at"() to PUBLIC;
grant EXECUTE on function public."set_chat_thread_updated_at"() to "anon";
grant EXECUTE on function public."set_chat_thread_updated_at"() to "authenticated";
grant EXECUTE on function public."set_chat_thread_updated_at"() to "postgres";
grant EXECUTE on function public."set_chat_thread_updated_at"() to "service_role";

grant EXECUTE on function public."sync_chat_thread_after_message_insert"() to PUBLIC;
grant EXECUTE on function public."sync_chat_thread_after_message_insert"() to "anon";
grant EXECUTE on function public."sync_chat_thread_after_message_insert"() to "authenticated";
grant EXECUTE on function public."sync_chat_thread_after_message_insert"() to "postgres";
grant EXECUTE on function public."sync_chat_thread_after_message_insert"() to "service_role";
