create table if not exists public."platform_finance_ledger_events" (
  "id" bigint generated by default as identity not null,
  "event_type" text not null,
  "source_type" text default 'unknown'::text not null,
  "source_id" text,
  "owner_user_id" text,
  "amount_minor" bigint default 0 not null,
  "currency" text default 'usd'::text not null,
  "direction" text default 'credit'::text not null,
  "status" text default 'pending'::text not null,
  "occurred_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "recorded_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "metadata" jsonb default '{}'::jsonb not null,
  constraint "platform_finance_ledger_events_pkey" primary key ("id"),
  constraint "platform_finance_ledger_events_event_type_check"
    check ("event_type" in (
      'premium_revenue',
      'ad_revenue',
      'sponsor_revenue',
      'paid_content_revenue',
      'tip_revenue',
      'network_revenue',
      'refund',
      'chargeback',
      'adjustment',
      'manual_correction'
    )),
  constraint "platform_finance_ledger_events_source_type_check"
    check ("source_type" in (
      'revenuecat',
      'app_store',
      'google_play',
      'applovin',
      'sponsor',
      'network_plan',
      'paid_content',
      'tip',
      'manual',
      'unknown'
    )),
  constraint "platform_finance_ledger_events_amount_check" check ("amount_minor" >= 0),
  constraint "platform_finance_ledger_events_currency_check" check ("currency" ~ '^[a-z]{3}$'),
  constraint "platform_finance_ledger_events_direction_check" check ("direction" in ('credit', 'debit', 'neutral')),
  constraint "platform_finance_ledger_events_status_check"
    check ("status" in ('pending', 'recorded', 'reconciled', 'void', 'disputed', 'reversed'))
);

create index if not exists "platform_finance_ledger_events_type_occurred_idx"
  on public."platform_finance_ledger_events" using btree ("event_type", "occurred_at" desc);

create index if not exists "platform_finance_ledger_events_owner_type_idx"
  on public."platform_finance_ledger_events" using btree ("owner_user_id", "event_type", "occurred_at" desc);

create table if not exists public."creator_payout_ledger_entries" (
  "id" bigint generated by default as identity not null,
  "creator_user_id" text not null,
  "source_ledger_event_id" bigint,
  "entry_type" text default 'payable'::text not null,
  "amount_minor" bigint default 0 not null,
  "currency" text default 'usd'::text not null,
  "status" text default 'pending'::text not null,
  "hold_reason" text,
  "hold_until" timestamp with time zone,
  "payout_provider" text,
  "payout_provider_reference" text,
  "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "metadata" jsonb default '{}'::jsonb not null,
  constraint "creator_payout_ledger_entries_pkey" primary key ("id"),
  constraint "creator_payout_ledger_entries_source_event_fkey"
    foreign key ("source_ledger_event_id") references public."platform_finance_ledger_events"("id") on delete set null,
  constraint "creator_payout_ledger_entries_type_check"
    check ("entry_type" in ('payable', 'hold', 'release', 'payout', 'reversal', 'adjustment')),
  constraint "creator_payout_ledger_entries_amount_check" check ("amount_minor" >= 0),
  constraint "creator_payout_ledger_entries_currency_check" check ("currency" ~ '^[a-z]{3}$'),
  constraint "creator_payout_ledger_entries_status_check"
    check ("status" in ('pending', 'held', 'available', 'scheduled', 'paid', 'canceled', 'reversed'))
);

create index if not exists "creator_payout_ledger_entries_creator_status_idx"
  on public."creator_payout_ledger_entries" using btree ("creator_user_id", "status", "created_at" desc);

create table if not exists public."network_billing_accounts" (
  "id" bigint generated by default as identity not null,
  "network_owner_user_id" text,
  "network_name" text,
  "plan_key" text,
  "status" text default 'foundation'::text not null,
  "billing_provider" text,
  "billing_provider_customer_id" text,
  "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "metadata" jsonb default '{}'::jsonb not null,
  constraint "network_billing_accounts_pkey" primary key ("id"),
  constraint "network_billing_accounts_status_check"
    check ("status" in ('foundation', 'active', 'paused', 'closed'))
);

create index if not exists "network_billing_accounts_owner_status_idx"
  on public."network_billing_accounts" using btree ("network_owner_user_id", "status", "created_at" desc);

create table if not exists public."network_invoice_records" (
  "id" bigint generated by default as identity not null,
  "network_billing_account_id" bigint,
  "invoice_number" text,
  "invoice_period_start" date,
  "invoice_period_end" date,
  "amount_minor" bigint default 0 not null,
  "currency" text default 'usd'::text not null,
  "status" text default 'foundation'::text not null,
  "billing_provider" text,
  "billing_provider_invoice_id" text,
  "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "metadata" jsonb default '{}'::jsonb not null,
  constraint "network_invoice_records_pkey" primary key ("id"),
  constraint "network_invoice_records_account_fkey"
    foreign key ("network_billing_account_id") references public."network_billing_accounts"("id") on delete set null,
  constraint "network_invoice_records_amount_check" check ("amount_minor" >= 0),
  constraint "network_invoice_records_currency_check" check ("currency" ~ '^[a-z]{3}$'),
  constraint "network_invoice_records_status_check"
    check ("status" in ('foundation', 'draft', 'open', 'paid', 'void', 'uncollectible'))
);

create index if not exists "network_invoice_records_account_status_idx"
  on public."network_invoice_records" using btree ("network_billing_account_id", "status", "created_at" desc);

create table if not exists public."sponsor_deal_records" (
  "id" bigint generated by default as identity not null,
  "creator_user_id" text,
  "brand_name" text,
  "deal_title" text,
  "deal_type" text default 'unknown'::text not null,
  "status" text default 'foundation'::text not null,
  "gross_amount_minor" bigint,
  "currency" text default 'usd'::text not null,
  "disclosure_required" boolean default true not null,
  "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "metadata" jsonb default '{}'::jsonb not null,
  constraint "sponsor_deal_records_pkey" primary key ("id"),
  constraint "sponsor_deal_records_type_check" check ("deal_type" in ('creator_sold', 'platform_served', 'unknown')),
  constraint "sponsor_deal_records_status_check"
    check ("status" in ('foundation', 'submitted', 'under_review', 'approved', 'active', 'completed', 'rejected', 'canceled')),
  constraint "sponsor_deal_records_amount_check" check ("gross_amount_minor" is null or "gross_amount_minor" >= 0),
  constraint "sponsor_deal_records_currency_check" check ("currency" ~ '^[a-z]{3}$')
);

create index if not exists "sponsor_deal_records_creator_status_idx"
  on public."sponsor_deal_records" using btree ("creator_user_id", "status", "created_at" desc);

create table if not exists public."platform_fraud_holds" (
  "id" bigint generated by default as identity not null,
  "target_type" text default 'unknown'::text not null,
  "target_id" text,
  "user_id" text,
  "reason" text not null,
  "status" text default 'active'::text not null,
  "enforcement_scope" text default 'foundation_only'::text not null,
  "created_by_user_id" text,
  "released_by_user_id" text,
  "created_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "released_at" timestamp with time zone,
  "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "metadata" jsonb default '{}'::jsonb not null,
  constraint "platform_fraud_holds_pkey" primary key ("id"),
  constraint "platform_fraud_holds_target_type_check"
    check ("target_type" in ('user', 'channel', 'content', 'ledger_event', 'payout_entry', 'sponsor_deal', 'network_account', 'unknown')),
  constraint "platform_fraud_holds_status_check" check ("status" in ('active', 'released', 'expired')),
  constraint "platform_fraud_holds_scope_check"
    check ("enforcement_scope" in ('foundation_only', 'payouts_later', 'monetization_later', 'uploads_live_later'))
);

create index if not exists "platform_fraud_holds_target_status_idx"
  on public."platform_fraud_holds" using btree ("target_type", "target_id", "status", "created_at" desc);

alter table public."platform_finance_ledger_events" enable row level security;
alter table public."creator_payout_ledger_entries" enable row level security;
alter table public."network_billing_accounts" enable row level security;
alter table public."network_invoice_records" enable row level security;
alter table public."sponsor_deal_records" enable row level security;
alter table public."platform_fraud_holds" enable row level security;

drop policy if exists "platform_finance_ledger_events_select_owner_operator" on public."platform_finance_ledger_events";
create policy "platform_finance_ledger_events_select_owner_operator"
  on public."platform_finance_ledger_events"
  for select
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "platform_finance_ledger_events_insert_owner_operator" on public."platform_finance_ledger_events";
create policy "platform_finance_ledger_events_insert_owner_operator"
  on public."platform_finance_ledger_events"
  for insert
  to "authenticated"
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "platform_finance_ledger_events_update_owner_operator" on public."platform_finance_ledger_events";
create policy "platform_finance_ledger_events_update_owner_operator"
  on public."platform_finance_ledger_events"
  for update
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text]))
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "creator_payout_ledger_entries_select_owner_operator" on public."creator_payout_ledger_entries";
create policy "creator_payout_ledger_entries_select_owner_operator"
  on public."creator_payout_ledger_entries"
  for select
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "creator_payout_ledger_entries_insert_owner_operator" on public."creator_payout_ledger_entries";
create policy "creator_payout_ledger_entries_insert_owner_operator"
  on public."creator_payout_ledger_entries"
  for insert
  to "authenticated"
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "creator_payout_ledger_entries_update_owner_operator" on public."creator_payout_ledger_entries";
create policy "creator_payout_ledger_entries_update_owner_operator"
  on public."creator_payout_ledger_entries"
  for update
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text]))
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "network_billing_accounts_select_owner_operator" on public."network_billing_accounts";
create policy "network_billing_accounts_select_owner_operator"
  on public."network_billing_accounts"
  for select
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "network_billing_accounts_insert_owner_operator" on public."network_billing_accounts";
create policy "network_billing_accounts_insert_owner_operator"
  on public."network_billing_accounts"
  for insert
  to "authenticated"
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "network_billing_accounts_update_owner_operator" on public."network_billing_accounts";
create policy "network_billing_accounts_update_owner_operator"
  on public."network_billing_accounts"
  for update
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text]))
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "network_invoice_records_select_owner_operator" on public."network_invoice_records";
create policy "network_invoice_records_select_owner_operator"
  on public."network_invoice_records"
  for select
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "network_invoice_records_insert_owner_operator" on public."network_invoice_records";
create policy "network_invoice_records_insert_owner_operator"
  on public."network_invoice_records"
  for insert
  to "authenticated"
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "network_invoice_records_update_owner_operator" on public."network_invoice_records";
create policy "network_invoice_records_update_owner_operator"
  on public."network_invoice_records"
  for update
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text]))
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "sponsor_deal_records_select_owner_operator" on public."sponsor_deal_records";
create policy "sponsor_deal_records_select_owner_operator"
  on public."sponsor_deal_records"
  for select
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "sponsor_deal_records_insert_owner_operator" on public."sponsor_deal_records";
create policy "sponsor_deal_records_insert_owner_operator"
  on public."sponsor_deal_records"
  for insert
  to "authenticated"
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "sponsor_deal_records_update_owner_operator" on public."sponsor_deal_records";
create policy "sponsor_deal_records_update_owner_operator"
  on public."sponsor_deal_records"
  for update
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text]))
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "platform_fraud_holds_select_platform_roles" on public."platform_fraud_holds";
create policy "platform_fraud_holds_select_platform_roles"
  on public."platform_fraud_holds"
  for select
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text, 'moderator'::text]));

drop policy if exists "platform_fraud_holds_insert_owner_operator" on public."platform_fraud_holds";
create policy "platform_fraud_holds_insert_owner_operator"
  on public."platform_fraud_holds"
  for insert
  to "authenticated"
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "platform_fraud_holds_update_owner_operator" on public."platform_fraud_holds";
create policy "platform_fraud_holds_update_owner_operator"
  on public."platform_fraud_holds"
  for update
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text]))
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

grant select, insert, update on table public."platform_finance_ledger_events" to "authenticated";
grant select, insert, update on table public."creator_payout_ledger_entries" to "authenticated";
grant select, insert, update on table public."network_billing_accounts" to "authenticated";
grant select, insert, update on table public."network_invoice_records" to "authenticated";
grant select, insert, update on table public."sponsor_deal_records" to "authenticated";
grant select, insert, update on table public."platform_fraud_holds" to "authenticated";

grant usage, select on sequence public."platform_finance_ledger_events_id_seq" to "authenticated";
grant usage, select on sequence public."creator_payout_ledger_entries_id_seq" to "authenticated";
grant usage, select on sequence public."network_billing_accounts_id_seq" to "authenticated";
grant usage, select on sequence public."network_invoice_records_id_seq" to "authenticated";
grant usage, select on sequence public."sponsor_deal_records_id_seq" to "authenticated";
grant usage, select on sequence public."platform_fraud_holds_id_seq" to "authenticated";
