create table if not exists public.safety_reports (
  id bigint generated by default as identity primary key,
  reporter_user_id text not null,
  target_type text not null,
  target_id text not null,
  category text not null,
  note text,
  room_id text,
  title_id text,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'safety_reports_target_type_check'
      and conrelid = 'public.safety_reports'::regclass
  ) then
    alter table public.safety_reports
      add constraint safety_reports_target_type_check
      check (target_type in ('participant', 'room', 'title'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'safety_reports_category_check'
      and conrelid = 'public.safety_reports'::regclass
  ) then
    alter table public.safety_reports
      add constraint safety_reports_category_check
      check (category in ('abuse', 'harassment', 'impersonation', 'copyright', 'safety', 'other'));
  end if;
end $$;

create index if not exists safety_reports_reporter_idx
  on public.safety_reports (reporter_user_id, created_at desc);

create index if not exists safety_reports_target_idx
  on public.safety_reports (target_type, target_id, created_at desc);

alter table if exists public.safety_reports enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'safety_reports'
      and policyname = 'safety_reports_select_own'
  ) then
    create policy safety_reports_select_own
      on public.safety_reports
      for select
      using (auth.uid() is not null and reporter_user_id = auth.uid()::text);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'safety_reports'
      and policyname = 'safety_reports_insert_own'
  ) then
    create policy safety_reports_insert_own
      on public.safety_reports
      for insert
      with check (auth.uid() is not null and reporter_user_id = auth.uid()::text);
  end if;
end $$;
