create table if not exists public."platform_usage_metering_events" (
  "id" bigint generated by default as identity not null,
  "metric_key" text not null,
  "source_type" text default 'unknown'::text not null,
  "source_id" text,
  "owner_user_id" text,
  "quantity" numeric(20, 4) not null,
  "unit" text not null,
  "occurred_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "recorded_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "metadata" jsonb default '{}'::jsonb not null,
  constraint "platform_usage_metering_events_pkey" primary key ("id"),
  constraint "platform_usage_metering_events_metric_check"
    check ("metric_key" in ('bandwidth_bytes', 'participant_minutes', 'storage_bytes')),
  constraint "platform_usage_metering_events_quantity_check"
    check ("quantity" >= 0),
  constraint "platform_usage_metering_events_unit_check"
    check ("unit" in ('bytes', 'minutes'))
);

create index if not exists "platform_usage_metering_events_metric_occurred_idx"
  on public."platform_usage_metering_events" using btree ("metric_key", "occurred_at" desc);

create index if not exists "platform_usage_metering_events_owner_metric_idx"
  on public."platform_usage_metering_events" using btree ("owner_user_id", "metric_key", "occurred_at" desc);

create table if not exists public."platform_usage_daily_rollups" (
  "id" bigint generated by default as identity not null,
  "rollup_date" date not null,
  "metric_key" text not null,
  "source_type" text default 'unknown'::text not null,
  "owner_user_id" text,
  "quantity" numeric(20, 4) default 0 not null,
  "unit" text not null,
  "event_count" integer default 0 not null,
  "generated_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "metadata" jsonb default '{}'::jsonb not null,
  constraint "platform_usage_daily_rollups_pkey" primary key ("id"),
  constraint "platform_usage_daily_rollups_metric_check"
    check ("metric_key" in ('bandwidth_bytes', 'participant_minutes', 'storage_bytes')),
  constraint "platform_usage_daily_rollups_quantity_check"
    check ("quantity" >= 0),
  constraint "platform_usage_daily_rollups_event_count_check"
    check ("event_count" >= 0),
  constraint "platform_usage_daily_rollups_unit_check"
    check ("unit" in ('bytes', 'minutes'))
);

create index if not exists "platform_usage_daily_rollups_date_metric_idx"
  on public."platform_usage_daily_rollups" using btree ("rollup_date" desc, "metric_key");

create index if not exists "platform_usage_daily_rollups_owner_metric_idx"
  on public."platform_usage_daily_rollups" using btree ("owner_user_id", "metric_key", "rollup_date" desc);

alter table public."platform_usage_metering_events" enable row level security;
alter table public."platform_usage_daily_rollups" enable row level security;

drop policy if exists "platform_usage_metering_events_select_platform_roles"
  on public."platform_usage_metering_events";
create policy "platform_usage_metering_events_select_platform_roles"
  on public."platform_usage_metering_events"
  for select
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text, 'moderator'::text]));

drop policy if exists "platform_usage_metering_events_insert_owner_operator"
  on public."platform_usage_metering_events";
create policy "platform_usage_metering_events_insert_owner_operator"
  on public."platform_usage_metering_events"
  for insert
  to "authenticated"
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "platform_usage_metering_events_update_owner_operator"
  on public."platform_usage_metering_events";
create policy "platform_usage_metering_events_update_owner_operator"
  on public."platform_usage_metering_events"
  for update
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text]))
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "platform_usage_daily_rollups_select_platform_roles"
  on public."platform_usage_daily_rollups";
create policy "platform_usage_daily_rollups_select_platform_roles"
  on public."platform_usage_daily_rollups"
  for select
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text, 'moderator'::text]));

drop policy if exists "platform_usage_daily_rollups_insert_owner_operator"
  on public."platform_usage_daily_rollups";
create policy "platform_usage_daily_rollups_insert_owner_operator"
  on public."platform_usage_daily_rollups"
  for insert
  to "authenticated"
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

drop policy if exists "platform_usage_daily_rollups_update_owner_operator"
  on public."platform_usage_daily_rollups";
create policy "platform_usage_daily_rollups_update_owner_operator"
  on public."platform_usage_daily_rollups"
  for update
  to "authenticated"
  using (public.has_platform_role(array['owner'::text, 'operator'::text]))
  with check (public.has_platform_role(array['owner'::text, 'operator'::text]));

grant select, insert, update on table public."platform_usage_metering_events" to "authenticated";
grant select, insert, update on table public."platform_usage_daily_rollups" to "authenticated";
grant usage, select on sequence public."platform_usage_metering_events_id_seq" to "authenticated";
grant usage, select on sequence public."platform_usage_daily_rollups_id_seq" to "authenticated";
